### PR TITLE
ICU-21408 Prohibit alpha4 as language inside tlang.

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21408
- [X] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [X] Tests included
- [X] Documentation is changed or added

### CODE REVIEW

**Review by markusicu — COMMENTED** [review]
lgtm

but please also test (& fix if necessary) in Java

**Comment by FrankYFTang** [comment]
Fixing java would be a lot of work because in C++ LocaleBuilder is based on the UTS35 grammar and parse -t- -u- and -x- and other extension . But in Java right now the ULocale.Builder is based on BCP47 grammar and parse -u- and -x- an other extension and does not parse -t- extension based on UTS35. Could I land this small fix for C++ first?

**Comment by markusicu** [comment]
> Could I land this small fix for C++ first?

yes, ok

**Review by markusicu — APPROVED** [review]
lgtm

**Pull request merged**
