### PR TITLE
ICU-20964 Fix small typo mistake

### PR DESCRIPTION
**Pull request by younies**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20964
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by jefgen** [comment]
Testing out manually triggering CI builds.

**Comment by jefgen** [comment]
Thanks for this PR @younies.

> Commit message for 855a27c fails validation 

Please use `git commit --amend` to fix the commit message to remove the colon.

Ex: `git commit --amend -m "ICU-20964 Fix small typo mistake"`

(Note: I've already updated/fixed the PR title on GitHub).

**Comment by markusicu** [comment]
ping @younies

**Comment by younies** [comment]
Done!

**Comment by jefgen** [comment]
Note: Please ignore the failing AppVeyor build for now. (See PR #1066).

**Pull request merged**
