### PR TITLE
ICU-22560 Merge ICU 74 maintenance branch to main

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22560
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
I suppose that we could also use the rc BRS ticket, in this case ICU-22534.

Unfortunately we have exhaustive-test failures now :-(
@dra8an @pedberg-icu did you run the exhaustive tests in the beta5 integration PR?

[test log](https://dev.azure.com/ms/icu/_build/results?buildId=508675&view=logs&jobId=eebd8c5b-7fc0-5066-6a66-50a75df23287&j=eebd8c5b-7fc0-5066-6a66-50a75df23287&t=0ea4acc7-ed89-5580-13a5-9418dd84ec87)
```
    VerifyTranslation   {
"    (Known issue cldrbug:15355) ks_Deva day names use chars not in exemplars
!!    getMonthNames(kxv, 7) at index 5 returned characters not in the exemplar characters: 0129.
!!    getDayNames(kxv_Deva, 1) at index 3 returned characters not in the exemplar characters: 0945.
!!    getDayNames(kxv_Deva_IN, 1) at index 3 returned characters not in the exemplar characters: 0945.
!!    getMonthNames(kxv_Latn, 7) at index 5 returned characters not in the exemplar characters: 0129.
!!    getMonthNames(kxv_Latn_IN, 7) at index 5 returned characters not in the exemplar characters: 0129.
"    (Known issue cldrbug:8899) lrc and mzn locales don't have translated day names
"    (Known issue cldrbug:14995) mai/sd_Deva day names use chars not in exemplars
"    (Known issue 11217) Fix result of uscript_getCode for yi: USCRIPT_YI -> USCRIPT_HEBREW
    } ---[5 ERRORS in /tsutil/cldrtest/VerifyTranslation]  (231ms) 
```

**Comment by markusicu** [comment]
FYI

> Unfortunately we have exhaustive-test failures now :-(

Fixed in https://github.com/unicode-org/icu/pull/2690

**Comment by markusicu** [comment]
Does this PR magically auto-include new commits on the source branch?

**Comment by sffc** [comment]
> Does this PR magically auto-include new commits on the source branch?

Yes.

Keep in mind that one must use a merge commit, not a rebase, to merge this.

**Review by markusicu — APPROVED** [review]

**Pull request merged**
