### PR TITLE
ICU-22333 Exclude ExhaustivePersonNameFormatterTest also from releaseJ…

### PR DESCRIPTION
**Pull request by yumaoka**
…arCheck target.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22333
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
rslgtm

**Comment by markusicu** [comment]
FYI typo in the commit message; I just fixed it in the PR title. Ok if you check in as-is, or I can re-stamp after amending.

**Comment by markusicu** [comment]
Why would the gcc-debug-build-and-test be getting killed after a little more than 4 minutes?

**Comment by markusicu** [comment]
tests pass now, and @richgillam wrote in a ticket comment “your PR looked fine to me”

**Review by richgillam — APPROVED** [review]
Looks fine to me.  Thanks for making the change!

**Pull request merged**
