### PR TITLE
ICU-13837 c build: make --disable-layoutex the default

### PR DESCRIPTION
**Pull request by srl295**
ICU-13837

- also update configure.ac that was missed in #1265 cad3903cc25c0db7f392adbc024829aea6591a50 ICU-21051
- also, some FALSE/TRUE were missed in source/test/letest

-----
Notes:
- see https://github.com/harfbuzz/icu-le-hb/issues/13 about building icu-le-hb
-  I did not fix some FALSE/TRUE that may be in source/samples/layout as I do not have a way to test it currently.

### CODE REVIEW

**Comment by srl295** [comment]
- [x] removed layoutex mention in the github action workflow

**Comment by srl295** [comment]
@markusicu can you make sure this gets noted when  69.1 is released?

**Comment by jefgen** [comment]
> * [x]  removed layoutex mention in the github action workflow

Thanks @srl295!

I think it could probably also be removed from the CI builds too:
https://github.com/unicode-org/icu/blob/master/.ci-builds/.azure-pipelines.yml#L93
https://github.com/unicode-org/icu/blob/master/.ci-builds/.azure-valgrind.yml#L50

I can open another PR with the same ticket number, or perhaps maybe you might not mind doing it here too? :)

**Comment by srl295** [comment]
> > * [x]   removed layoutex mention in the github action workflow
> 
> Thanks @srl295!
> 
> I think it could probably also be removed from the CI builds too:
> https://github.com/unicode-org/icu/blob/master/.ci-builds/.azure-pipelines.yml#L93
> https://github.com/unicode-org/icu/blob/master/.ci-builds/.azure-valgrind.yml#L50
> 
> I can open another PR with the same ticket number, or perhaps maybe you might not mind doing it here too? :)

done

**Comment by markusicu** [comment]
> @markusicu can you make sure this gets noted when 69.1 is released?

Done: http://site.icu-project.org/download/69#TOC-ICU4C-Specific-Changes

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Review by jefgen — APPROVED** [review]
lgtm, thanks @srl295 !

**Pull request merged**
