### PR TITLE
ICU-21959 Update stale Jira tickets in ICU4J TODOs

### PR DESCRIPTION
**Pull request by hugovdm**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21959
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable **(not applicable)**
- [X] API docs and/or User Guide docs changed or added, if applicable **(not applicable)**

### CODE REVIEW

**Review by sffc — APPROVED** [review]

**Review by sffc — CHANGES_REQUESTED** [review]
Actually, there should no longer be commits against ICU-21862 on the main branch. I'll see if there's an ICU 72 cleanup bug.

**Comment by hugovdm** [comment]
Understood. And making this part of ICU-21988 does not make sense: for that, I should just go ahead and finish my PR that fixes it. :)

**Comment by sffc** [comment]
Please re-target this against ICU-21959

I think this is a good change to make even if you have the main PR in progress

**Comment by hugovdm** [comment]
Done (entirely rephrased the pull request title and commit message)

**Review by sffc — APPROVED** [review]

**Pull request merged**
