### PR TITLE
ICU-20980 BRS66GA Update version numbers and README files

### PR DESCRIPTION
**Pull request by daniel-ju**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20980
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [x] Documentation is changed or added

### CODE REVIEW

**Comment by jefgen** [comment]
The changes/updates to the *.jar files for the version number (in this PR) will conflict with the CLDR data updates that are in PR #1007.
I think it might be better to wait for CLDR updates to be merged first, and then we can do the version update afterwards and rebuild the jar files.

**Comment by daniel-ju** [comment]
> The changes/updates to the *.jar files for the version number (in this PR) will conflict with the CLDR data updates that are in PR #1007.
> I think it might be better to wait for CLDR updates to be merged first, and then we can do the version update afterwards and rebuild the jar files.

The CLDR integration is going into the master branch for ICU 67, while the version updates are going into the maint-66 branch. There shouldn't be any merge conflict issues from that, or am I mistaken?

**Comment by jefgen** [comment]
> The CLDR integration is going into the master branch for ICU 67, while the version updates are going into the maint-66 branch. There shouldn't be any merge conflict issues from that, or am I mistaken?

You're absolutely correct! My mistake.
(I think I was confused by the two releases happening so close to one another, and being up too late...)

**Pull request merged**
