### PR TITLE
ICU-20871 Fixed: no rule was defined to create the $(OUTDIR) directory if it di…

### PR DESCRIPTION
**Pull request by smaarn**
…dn't exist.

This would cause failures during cross compilation cases such as:

make[6]: Leaving directory '/spksrc/spk/bazarr/work-qoriq-6.1/icu/source/data'
make[5]: *** No rule to make target 'out', needed by 'out/icudt64b.dat'.  Stop.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20871
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] ~~Tests included~~
- [x] ~~Documentation is changed or added~~

### CODE REVIEW

**Comment by sffc** [comment]
@smaarn Can you rewrite your commit message?  See here for details:

https://us-central1-festive-cistern-138116.cloudfunctions.net/icu-jira-github-pr-check-test/info/unicode-org/icu/887

There is a button "Squash branch" to help you put the message in the correct format.

**Comment by antoine-malliarakis** [comment]
> @smaarn Can you rewrite your commit message? See here for details:
> 
> https://us-central1-festive-cistern-138116.cloudfunctions.net/icu-jira-github-pr-check-test/info/unicode-org/icu/887
> 
> There is a button "Squash branch" to help you put the message in the correct format.

Just rephrased the commit (if I understood correctly it was a matter of prefixing the commit header with the Jira identifier, correct ?).

**Comment by smaarn** [comment]
@sffc the commit has been rewritten. I don't have the rights, though, to rebase nor merge this PR.

**Comment by sffc** [comment]
Thanks for the contribution!

**Pull request merged**
