### PR TITLE
ICU-22462 move ExhaustivePersonNameFormatterTest to PersonNameConsistencyTest

### PR DESCRIPTION
**Pull request by FrankYFTang**
Rename ExhaustivePersonNameFormatterTest to PersonNameConsistencyTest
Always run. Paramaterize the test to use 
junitparams.JUnitParamsRunner frame work so we can see the errors 
from indivisual file clearly. 

For the document of @Parameters(method = xxx)
See https://www.baeldung.com/junit-params#2-parameter-method for details

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22462
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by richgillam — COMMENTED** [review]
Peter and Dragan are in there making changes now.  Is this truly necessary, and can it wait until they're done?

I'm also not crazy about your making extensive changes to this test without talking to me first.  Maybe the changes are okay, but I don't understand the motivation or what you're doing to address it.  What does `JUnitParamsRunner` do, and why do you need it here?  Is it replacing all the stats logging that you took out, and if not, why did you take all that stuff out?

**Comment by FrankYFTang** [comment]
> Peter and Dragan are in there making changes now. Is this truly necessary, and can it wait until they're done?

Sure. We can wait


I filed https://unicode-org.atlassian.net/browse/ICU-22462 last week and I have talked to you about the issue related to ExhaustivePersonNameFormatterTest several times last severl weeks, right?

I remember we talk about for all your PR related to ExhaustivePersonNameFormatterTest it is better to put  "/azp run CI-Exhaustive" in the PR comments to trigger the post-merge Exhaustive test before merging it. And apparently you didn't do so on https://github.com/unicode-org/icu/pull/2544
and this post-merged test failure has been in the trunk the last two weeks. These failures are keep showing up on post-merged CI - See all the red X on https://github.com/unicode-org/icu/commits/main and we cannot be sure any PR we landed after that passed all the post-merge tests. 

which the first one show up after your post-merged breakage https://github.com/unicode-org/icu/commit/ca3fd47f4cd6102e91b7d88607dcea0be7648d87#diff-6c4a4e38ddc9a10d5fc48efe13e011e4fb13fa9b3a9d5ea4b3db4e5362dcd28d

see the red x on the upper left which point you to 
https://github.com/unicode-org/icu/runs/15803540080
and showing
https://dev.azure.com/ms/icu/_build/results?buildId=486821&view=results
and
line 1100-1101 in
https://dev.azure.com/ms/icu/_build/results?buildId=486821&view=logs&j=c739c0b6-c3cc-5424-70de-339140243943&t=498131dd-877e-5e7d-0e35-960d74a08952&l=1101
```
    [junit] Running com.ibm.icu.dev.test.format.ExhaustivePersonNameFormatterTest
    [junit] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.726 sec
```

The test show the following errors now 
https://dev.azure.com/ms/icu/_build/results?buildId=486821&view=logs&j=c739c0b6-c3cc-5424-70de-339140243943&t=e60e287e-8cda-58ef-b989-64d8c3764fc7&l=104
and
https://dev.azure.com/ms/icu/_build/results?buildId=486821&view=logs&j=c739c0b6-c3cc-5424-70de-339140243943&t=e60e287e-8cda-58ef-b989-64d8c3764fc7&l=151


I filed the bug https://unicode-org.atlassian.net/browse/ICU-22462 and put you on the watch list last Thursday (2023-08-17 11:30AM) I understand you and Peter must be very busy on the CLDR merge issue so I try to see how can I help to improve this.


>  I don't understand the motivation or what you're doing to address it. What does JUnitParamsRunner do, and why do you need it here?

The way you currently write the test is  using @RunWith(JUnit4.class). It happen when I write my test in https://github.com/unicode-org/icu/commit/ffc449de6243b17857b5d67854bdec723bf06f21#diff-cce2d75f5ae93465a6124bfaf0d1034cc17f816d52a45a61d265fe3455cb6aa5R62


Markus and Mihai teach me to use JUnitParamsRunner . The problem with @RunWith(JUnit4.class) is that if we assert on one error the test case will stop and not continue. But by restructure to use JUnitParamsRunner, the cases are broken down and feed into the test function multiple time, each time with a case and the reporting will only stop while the error happen for that particular case. 

The other issue is currently the Exhaustive test a very long time to run, and by converting to JUnitParamsRunner, I think we can parallized the testint by multiple thread/core after adding
  @TestParallel

See https://onloadcode.com/mastering-junitparams-advanced-techniques-parameterized-testing-java/#Parallel_test_execution

We see a lot of timeout on running the post-merge Exhaustive now because it take too long to run. By converting to JUnitParamsRunner and adding @TestParallel (I have not try that yet) we probably can speed up that.

**Comment by FrankYFTang** [comment]
The output in the xml is now change to something like
```
      <testcase classname="com.ibm.icu.dev.test.format.ExhaustivePersonNameFormatterTest" name="TestPersonNames" time="1.004" />

      <system-out><![CDATA[af.txt had 0 errors
am.txt had 0 errors
ar.txt had 0 errors
as.txt had 0 errors
br.txt had 0 errors
brx.txt had 0 errors
ca.txt had 0 errors
cs.txt had 0 errors
cy.txt had 0 errors
da.txt had 0 errors

...
```

**Comment by FrankYFTang** [comment]
The test output after this PR will be changed to something like
```
     <testcase classname="com.ibm.icu.dev.test.format.ExhaustivePersonNameFormatterTest" name="[0] af.txt (TestPersonNames)" time="0.157" />

      <testcase classname="com.ibm.icu.dev.test.format.ExhaustivePersonNameFormatterTest" name="[1] am.txt (TestPersonNames)" time="0.03" />

      <testcase classname="com.ibm.icu.dev.test.format.ExhaustivePersonNameFormatterTest" name="[2] ar.txt (TestPersonNames)" time="0.019" />

      <testcase classname="com.ibm.icu.dev.test.format.ExhaustivePersonNameFormatterTest" name="[3] as.txt (TestPersonNames)" time="0.015" />

```
so the error in each file will be report separately. 
and regardless we ignore the error, we will see the running
```
 <system-out><![CDATA[af.txt had 0 errors
am.txt had 0 errors
ar.txt had 0 errors
as.txt had 0 errors
    Expected 'Müller', got 'Müller Käthe' at line 335
    Expected 'Müller', got 'Müller Käthe' at line 336
    Expected 'Käthe', got 'Müller Käthe' at line 340
    Expected 'Ştöber Zazilia H.', got 'Ştöber Zazilia Hamiş' at line 369
    Expected 'Ştöber Zazilia', got 'Ştöber Zazilia Hamiş' at line 373
    Expected 'Ştöber Zazilia', got 'Ştöber Zazilia Hamiş' at line 374
...
    Expected 'Neele', got 'van den Volf Ada Kornelia Sezar Martin M.D. Ph.D.' at line 435
az.txt had 15 errors
Test failure on az.txt: ERROR: Testing against 'az.txt' contains 15 errors.
    Expected 'ВКР', got 'ВР' at line 204
    Expected 'МАК', got 'МК' at line 269
be.txt had 2 errors
...
Test throw exception on gd.txt: java.lang.IllegalArgumentException: Invalid modifier name vocative Invalid modifier name vocative
...
Test failure on zu.txt: ERROR: Testing against 'zu.txt' contains 44 errors.

 1 Known Issues:
ICU-17028 <https://unicode-org.atlassian.net/browse/ICU-17028>
  -  (ERROR: Testing against 'az.txt' contains 15 errors.)
  ... and 38 more
]]></system-out>

```

**Review by richgillam — APPROVED** [review]
I understand that Peter and Dragan landed their change that should have fixed the failures in this test.  Have you rebased on top of their changes?  If so, I think you're good to go.

I've always hated that the JUnit tests stop at the first error, so if this fixes that, I'm all for it.  I'm a little less crazy about breaking things out so that every input file is a separate "test case," but that's probably just my own personal aesthetics, so I guess I'll go along with it.  I'm not that concerned about running these tests in parallel, because as I remember it, they were pretty fast-- the whole set ran in well under a second on my machine, as I remember it.  But if they're running slower for you, I can see how the ability to run them in parallel would be an advantage.

As for the larger issue, the way I remember things, I _did_ run the exhaustive tests the last time I worked on PersonNameFormatter, and everything passed.  I believe the tests started failing later, while Peter and Dragan were working on the CLDR integration.  But maybe I'm wrong about that.

I've come to really hate this test and to regret adding it to the standard unit test suite, and a lot of that has to do with the fact that the CLDR data has been in flux and there's been no good way to keep up with the changes happening on the CLDR side.  I know Mark, Peter, and Dragan are implementing process improvements on the CLDR side to help with this in the future, and I really hope it all helps, and that the CLDR (and the design of PersonNameFormatter) settle down after 44/74.

They're going to send me a ticket to bring things back into sync and reenable all the failing test cases after things settle down on the CLDR side, hopefully in the next week or so.  I really hope that's the last of it.

**Comment by FrankYFTang** [comment]
Yes, I did sync after peter merged https://github.com/unicode-org/icu/pull/2559 .

My origional intend for this PR is to fix the broken test on the trunk. But that was fix by https://github.com/unicode-org/icu/pull/2559 20 hours ago already. 

The breaking test case would help you to quickly find out which file has the problem. Ideally, the error should not be outputted by System.out.println but should by assertXXX that this unit test currently not follow. But for most part I didn't change that. 

The ticket is not accepted yet. Since the broken test is now fix, maybe I should open a different ticket to land this test instead.

> as I remember it, they were pretty fast
Then why we put them as an Exhaustive test instead of always run them?

**Comment by richgillam** [comment]
> Yes, I did sync after peter merged #2559 .

Good.  Thank you.

> My origional intend for this PR is to fix the broken test on the trunk. But that was fix by #2559 20 hours ago already.
> 
> The ticket is not accepted yet. Since the broken test is now fix, maybe I should open a different ticket to land this test instead.

Or change the existing ticket to cover what you're doing now.  As I said, I'm willing to have the changes go in; I do think they're improvements.  I'll support accepting the ticket, whether it's a new one or a reworded version of the ticket you already filed.

> The breaking test case would help you to quickly find out which file has the problem. Ideally, the error should not be outputted by System.out.println but should by assertXXX that this unit test currently not follow. But for most part I didn't change that.

If you want to do that too, that's fine with me.  Or I can take another look at that the next time I go in there.

> > as I remember it, they were pretty fast
> 
> Then why we put them as an Exhaustive test instead of always run them?

Two reasons: 1) At the time, I didn't know just how fast the test was.  And 2) as you know, this test started out as just another thing I was checking in and not part of the test suite at all, and I did it that way because I didn't know how to guarantee that the data files it depends on were in the right place (they were only over in the CLDR tree when I first wrote that test).  I think I was trying to keep this test from being run all the time when I didn't know how stable it was going to be or how we were going to manage that dependency (and I think I was right about that, given how things have gone over the last month!).

**Comment by FrankYFTang** [comment]
@richgillam @pedberg-icu @mihnita PTAL and approve.

**Review by richgillam — APPROVED** [review]
LGTM

**Pull request merged**
