### PR TITLE
ICU-21361 Publish additional public key

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21361
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by jefgen** [comment]
Thanks for creating this PR!

Hmm... it looks like this PR has ~30 commits or so...
I wonder if maybe the git branch you started with was out-of-sync, or if perhaps it was messed up somehow?
(Maybe you started with `maint/maint-68`?)

FWIW, I think you'd only want to have this one commit in the PR:
https://github.com/unicode-org/icu/pull/1447/commits/296d85ebfa677d29d80996914fd0e2afcc5e200b

**Review by jefgen — CHANGES_REQUESTED** [review]
Please fix the extra commits. :)

**Comment by sven-oly** [comment]
Updated this PR to have only one file and one commit.

**Review by jefgen — APPROVED** [review]
lgtm, thanks!

**Pull request merged**
