### PR TITLE
ICU-10291 Optimize IDNA toASCII loop

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-10291
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [X] Tests included
- [X] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
Does this need to be fixed in Java as well?

Can you make your commit message a little bit more descriptive?  "Optimize the loop" is not very useful when scrolling through the commit log to see what changed.  What loop are you talking about?  Something like "Optimize IDNA2003 toASCII loop" would be more helpful.

**Comment by FrankYFTang** [comment]
> Does this need to be fixed in Java as well?

this bug is a just a code critique to the C++ code. There are no real "bug" so therefore there are no need of "fix" for Java.

> 
> Can you make your commit message a little bit more descriptive? "Optimize the loop" is not very useful when scrolling through the commit log to see what changed. What loop are you talking about? Something like "Optimize IDNA toASCII loop" would be more helpful.

**Comment by sffc** [comment]
What I mean is, it looks like the same code exists in Java (IDNA2003.java), and changing it in C++ brings the two out of sync, which we don't want:

```java
    private static boolean startsWithPrefix(StringBuffer src){
        boolean startsWithPrefix = true;

        if(src.length() < ACE_PREFIX.length){
            return false;
        }
        for(int i=0; i<ACE_PREFIX.length;i++){
            if(toASCIILower(src.charAt(i)) != ACE_PREFIX[i]){
                startsWithPrefix = false;
            }
        }
        return startsWithPrefix;
    }
```

**Comment by sffc** [comment]
> How could I change commit message once committed?

`git commit --amend` followed by `git push -f`

**Comment by FrankYFTang** [comment]
PTAL

**Pull request merged**
