### PR TITLE
ICU-20693 Cherry-pick CLDR converter tool commits from master to maint/maint-65

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20693
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
@markusicu @srl295 @jefgen 

These commits are intended for ICU 66.1.  Should we create a new branch?

**Comment by srl295** [comment]
> These commits are intended for ICU 66.1. Should we create a new branch?

If they are for 66.1, please change the PR title and mark as not ready.

2019-09-25 TC agenda says:
> After 65 release & tag – wait a few days in case we need to re-tag 65 – create maint/maint-66 from tag for 65

Can you add an agenda item to a future TC agenda (for the record) and start a thread on icu-core? I don't think we can resolve this here on the PR

**Comment by markusicu** [comment]
As agreed before, I think we want to create maint/maint-66 sometime next week.

I think it makes sense to then cherry-pick these commits to there.

**Comment by sffc** [comment]
I added an agenda item.  We should be able to use the same PR and just retarget it to the new branch.

**Comment by sffc** [comment]
Good news!  This PR is obsolete, because of the consensus at ICU-TC this morning to create the 66 branch directly from master.  (See the meeting notes; there are no substantial commits right now on master other than these commits for the CLDR converter tool.)

**Pull request closed without merging**
