### PR TITLE
ICU-12811 Refactor test-framework to not depend on core

### PR DESCRIPTION
**Pull request by mihnita**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-12811
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [X] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by echeran — APPROVED** [review]
LGTM. Thanks!

**Comment by mihnita** [comment]
Thank you!
M.

**Comment by pedberg-icu** [comment]
@mihnita @macchiati @srl295 This broke all sorts of CLDR code that depended on UnicodeMap and ElapsedTimer being in the ICU4J libs used by CLDR. Trying to figure out what to do about that. We may need to have copies of UnicodeMap and the old ElapsedTimer  in CLDR sources.

**Comment by srl295** [comment]
Yes, this should not have been done w/o checking CLDR code. 

Could we meet and talk about https://unicode-org.atlassian.net/browse/ICU-21757 ?

**Comment by srl295** [comment]
@mihnita @echeran or, just revert the deletion of ElapsedTimer and UnicodeMap for now?

**Comment by pedberg-icu** [comment]
https://github.com/unicode-org/cldr/pull/2780 is the CLDR PR that should have updated the ICU4J libs to latest but cannot because of this problem.

**Comment by srl295** [comment]
opened a revert in #2364

**Comment by mihnita** [comment]
Approved it.
But it does not seem to build.

**Pull request merged**
