### PR TITLE
ICU-21405 Update ICU4J Readme for BRS 68.2

### PR DESCRIPTION
**Pull request by echeran**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21405
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [ ] Tests included
- [X] Documentation is changed or added

@erik0686 has already covered the ICU4C Readme version update (thanks!) in https://github.com/unicode-org/icu/pull/1495/files#r534507835, so this PR is just for the remaining ICU4J Readme version update.

### CODE REVIEW

**Review by erik0686 — DISMISSED** [review]

**Review by daniel-ju — DISMISSED** [review]

**Review by jefgen — DISMISSED** [review]
Thanks Elango!

**Review by markusicu — DISMISSED** [review]
lgtm

**Comment by echeran** [comment]
Aside from the license/CLA check, all the checks passed (even Travis!). Since the license/CLA check is stuck in an "Expected" state, it hasn't run yet, so there is no link available to manually re-run it. In order to re-trigger the PR checks in hopes that it will run again, I'm amending the commit message and doing a force push to the PR, but leaving the contents of the PR commit the same.

**Review by markusicu — APPROVED** [review]
lgtm

If necessary, unicode-org admins (like me) can re-trigger CLA checks. Please ask before force-pushing.

**Pull request merged**
