### PR TITLE
ICU-20842 Fix library names in pkg-config files  on Windows (mingw-w64)

### PR DESCRIPTION
**Pull request by vtorri**
since the move of the DLL to bin/ the library names in .pc files is
wrong. With ICU 65.1, icu-uc.pc contains

Libs: -L${libdir} -licuuc65 -licudt65

the version number should not appear. Indeed, the linker looks for the
libraries in $prefix/lib in the following order (see [1]):

libxxx.dll.a
xxx.dll.a
libxxx.a
cygxxx.dll
libxxx.dll
xxx.dll

As there is only the import library with no versioning (which is normal),
there is a link error when using ICU pc files.

[1] https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Using_ld_the_GNU_Linker/win32.html

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20842
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by jefgen** [comment]
Thank you for the PR!

Would you mind posting (in a comment) what the diff in the .pc file looks like? (For others to see as well). Thank you!

**Comment by vtorri** [comment]
here are the diffs (in different comments) :

```
$ diff -Naur config/icu-i18n.pc ~/gitroot_64/icu_vtorri2/icu4c/source/config/icu-i18n.pc
--- config/icu-i18n.pc  2020-02-13 05:54:44.647074400 +0100
+++ /home/vincent.torri/gitroot_64/icu_vtorri2/icu4c/source/config/icu-i18n.pc  2020-02-13 13:10:32.391094100 +0100
@@ -8,7 +8,7 @@
 CXXFLAGS =  -std=c++11
 # DEFS only contains those UCONFIG_CPPFLAGS which are not auto-set by platform.h
 DEFS =
-prefix = /opt/icu
+prefix = /opt/icu_32
 exec_prefix = ${prefix}
 #bindir = ${exec_prefix}/bin
 libdir = ${exec_prefix}/lib
@@ -37,4 +37,4 @@
 Description: International Components for Unicode: Internationalization library
 Name: icu-i18n
 Requires: icu-uc
-Libs: -licuin66
+Libs: -licuin
```

**Comment by vtorri** [comment]
```
$ diff -Naur config/icu-io.pc ~/gitroot_64/icu_vtorri2/icu4c/source/config/icu-io.pc
--- config/icu-io.pc    2020-02-13 05:54:44.665581200 +0100
+++ /home/vincent.torri/gitroot_64/icu_vtorri2/icu4c/source/config/icu-io.pc    2020-02-13 13:10:32.406715000 +0100
@@ -8,7 +8,7 @@
 CXXFLAGS =  -std=c++11
 # DEFS only contains those UCONFIG_CPPFLAGS which are not auto-set by platform.h
 DEFS =
-prefix = /opt/icu
+prefix = /opt/icu_32
 exec_prefix = ${prefix}
 #bindir = ${exec_prefix}/bin
 libdir = ${exec_prefix}/lib
@@ -37,4 +37,4 @@
 Description: International Components for Unicode: Stream and I/O Library
 Name: icu-io
 Requires: icu-i18n
-Libs: -licuio66
+Libs: -licuio
```

**Comment by vtorri** [comment]
```
$ diff -Naur config/icu-uc.pc ~/gitroot_64/icu_vtorri2/icu4c/source/config/icu-uc.pc
--- config/icu-uc.pc    2020-02-13 05:54:44.711388300 +0100
+++ /home/vincent.torri/gitroot_64/icu_vtorri2/icu4c/source/config/icu-uc.pc    2020-02-13 13:10:32.359852500 +0100
@@ -8,7 +8,7 @@
 CXXFLAGS =  -std=c++11
 # DEFS only contains those UCONFIG_CPPFLAGS which are not auto-set by platform.h
 DEFS =
-prefix = /opt/icu
+prefix = /opt/icu_32
 exec_prefix = ${prefix}
 #bindir = ${exec_prefix}/bin
 libdir = ${exec_prefix}/lib
@@ -36,5 +36,5 @@
 # end of icu.pc.in
 Description: International Components for Unicode: Common and Data libraries
 Name: icu-uc
-Libs: -L${libdir} -licuuc66 -licudt66
+Libs: -L${libdir} -licuuc -licudt
 Libs.private: ${baselibs}
```

**Comment by vtorri** [comment]
Note that I have tested when compiling for 32 bits and 64 bits

**Comment by jefgen** [comment]
Thank you for posting the diffs! :)

**Comment by vtorri** [comment]
thank you

**Pull request merged**
