### PR TITLE
ICU-22002 Fix for C++20 - don't undef __STRICT_ANSI__

### PR DESCRIPTION
**Pull request by paulharris**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22002
- [x] Required: The PR title must be prefixed with a JIRA Issue number.
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number.
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by yumaoka** [comment]
CI build is failing with this change on Cygwin GCC/MSYS2  GCC. @paulharris Can you take a look at the build problems first?

**Comment by jefgen** [comment]
Both the Cygwin build and the MSYS2 build are failing with the following error:

```
ufile.cpp:29:14: error: 'FILE' was not declared in this scope
   29 | int _fileno( FILE * );
      |              ^~~~
ufile.cpp:24:1: note: 'FILE' is defined in header '<cstdio>'; did you forget to '#include <cstdio>'?
```

**Comment by paulharris** [comment]
Yep thanks guys, I should've changed it to a Draft PR.
Fiddling with different ways of fixing it for cygwin/msys.

**Comment by paulharris** [comment]
I see these warnings compiling in GCC (cygwin's pipeline, in this case):
```
g++ -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_STRTOD_L=1 -DU_HAVE_XLOCALE_H=0  -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -I. -I../common   -DU_ATTRIBUTE_DEPRECATED= -DU_I18N_IMPLEMENTATION -O3  -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long -std=c++11    -c -DPIC  -o calendar.o calendar.cpp
In file included from calendar.cpp:56:
In member function ‘icu_72::Calendar& icu_72::Calendar::operator=(const icu_72::Calendar&)’,
    inlined from ‘icu_72::Calendar& icu_72::Calendar::operator=(const icu_72::Calendar&)’ at calendar.cpp:817:1,
    inlined from ‘icu_72::Calendar::Calendar(const icu_72::Calendar&)’ at calendar.cpp:811:13:
../common/cstring.h:43:70: warning: ‘char* strncpy(char*, const char*, size_t)’ output may be truncated copying 156 bytes from a string of length 156 [-Wstringop-truncation]
   43 | #define uprv_strncpy(dst, src, size) U_STANDARD_CPP_NAMESPACE strncpy(dst, src, size)
calendar.cpp:844:9: note: in expansion of macro ‘uprv_strncpy’
  844 |         uprv_strncpy(actualLocale, right.actualLocale, sizeof(actualLocale));
      |         ^~~~~~~~~~~~
```

The code appears to be:
```
        uprv_strncpy(validLocale, right.validLocale, sizeof(validLocale));
        uprv_strncpy(actualLocale, right.actualLocale, sizeof(actualLocale));
        validLocale[sizeof(validLocale)-1] = 0;
        actualLocale[sizeof(validLocale)-1] = 0;
```

Why not do something like:
```
        uprv_strncpy(actualLocale, right.actualLocale, sizeof(actualLocale)-1);
```
Then you don't need to set the null char at the end, and you won't get the strncpy warnings?

**Comment by paulharris** [comment]
This is looking good.  But why does the cygwin pipeline 4+ hours to run tests?

**Comment by paulharris** [comment]
> Notice: the branch changed across the force-push!
> 
>     * icu4c/source/io/ufile.cpp is different
> 
> 
> [View Diff Across Force-Push](https://github.com/unicode-org/icu/compare/unicode-org:1a52cb6..unicode-org:212ad8e)
> 
> ~ Your Friendly Jira-GitHub PR Checker Bot

Was just a whitespace fix.

**Comment by jefgen** [comment]
> Why not do something like:
>
>        uprv_strncpy(actualLocale, right.actualLocale, sizeof(actualLocale)-1);
> Then you don't need to set the null char at the end, and you won't get the strncpy warnings?

Thanks for taking a look at the warnings!
FWIW, there's been a few "strncpy" related tickets/issues filed in the past, but I don't think anyone has had time to work on them.
For example:
https://unicode-org.atlassian.net/browse/ICU-21260
https://unicode-org.atlassian.net/browse/ICU-20983

If you have time, and want to make another pull-request, that would be helpful. :)

**Comment by paulharris** [comment]
> If you have time, and want to make another pull-request, that would be helpful. :)

I wish I had the time, sorry.  I did leave my thoughts on ICU-20983, that has an interesting discussion.

**Pull request merged**
