### PR TITLE
ICU-20027: Support parallel builds with MSYS/MSVC and Cygwin/MSVC

### PR DESCRIPTION
**Pull request by madscientist**
##### Checklist

- [x] Issue filed at https://unicode-org.atlassian.net :  ICU-20027
- [x] Update PR title to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

No tests or docs needed for this change (I searched for docs related to MSVC debug compilation but didn't find any)

### CODE REVIEW

**Comment by jefgen** [comment]
@madscientist Thanks for the pull-request! Please take a moment to review and sign the CLA. Thanks!

**Comment by madscientist** [comment]
I did sign it, yesterday.  And again just now.  When I do it it says "thanks for signing" but the status here is never updated... :(

**Comment by jefgen** [comment]
Okay, it looks like you have indeed signed the CLA (as the user "madscientist").

However, it looks like the actual commit author 'nuodb-mirror' instead. So I think the CLA needs to be signed as that user, or the commit would need to be modified to change the author.

**Comment by madscientist** [comment]
What?  Ugh.  OK I'll redo the commit.  I don't know how my Git config got messed up there.

**Pull request closed without merging**
