### PR TITLE
ICU-21900 integrate CLDR release-41-alpha0 to ICU main for 71 front-load

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21900
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

This PR integrates CLDR release-41-alpha0 (a pre-alpha pass), which includes data from the CLDR 41 survey tool phase, into ICU main branch as part of the ICU 71 front-loading work. There are a couple of things to call out:
1. CLDR 41 has several new transforms for Ethiopic. There were some naming issues with these, which were fixed in CLDR PRs for the integration: [PR-1739](https://github.com/unicode-org/cldr/pull/1739), [PR-1740](https://github.com/unicode-org/cldr/pull/1740). There is still a problem creating inverse forms for these which caused an ICU test failure, currently skipped with a logKnownIssue: CLDR-15337 (https://unicode-org.atlassian.net/browse/CLDR-15337).
2. The PRs for Japanese linebreak changes (for ICU-21699), [PR-1936](https://github.com/unicode-org/icu/pull/1936) and [PR-1959](https://github.com/unicode-org/icu/pull/1959), directly edited the file `icu4c/source/data/brkitr/ja.txt`. That file is supposed to be generated, partly from `icu4c/source/data/xml/brkitr/ja.xml` (for mapping to the rule files), and partly from data that should be in CLDR (in this case, the particles and auxVerbs bundles). For this integration I did update `icu4c/source/data/xml/brkitr/ja.xml` to generate the rule file mappings, but I just recopied the `particles` and `auxVerbs` data manually (and updated the cldr-icu-readme accordingly). I filed a ticket to have those generated from new CLDR data: For CLDR, [CLDR-15340](https://unicode-org.atlassian.net/browse/CLDR-15340). And now it looks like that data is changing anyway: [PR-1964](https://github.com/unicode-org/icu/pull/1964).

### CODE REVIEW

**Review by macchiati — APPROVED** [review]
From a spot check, looks good.

**Comment by pedberg-icu** [comment]
Updated tests to fix exhaustive failure...

**Review by markusicu — APPROVED** [review]
mostly rslgtm

**Review by macchiati — APPROVED** [review]

**Pull request merged**
