### PR TITLE
ICU-22196 TZ Database 2022f updates

### PR DESCRIPTION
**Pull request by yumaoka**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22196
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by pedberg-icu — APPROVED** [review]
Looks good, thanks!

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Review by srl295 — APPROVED** [review]
Changes LGTM, i assume based on cldr main? will this be cherry picked into maint?

**Comment by yumaoka** [comment]
> Changes LGTM, i assume based on cldr main? will this be cherry picked into maint?

metaZones.txt is generated from the version in the CLDR PR https://github.com/unicode-org/cldr/pull/2505 - this is merged into CLDR main branch.

On ICU side, we don't really merge tz updates to maintenance branches regularly. For official maintenance releases, we try to refresh tz data to the latest at that point although.

**Pull request merged**
