### PR TITLE
ICU-20884 initialized buffer uloc_getKeywordValue

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20884
- [X] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [X] Tests included
- [X] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
LGTM

Wait for reply from ICU-TC with regard to the 66 maintenance branch before merging.

**Comment by FrankYFTang** [comment]
ping

**Comment by sffc** [comment]
The right place to ping is on the thread on icu-core.

**Comment by FrankYFTang** [comment]
I am very confused how the PR get all other files in here. Need some help to remove them.

**Comment by jefgen** [comment]
> how the PR get all other files in here.

I think this is likely because the commit was originally made using a branch off of `master`, but then the target for the PR was changed to `maint/maint-66` afterwards.

One way to fix this would be to rebase the changes in your branch `ICU-20884` onto the `maint/maint-66` branch, and then force push.

**Comment by sffc** [comment]
Yeah, I think at first the diff was the same on master and maint/maint-66, but the longer we wait the more likely they are to diverge.  The easiest thing would be to rebase your commit against the head of maint/maint-66.

**Pull request merged**
