### PR TITLE
ICU-21344 Fix wrong passing of script in Locale.

### PR DESCRIPTION
**Pull request by FrankYFTang**
Also add same unit test in Java which have no problem.

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21344
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [X] Tests included
- [X] Documentation is changed or added

### CODE REVIEW

**Review by markusicu — DISMISSED** [review]
lgtm tnx

**Review by markusicu — APPROVED** [review]
lgtm tnx 2

**Comment by sffc** [comment]
This PR caused a depstest error on the maintenance branch:

```
Error: in group resourcebundle: common/locid.o imports icu_68::LocaleBuilder::build(UErrorCode&) but resourcebundle does not depend on localebuilder (for common/localebuilder.o)Error: in group resourcebundle: common/locid.o imports icu_68::LocaleBuilder::setLanguage(icu_68::StringPiece) but resourcebundle does not depend on localebuilder (for common/localebuilder.o)Error: in group resourcebundle: common/locid.o imports icu_68::LocaleBuilder::~LocaleBuilder() but resourcebundle does not depend on localebuilder (for common/localebuilder.o)Error: in group resourcebundle: common/locid.o imports icu_68::LocaleBuilder::setScript(icu_68::StringPiece) but resourcebundle does not depend on localebuilder (for common/localebuilder.o)Error: in group resourcebundle: common/locid.o imports icu_68::LocaleBuilder::LocaleBuilder() but resourcebundle does not depend on localebuilder (for common/localebuilder.o)Error: There were errors, please fix them and re-run. Processing may have terminated abnormally.The command "( cd ../icu4c/source/test/depstest && ./depstest.py ../../../../build/ )" exited with 1.
```

**Comment by sffc** [comment]
Note: I see that the test was indeed failing in presubmit on this PR.  This PR shouldn't have been merged with a failing test.

**Comment by markusicu** [comment]
> This PR caused a depstest error on the maintenance branch:

Yes. So either this code needs to build a valid locale ID with a script subtag (rather than using the LocaleBuilder), or the builder needs to be moved into the resourcebundle group. @FrankYFTang

**Comment by FrankYFTang** [comment]
sorry, what is the proper way to rollback https://github.com/unicode-org/icu/pull/1422 ?

**Comment by FrankYFTang** [comment]
sorry to cause this breakage - "the builder needs to be moved into the resourcebundle group." what does this mean? HOW?

**Comment by FrankYFTang** [comment]
I am not sure how to verify this on my local build. I tried but got strange result.  I blindly put https://github.com/unicode-org/icu/pull/1429 together and see would the trybot show me the result correctly or not.

**Comment by srl295** [comment]
> sorry, what is the proper way to rollback #1422 ?

a new PR

**Comment by srl295** [comment]
Cause: branch rules for *maint* branches did not require travis-ci to pass. Fixed. https://github.com/unicode-org/icu/settings/branch_protection_rules/2452846

**Pull request merged**
