### PR TITLE
ICU-21395 Fix UBSan breakage on 8bit of rbbi

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21395
- [X] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Review by gnrunge — APPROVED** [review]

**Review by sffc — APPROVED** [review]
I don't understand why accessing the data via the union field was undefined behavior

**Comment by jefgen** [comment]
> I don't understand why accessing the data via the union field was undefined behavior

I'm not sure either... maybe the compiler couldn't determine if it was the 8 or 16 bit table in the union that was being used?

**Comment by aheninger** [comment]
I don't understand why it fails either. The original code should be OK.

Maybe the UBSan tool just has one required alignment for types, so "union RBBIStateTableRow {...}" gets stuck with requiring an alignment of 16 bits. Then the access of "row->" gets flagged, without determining that only the eight bit side is actually used.

At any rate, the fix is harmless, and if it makes the failure go away, I'm ok with it.

**Review by markusicu — APPROVED** [review]
lgtm tnx

I agree, weird. Might be worth reporting back to the UBSan people. I assume we have a contact in Google.

**Comment by aheninger** [comment]
I think it may actually be undefined behavior. That a union must be aligned such that it could correctly store with any of its constituent members. So, in this case, having a pointer to the union type that will only work with the 8 bit types becomes problematic, even if the 16 bit types aren't actually used.

But I'm not certain, and haven't been able to find a clear reference with a little web searching.

**Comment by gnrunge** [comment]
Is this discussion still open? Or is feedback to more learned authorities
in order?

**Comment by aheninger** [comment]
I think this can be closed. The undefined behavior question is only of academic interest; the situation is removed from the code.

**Pull request merged**
