### PR TITLE
ICU-21632 Fix links in readme.html files to respective User Guide pages

### PR DESCRIPTION
**Pull request by echeran**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21632
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [X] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by jefgen** [comment]
Tested and they work great now. :)

http://htmlpreview.github.io/?https://raw.githubusercontent.com/unicode-org/icu/585dd772437c844c3bd6c0e82e7926b8162b7b6f/icu4c/readme.html

http://htmlpreview.github.io/?https://raw.githubusercontent.com/unicode-org/icu/585dd772437c844c3bd6c0e82e7926b8162b7b6f/icu4j/readme.html

Thanks @echeran :)

**Comment by erik0686** [comment]
@echeran @jefgen Just to make sure this is not only happening to me, could either of you check the readme file that github shows on Elango's branch https://github.com/echeran/icu/tree/readme-fix-links/icu4c and see if the link works there? To me, it seems it is including extra things in the links so I still get a 404

**Comment by erik0686** [comment]
image


I see it including an extra >ICU4C in the link. But maybe this is a github thing?

**Comment by jefgen** [comment]
> @echeran @jefgen Just to make sure this is not only happening to me, could either of you check the readme file that github shows on Elango's branch https://github.com/echeran/icu/tree/readme-fix-links/icu4c and see if the link works there? To me, it seems it is including extra things in the links so I still get a 404

AFAIK, GitHub doesn't render HTML pages properly, and only does Markdown. So the HTML pages as-is won't work on GitHub.

However, if you look at the preview of the HTML page in the comment above (link: https://github.com/unicode-org/icu/pull/1739#issuecomment-858020268 ) then it appears to be working fine. :)

**Comment by erik0686** [comment]
@jefgen Ahhh okay okay, that is good to know. The this looks good to me :) Thanks @echeran !!

**Review by erik0686 — APPROVED** [review]

**Comment by jefgen** [comment]
> image
> 
> I see it including an extra >ICU4C in the link. But maybe this is a github thing?

Maybe we can file a bug on GitHub? 🐛

**Pull request merged**
