### PR TITLE
ICU-22190 Update KEYS with additional public key

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22190
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by roubert** [comment]
I don't think it's a particularly good idea to add an unsigned public key to the ICU `KEYS` file.

**Review by markusicu — DISMISSED** [review]
rslgtm if it lgt @roubert

**Comment by sven-oly** [comment]
The latest version is now signed by Fredrik. Thanks!

**Review by roubert — DISMISSED** [review]
LGTM

**Comment by roubert** [comment]
OK, PR #2236 has now been merged, so you can now rebase this change on top of that.

**Comment by roubert** [comment]
I just moved the newly added key to the end of the file, as that would be more logical.

**Review by roubert — APPROVED** [review]
LGTM

**Review by roubert — APPROVED** [review]

**Pull request merged**
