### PR TITLE
ICU-20654 Add hour/minute for "this hour/minute"

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20654
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [x] Documentation is changed or added

### CODE REVIEW

**Comment by FrankYFTang** [comment]
> Please fix the broken tests.

DONE.

**Comment by sffc** [comment]
LGTM, please squash.

**Comment by FrankYFTang** [comment]
> LGTM, pending API approval. Thanks for fixing both C and J

API got approved by TC, could you approve this PR now? Thanks

**Comment by FrankYFTang** [comment]
> Sorry. I just noticed that you didn't add a test in C++ that uses the new constants. You did in Java. Can you add a test in C++ that directly uses `UDAT_ABSOLUTE_HOUR` and `UDAT_ABSOLUTE_MINUTE`, maybe inside of a big parameterized test like kEnglishNoQuantity?
> 
> Also, I notice that you added UDAT_ABSOLUTE_HOUR and _MINUTE but not _SECOND. Is that intentional?

ok, i will add test in C. There are no need to have _SECOND because there are no "this second", but only "now" and that is already implemented.

**Pull request merged**
