### PR TITLE
ICU-20593 Genrb: Remove keys if bundle is empty after filtering.

### PR DESCRIPTION
**Pull request by sffc**
This is a bug fix.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20593
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by jungshik** [comment]
Do you mean 'remove keys if bundle is empty after filtering'?

**Comment by sffc** [comment]
> Do you mean 'remove keys if bundle is empty after filtering'?

I think that's what my PR says, except for "even if". Unused keys are already being removed, but if *all* keys were marked as unused due to filtering, the code took a fast path that didn't actually remove the keys from the bundle.

**Comment by jungshik** [comment]
To me, 'even if' implies that keys are expected to be kept for an empty bundle after filtering, but that you're taking an exception in the cl. 

Although I know where this cl came from (it's discovered in data filtering for chromium) and I requested this fix, your cl description is still confusing to me. 

I'd rather include what you wrote in response to my question. Imho, most ICU cl descriptions tend to be too terse to be useful. See go/tott/536 at Google.

**Comment by sffc** [comment]
OK, changed "even if" to "if".

> Although I know where this cl came from (it's discovered in data filtering for chromium) and I requested this fix, your cl description is still confusing to me.

I separately discovered this one while doing google3 integration.  The one found during V8 integration is #571 I believe.

**Pull request merged**
