### PR TITLE
ICU-21562 Add include to fix std:abs build problem

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21562
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm

**Review by hugovdm — COMMENTED** [review]
Thanks!

I'll experiment with this when I poke at "include-what-you-use" (https://unicode-org.atlassian.net/browse/ICU-8530) - e.g. removing the include to see what happens.

**Comment by FrankYFTang** [comment]
The problem is "libc++ unexpectedly defines std::abs(float) in cmath and std::abs(int) in cstdlib."

see also https://gcc.gnu.org/bugzilla/show_bug.cgi?id=89855
My understanding is different platforms ( or compiler + library) somehow define them in different header file ...

**Comment by FrankYFTang** [comment]
Therefore, you need to try it on all platform OR you check the C++ documentation
https://en.cppreference.com/w/cpp/numeric/math/abs
said


Defined in header <cstdlib> |   |  
-- | -- | --
Defined in header <cmath>

**Pull request merged**
