### PR TITLE
ICU-22561 Added maven-gpg-plugin in pom.xml to sign artifacts for mav…

### PR DESCRIPTION
**Pull request by yumaoka**
…en central release.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22561
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by yumaoka** [comment]
This updated pom.xml was actually used for 74.1 release. Because repo was already tagged at that time, I merged the change to main branch at that time. For 74.2 maintenance update, we need this one merged to maint-74 branch as discussed in 2023-11-30 ICU-TC meeting.

**Review by markusicu — CHANGES_REQUESTED** [review]
Please retarget this cherry-pick PR to `maint/maint-74`.

Given that it currently targets `main`, how is it possible that it shows the same change as in PR #2693 which you merged into `main`??

Did you follow the [instructions](https://unicode-org.github.io/icu/userguide/dev/gitdev.html#after-ga) or do something equivalent?

**Comment by yumaoka** [comment]
@markusicu @mihnita My mistake. Retargetted to maint-74.

**Review by markusicu — APPROVED** [review]
rslgtm tnx

**Review by mihnita — COMMENTED** [review]
Thanks!
LGTM (but for some reason)

For some reason I don't get the buttons to approve.
So consider this an approval.

**Pull request merged**
