### PR TITLE
ICU-21472 Update ICU to support latest CLDR units updates (ofglucose, new constants)

### PR DESCRIPTION
**Pull request by hugovdm**
This updates ICU code to match [CLDR-14232 Change blood glucose measures to be compatible](https://github.com/unicode-org/cldr/pull/951) and [CLDR-14232 regenerate unit test data](https://github.com/unicode-org/cldr/pull/987).

* This units.txt was generated from units.xml in cldr, not in cldr-staging, because cldr-staging has not been updated since 16 December.

Closes: icu-units#126

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21472
- [X] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by hugovdm** [comment]
The checks are not supposed to pass: I don't have Java changes here yet. This indicates missing unit tests: I have reopened https://github.com/icu-units/icu/issues/92

**Review by sffc — APPROVED** [review]

**Comment by hugovdm** [comment]
Merging this, so further work can be based on master: another one's incoming, for the unitPreferences change of https://github.com/unicode-org/cldr/pull/991

**Comment by hugovdm** [comment]
Java is failing because "ofglucose" is for some reason not appearing in the output of UnitsData.getSimpleUnits - which reads "units/convertUnits" - somehow the resource file is not up to date in Java? While it works fine in C++? :thinking:

**Comment by hugovdm** [comment]
The file icu4j/main/classes/core/out/bin/com/ibm/icu/impl/data/icudt68b/units.res is taken from somewhere old (I'm getting a 2 December timestamp instead of the freshly-generated 29 January version I want). So it seems I'm not sure how ICU4J's data files work.

**Comment by hugovdm** [comment]
Ah, need to update icudata.jar

**Comment by hugovdm** [comment]
I recall us collaborative .jar reviewing last time we updated icudata.jar.

**Comment by hugovdm** [comment]
How did this get stuck... timeout after 6 horus on GHA? "nice ant check" ran 13 minutes 12 seconds on my laptop. :thinking: - retry?

@sffc how thoroughly do we want to review the icudata.jar update, when we know it will be updated again officialy in the next couple of weeks?

**Comment by sffc** [comment]
I re-generated the jar file and it looks like the tests are passing.  I couldn't push to your branch because it required LFS access, so I pushed it to my fork instead:

https://github.com/sffc/icu/tree/cldr_update_ofglucose

**Comment by hugovdm** [comment]
I'll experiment with jar file regeneration independently of this PR - for now, I'm just cherry-picking yours. Thanks for doing this!

**Comment by sffc** [comment]
LGTM please squash

**Comment by hugovdm** [comment]
Squashed!

**Review by younies — APPROVED** [review]

**Pull request merged**
