### PR TITLE
ICU-22740 Add missing template arguments in MF2 parser

### PR DESCRIPTION
**Pull request by catamorphism**
This fixes a clang-17 `-Wctad-maybe-unsupported` warning.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22740
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by catamorphism** [comment]
cc @roubert @echeran

**Review by roubert — APPROVED** [review]
LGTM

**Review by roubert — COMMENTED** [review]
Hm, I didn't realize before that there were configurations that used `-Werror` without also using `-Wall -Wextra`, maybe this'll be a bit easier to maintain if only those get the new warning added.

**Comment by catamorphism** [comment]
> Hm, I didn't realize before that there were configurations that used `-Werror` without also using `-Wall -Wextra`, maybe this'll be a bit easier to maintain if only those get the new warning added.

Fixed in [b849e63](https://github.com/unicode-org/icu/pull/2971/commits/b849e63e5338f6f380505038357e23b878122c17)

**Comment by roubert** [comment]
> Fixed in [b849e63](https://github.com/unicode-org/icu/pull/2971/commits/b849e63e5338f6f380505038357e23b878122c17)

Now you got it backwards, `-Wctad-maybe-unsupported` should go together with `-Werror -Wall -Wextra`.

**Comment by catamorphism** [comment]
> Now you got it backwards, `-Wctad-maybe-unsupported` should go together with `-Werror -Wall -Wextra`.

Oops. Should be fixed now.

**Review by roubert — APPROVED** [review]
LGTM

**Pull request merged**
