### PR TITLE
ICU-21635 Unicode 14 beta

### PR DESCRIPTION
**Pull request by markusicu**
- update version numbers
- copy change log for Unicode 13 & make initial adjustments for Unicode 14
- run Python scripts with 20210609 Unicode data files
- tweak the main script to make ppucd.txt compaction more deterministic
  - ppucd.txt still flip-flops between block default values when one becomes slightly more common
- add API constants for new property values
- document new Bazel build process, extend it to cover all data files
- fix & run Unicode data generator tools
- update unit tests
- update a hardcoded list of Default_Ignorable_Code_Point ranges
- line break: remove redundant LB 27a rule
- update zh collation & translit from CLDR
- update Java data & test data

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21635
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by markusicu** [comment]
Thanks @Manishearth for approving, but this is incomplete and thus still “draft” ;-)

**Comment by markusicu** [comment]
Hi @echeran FYI the second commit here is my first real use of your Bazel build. I fixed some tools after @sffc's toolutil change, documented the Bazel build in my change log (might move it elsewhere later), and extended it to clean & generate more files.

Next I need to look at tests, then collation, then Java.

Once the Unicode 14 update is done, it would be good to get the Bazel build into CI to prevent bit rot.

**Comment by aheninger** [comment]
The line break rule files all have a comment at the top that gives the UAX-14 version and the Unicode version that they are implementing. Applies to both the main data rules and the monkey test rule files. These want to be updated.

When updating rules, I usually make the root file look right, create a diff file from that, then patch that into all the tailoring files. Might be overkill for something this simple, though.

Where things get messy is when updates affect rules that are also modified by some of the tailorings. In which case I end up diffing the rules in every which direction, trying to keep the tailorings intact.

**Comment by markusicu** [comment]
> The line break rule files all have a comment at the top that gives the UAX-14 version and the Unicode version that they are implementing. Applies to both the main data rules and the monkey test rule files. These want to be updated.

done

**Comment by aheninger** [comment]
The changes to the break iterator files look good to me.

**Comment by markusicu** [comment]
FYI rebased onto the latest "main"

**Comment by markusicu** [comment]
I think this is it for Unicode 14 beta -- ready for review. Note that the data file changes just follow Unicode and CLDR.

I will probably move the Bazel build documentation out of the change log, but probably in a follow-up PR.

I have not squashed yet, in case y'all find it useful to look at the stages of this update.

**Review by macchiati — DISMISSED** [review]
It all looks great. Caveat: I didn't look at the big generated files, nor at the collation files that I'd already reviewed.

**Comment by markusicu** [comment]
I just rearranged some of the intro/overview docs for Unicode updates. In particular, I moved most of the new text about Bazel to the Unicode Update page, and generally refreshed that page and the BRS Standards page.

Any more feedback before I squash?

**Comment by markusicu** [comment]
Squashed. I would like to ask for someone to approve; note that Mark reviewed the substantive changes on Saturday, the only changes since then are to docs.

**Review by echeran — DISMISSED** [review]
RSLGTM

**Review by echeran — APPROVED** [review]
RSLGTM after the [typo fix since the last push](https://github.com/unicode-org/icu/compare/unicode-org:f6aad09..unicode-org:aa8ea6e)

**Pull request merged**
