### PR TITLE
ICU-21480 integrate CLDR release-39-alpha2 to ICU trunk

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21480
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [x] Documentation is changed or added

This integrates the version of CLDR tagged release-39-alpha2 into ICU. The changes here are the result of just a couple of enhancements (for grammatical info and Latin-ASCII transform), plus the result of some CLDR BRS tasks. This CLDR version is what will likely become the public alpha.

### CODE REVIEW

**Review by hugovdm — APPROVED** [review]
Looks good to me.

I also traced through some of the units changes to confirm the fallbacks and data reduction is behaving like I expect it to.

**Review by jefgen — APPROVED** [review]
thanks Peter!

**Comment by jefgen** [comment]
Note: All the CI builds passed, but for some reason GitHub seems to be having issues waiting for the CI check status to be reported.

image

I'm going to bypass the check for now, and merge the PR, as all the builds/tests have passed.

**Pull request merged**
