### PR TITLE
ICU-22285 omit the gb2312 & big5han collation tailorings by default

### PR DESCRIPTION
**Pull request by markusicu**
This reduces the size of coll/zh.res from 918660 bytes to 682904 bytes.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22285
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by FrankYFTang** [comment]
./main/tests/collate/src/com/ibm/icu/dev/test/collator/CollationServiceTest.java
./main/tests/collate/src/com/ibm/icu/dev/test/util/ICUResourceBundleCollationTest.java
./main/tests/core/src/com/ibm/icu/dev/test/util/TestLocaleValidity.java

need to be changes to remove the test against big5han and gb2312han

**Comment by FrankYFTang** [comment]
https://github.com/unicode-org/icu/actions/runs/4410702565/jobs/7728445138#step:7:1
```
name "*.txt" -exec grep -l FAILED {} \;`;
Testsuite: com.ibm.icu.dev.test.util.ICUResourceBundleCollationTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.043 sec

Testcase: TestFunctionalEquivalent took 0.01 sec
	FAILED
16:  Error, expected  Equiv=false		zh_TW_STROKE@collation=big5han		--> zh@collation=big5han,  but got false zh@collation=stroke
junit.framework.AssertionFailedError: 16:  Error, expected  Equiv=false		zh_TW_STROKE@collation=big5han		--> zh@collation=big5han,  but got false zh@collation=stroke
	at com.ibm.icu.dev.test.AbstractTestLog.errln(AbstractTestLog.java:50)
	at com.ibm.icu.dev.test.util.ICUResourceBundleCollationTest.getFunctionalEquivalentTestCases(ICUResourceBundleCollationTest.java:1[7](https://github.com/unicode-org/icu/actions/runs/4410702565/jobs/7728445138#step:7:8)9)
	at com.ibm.icu.dev.test.util.ICUResourceBundleCollationTest.TestFunctionalEquivalent(ICUResourceBundleCollationTest.java:7[8](https://github.com/unicode-org/icu/actions/runs/4410702565/jobs/7728445138#step:7:9))
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

Testcase: TestOpen took 0 sec
Testcase: TestKeywordValues took 0 sec
Testcase: TestGetWithFallback took 0.004 sec
```

**Comment by FrankYFTang** [comment]
looks like you have merge conflict and need a rebase/merge

**Comment by markusicu** [comment]
Amended with Java changes, and rebased.

**Review by echeran — APPROVED** [review]
LGTM

**Review by FrankYFTang — APPROVED** [review]

**Review by sffc — COMMENTED** [review]
(this was merged with me as assignee in less than 24 hours before I had a chance to open and review it)

The docs do not explain how to reset the rules back to include big5han and gb2312han. If the idea is to add a rule such as "+/collations", please document that, and also test it by adding that rule to icu/.ci-builds/data-filter.json and then run a test to ensure that the collations work by adding it here:

https://github.com/unicode-org/icu/blob/main/.ci-builds/.azure-pipelines.yml#L62

**Comment by markusicu** [comment]
> The docs do not explain how to reset the rules back to include big5han and gb2312han. If the idea is to add a rule such as "+/collations", please document that,

Ok --> PR #2371

> and also test it by adding that rule to icu/.ci-builds/data-filter.json and then run a test to ensure that the collations work by adding it here:
> 
> https://github.com/unicode-org/icu/blob/main/.ci-builds/.azure-pipelines.yml#L62

I tested it manually and verified that coll/zh.res is back to its old size, but I don't know how to write a test that works with and without these tailorings in the data, and tells us something useful in CI. Ideas?

**Comment by sffc** [comment]
> Ideas?

Pass a config somehow to the test? Lots of ways to do that: environment variable at runtime, `-D` variable at compile time, new argument to intltest, existing argument to intltest, ...

I think it's worthwhile testing. Otherwise there's no code anywhere that verifies that these collations even work or run to completion; we may as well delete them entirely.

**Comment by markusicu** [comment]
> Pass a config somehow to the test? Lots of ways to do that: environment variable at runtime, `-D` variable at compile time, new argument to intltest, existing argument to intltest, ...

I might create a follow-up ticket for that.

> I think it's worthwhile testing. Otherwise there's no code anywhere that verifies that these collations even work or run to completion; we may as well delete them entirely.

There is a lot that we don't test. In particular, we don't test each collation tailoring for whether it's there and does something interesting. Doing that would require more data-driven testing, because hardcoding such detailed behaviors would be too brittle.

**Pull request merged**
