### PR TITLE
ICU-20149 allow duplicate unicode attribute

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20149
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [X] Tests included
- [X] Documentation is changed or added

### CODE REVIEW

**Comment by lagingsapol77** [comment]
What I have done noone is doing and no one comes close

**Comment by FrankYFTang** [comment]
can I land this PR to trunk now? since the 64 branch is already cut?

**Comment by FrankYFTang** [comment]
ping

**Comment by FrankYFTang** [comment]
ping

**Comment by sffc** [comment]
Master is open.

**Comment by sffc** [comment]
@FrankYFTang Looks like this is ready to merge

**Pull request merged**
