### PR TITLE
ICU-21959 Online demos how to update

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [ ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21959
- [ ] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by richgillam — DISMISSED** [review]
MUCH better!  The crap from my earlier DateIntervalFormat fix is all gone now, and it's just the stuff you meant to post.  As for that stuff, it all looks good to ME, but I'm probably not the best person to ask for feedback on the ICU demos.

**Review by richgillam — APPROVED** [review]
Still looks good.

**Comment by sven-oly** [comment]
PTAL when you have a chance!

**Review by richgillam — APPROVED** [review]
Still looks good.  Sorry I missed the emails for this earlier.

**Pull request merged**
