### PR TITLE
ICU-13813: Windows icucheck.bat script does not handle if the tests c…

### PR DESCRIPTION
**Pull request by jefgen**
…rash while executing.

### CODE REVIEW

**Comment by jefgen** [comment]
Going to add a few others to the PR, just to test out the code-review process on GitHub.

**Comment by srl295** [comment]
^ just since you merged it

**Comment by jefgen** [comment]
I think I'm going to change the assignee to you @srl295, so that you show up as the reviewer in JIRA.

**Comment by srl295** [comment]
@jefgen uh… but you are the one that merged the PR!

**Comment by jefgen** [comment]
Okay, it sounds like we need to decided/figure out if we want to use the "Assignee" on the GitHub PR for designating the actual JIRA reviewer, or for designating who will merge the PR.
It doesn't bother me either way, but it would good to clarify.

**Comment by jefgen** [comment]
Minor update: It was decided in the TC call to use the "Assignee" as the primary/main reviewer for PRs, so I'm retroactively editing to set the "Assignee" to you, since you reviewed the change. (Thanks!).

**Pull request merged**
