### PR TITLE
ICU-20489 Removing resfiles.mk files.

### PR DESCRIPTION
**Pull request by sffc**
Build res_index.txt based on directory glob minus aliases read from deprecates XML file.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20489
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by pedberg-icu** [comment]
Hmm, behavior changes in ures_getFunctionalEquivalent causing failures in the C: Linux Clang bio;d, among other failures.

**Comment by sffc** [comment]
Pushed a fix for the failing test.  Markus pre-approved.

**Comment by sffc** [comment]
You get large bold text if you underline your paragraph with `---` or `===` in Markdown
---

The full list of locales being built into ICU collator is as follows, and this is not changed across this PR:

<details>
<summary>Expand for full list</summary>
<pre>
res_index:table(nofallback) {
    InstalledLocales {
        af {""}
        af_NA {""}
        agq {""}
        ak {""}
        am {""}
        ar {""}
        ar_AE {""}
        ar_DJ {""}
        ar_ER {""}
        ar_KM {""}
        ar_LB {""}
        ar_SA {""}
        ar_SO {""}
        ar_SS {""}
        as {""}
        asa {""}
        ast {""}
        az {""}
        az_Cyrl {""}
        az_Latn {""}
        az_Latn_AZ {""}
        bas {""}
        be {""}
        bem {""}
        bez {""}
        bg {""}
        bm {""}
        bn {""}
        bo {""}
        bo_IN {""}
        br {""}
        brx {""}
        bs {""}
        bs_Cyrl {""}
        bs_Latn {""}
        bs_Latn_BA {""}
        ca {""}
        ca_FR {""}
        ccp {""}
        ce {""}
        ceb {""}
        cgg {""}
        chr {""}
        ckb {""}
        cs {""}
        cy {""}
        da {""}
        dav {""}
        de {""}
        de_CH {""}
        de_LI {""}
        de_LU {""}
        dje {""}
        dsb {""}
        dua {""}
        dyo {""}
        dz {""}
        ebu {""}
        ee {""}
        el {""}
        en {""}
        en_001 {""}
        en_150 {""}
        en_AE {""}
        en_AG {""}
        en_AI {""}
        en_AT {""}
        en_AU {""}
        en_BB {""}
        en_BE {""}
        en_BI {""}
        en_BM {""}
        en_BS {""}
        en_BW {""}
        en_BZ {""}
        en_CA {""}
        en_CC {""}
        en_CH {""}
        en_CK {""}
        en_CM {""}
        en_CX {""}
        en_CY {""}
        en_DE {""}
        en_DG {""}
        en_DK {""}
        en_DM {""}
        en_ER {""}
        en_FI {""}
        en_FJ {""}
        en_FK {""}
        en_FM {""}
        en_GB {""}
        en_GD {""}
        en_GG {""}
        en_GH {""}
        en_GI {""}
        en_GM {""}
        en_GY {""}
        en_HK {""}
        en_IE {""}
        en_IL {""}
        en_IM {""}
        en_IN {""}
        en_IO {""}
        en_JE {""}
        en_JM {""}
        en_KE {""}
        en_KI {""}
        en_KN {""}
        en_KY {""}
        en_LC {""}
        en_LR {""}
        en_LS {""}
        en_MG {""}
        en_MO {""}
        en_MS {""}
        en_MT {""}
        en_MU {""}
        en_MW {""}
        en_MY {""}
        en_NA {""}
        en_NF {""}
        en_NG {""}
        en_NL {""}
        en_NR {""}
        en_NU {""}
        en_NZ {""}
        en_PG {""}
        en_PH {""}
        en_PK {""}
        en_PN {""}
        en_PW {""}
        en_RW {""}
        en_SB {""}
        en_SC {""}
        en_SD {""}
        en_SE {""}
        en_SG {""}
        en_SH {""}
        en_SI {""}
        en_SL {""}
        en_SS {""}
        en_SX {""}
        en_SZ {""}
        en_TC {""}
        en_TK {""}
        en_TO {""}
        en_TT {""}
        en_TV {""}
        en_TZ {""}
        en_UG {""}
        en_VC {""}
        en_VG {""}
        en_VU {""}
        en_WS {""}
        en_ZA {""}
        en_ZM {""}
        en_ZW {""}
        eo {""}
        es {""}
        es_419 {""}
        es_AR {""}
        es_BO {""}
        es_BR {""}
        es_BZ {""}
        es_CL {""}
        es_CO {""}
        es_CR {""}
        es_CU {""}
        es_DO {""}
        es_EC {""}
        es_GQ {""}
        es_GT {""}
        es_HN {""}
        es_MX {""}
        es_NI {""}
        es_PA {""}
        es_PE {""}
        es_PH {""}
        es_PR {""}
        es_PY {""}
        es_SV {""}
        es_US {""}
        es_UY {""}
        es_VE {""}
        et {""}
        eu {""}
        ewo {""}
        fa {""}
        fa_AF {""}
        ff {""}
        ff_GN {""}
        ff_Latn {""}
        ff_Latn_GH {""}
        ff_Latn_GM {""}
        ff_Latn_GN {""}
        ff_Latn_LR {""}
        ff_Latn_MR {""}
        ff_Latn_NG {""}
        ff_Latn_SL {""}
        ff_MR {""}
        fi {""}
        fil {""}
        fil_PH {""}
        fo {""}
        fo_DK {""}
        fr {""}
        fr_BI {""}
        fr_CA {""}
        fr_CD {""}
        fr_DJ {""}
        fr_DZ {""}
        fr_GN {""}
        fr_HT {""}
        fr_KM {""}
        fr_LU {""}
        fr_MG {""}
        fr_MR {""}
        fr_MU {""}
        fr_RW {""}
        fr_SC {""}
        fr_SY {""}
        fr_TN {""}
        fr_VU {""}
        fur {""}
        fy {""}
        ga {""}
        gd {""}
        gl {""}
        gsw {""}
        gu {""}
        guz {""}
        gv {""}
        ha {""}
        ha_GH {""}
        ha_NE {""}
        haw {""}
        he {""}
        he_IL {""}
        hi {""}
        hr {""}
        hr_BA {""}
        hsb {""}
        hu {""}
        hy {""}
        ia {""}
        id {""}
        id_ID {""}
        ig {""}
        ii {""}
        is {""}
        it {""}
        ja {""}
        ja_JP {""}
        jgo {""}
        jmc {""}
        jv {""}
        ka {""}
        kab {""}
        kam {""}
        kde {""}
        kea {""}
        khq {""}
        ki {""}
        kk {""}
        kkj {""}
        kl {""}
        kln {""}
        km {""}
        kn {""}
        ko {""}
        kok {""}
        ks {""}
        ksb {""}
        ksf {""}
        ksh {""}
        ku {""}
        kw {""}
        ky {""}
        lag {""}
        lb {""}
        lg {""}
        lkt {""}
        ln {""}
        ln_AO {""}
        lo {""}
        lrc {""}
        lt {""}
        lu {""}
        luo {""}
        luy {""}
        lv {""}
        mas {""}
        mas_TZ {""}
        mer {""}
        mfe {""}
        mg {""}
        mgh {""}
        mgo {""}
        mi {""}
        mk {""}
        ml {""}
        mn {""}
        mr {""}
        ms {""}
        ms_BN {""}
        ms_SG {""}
        mt {""}
        mua {""}
        my {""}
        mzn {""}
        naq {""}
        nb {""}
        nb_NO {""}
        nd {""}
        nds {""}
        ne {""}
        nl {""}
        nl_AW {""}
        nl_BQ {""}
        nl_CW {""}
        nl_SR {""}
        nl_SX {""}
        nmg {""}
        nn {""}
        nn_NO {""}
        nnh {""}
        nus {""}
        nyn {""}
        om {""}
        om_KE {""}
        or {""}
        os {""}
        os_RU {""}
        pa {""}
        pa_Arab {""}
        pa_Arab_PK {""}
        pa_Guru {""}
        pa_Guru_IN {""}
        pl {""}
        ps {""}
        ps_PK {""}
        pt {""}
        pt_AO {""}
        pt_CH {""}
        pt_CV {""}
        pt_GQ {""}
        pt_GW {""}
        pt_LU {""}
        pt_MO {""}
        pt_MZ {""}
        pt_PT {""}
        pt_ST {""}
        pt_TL {""}
        qu {""}
        qu_BO {""}
        qu_EC {""}
        rm {""}
        rn {""}
        ro {""}
        ro_MD {""}
        rof {""}
        ru {""}
        ru_BY {""}
        ru_KG {""}
        ru_KZ {""}
        ru_MD {""}
        rw {""}
        rwk {""}
        sah {""}
        saq {""}
        sbp {""}
        sd {""}
        se {""}
        se_SE {""}
        seh {""}
        ses {""}
        sg {""}
        shi {""}
        shi_Latn {""}
        shi_Tfng {""}
        shi_Tfng_MA {""}
        si {""}
        sk {""}
        sl {""}
        smn {""}
        sn {""}
        so {""}
        so_DJ {""}
        so_ET {""}
        so_KE {""}
        sq {""}
        sq_MK {""}
        sr {""}
        sr_Cyrl {""}
        sr_Cyrl_BA {""}
        sr_Cyrl_RS {""}
        sr_Cyrl_XK {""}
        sr_Latn {""}
        sr_Latn_BA {""}
        sr_Latn_ME {""}
        sr_Latn_RS {""}
        sv {""}
        sw {""}
        sw_CD {""}
        sw_UG {""}
        ta {""}
        ta_LK {""}
        ta_MY {""}
        ta_SG {""}
        te {""}
        teo {""}
        teo_KE {""}
        tg {""}
        th {""}
        th_TH {""}
        ti {""}
        ti_ER {""}
        tk {""}
        to {""}
        tr {""}
        tt {""}
        twq {""}
        tzm {""}
        ug {""}
        uk {""}
        ur {""}
        ur_IN {""}
        uz {""}
        uz_Arab {""}
        uz_Arab_AF {""}
        uz_Cyrl {""}
        uz_Latn {""}
        uz_Latn_UZ {""}
        vai {""}
        vai_Latn {""}
        vai_Vaii {""}
        vai_Vaii_LR {""}
        vi {""}
        vun {""}
        wae {""}
        wo {""}
        xh {""}
        xog {""}
        yav {""}
        yi {""}
        yo {""}
        yo_BJ {""}
        yue {""}
        yue_Hans {""}
        yue_Hans_CN {""}
        yue_Hant {""}
        yue_Hant_HK {""}
        zgh {""}
        zh {""}
        zh_Hans {""}
        zh_Hans_CN {""}
        zh_Hans_HK {""}
        zh_Hans_MO {""}
        zh_Hans_SG {""}
        zh_Hant {""}
        zh_Hant_HK {""}
        zh_Hant_MO {""}
        zh_Hant_TW {""}
        zu {""}
    }
}
</pre>
</details>

Note that `zh_Hant_TW`, `zh_Hans_CN`, etc., are indeed "physically present" in the data bundle, which are the tests that changed.  So technically I think this could be considered a bug fix, since we are now doing more to obey the API contract.

**Comment by sffc** [comment]
Here is the diff from the old coll/res_index.txt to the new coll/res_index.txt:

https://www.diffchecker.com/uvgYx8ta

**Comment by pedberg-icu** [comment]
> Note that `zh_Hant_TW`, `zh_Hans_CN`, etc., are indeed "physically present" in the data bundle, which are the tests that changed. So technically I think this could be considered a bug fix, since we are now doing more to obey the API contract.

OK, makes sense.

**Comment by sffc** [comment]
Squashed; please approve

**Pull request merged**
