### PR TITLE
Revert "ICU-22357 Update gb18030 mappings for the -2022 version"

### PR DESCRIPTION
**Pull request by sffc**
Reverts unicode-org/icu#2430

I want to see if this fixes CI. If it does, we should figure out why.

CC @pedberg-icu @markusicu @richgillam @gvictor

### CODE REVIEW

**Comment by markusicu** [comment]
> I want to see if this fixes CI. If it does, we should figure out why.

All tests pass, including the DataFilter test. Which is bad news :-/

(All pass except for "jira-ticket" and "single-commit".)

**Comment by pedberg-icu** [comment]
@sffc This can be closed now, right?

**Comment by sffc** [comment]
Superseded by https://github.com/unicode-org/icu/pull/2471

**Comment by sffc** [comment]
I do find it quite curious how two things coincided: a PR landed in the uconv code, which very rarely changes, and also we start getting flaky tests that point to the uconv code. But, we seem to agree that this is a pure coincidence and that the root cause is actually the CI parallelism change.

**Pull request closed without merging**
