### PR TITLE
ICU-21008 Make ant checkTest run tests in exhaustive mode

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21008
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by markusicu** [comment]
I would like to see some discussion on the ticket and/or in the TC before we do this.

**Comment by sffc** [comment]
An email has been sent to icu-core, with one "SGTM" and no other comments.  I have accepted the ticket.

**Comment by sffc** [comment]
The commit was misticketted (caught by the bot); I re-wrote the message with the correct ticket number.

**Comment by sffc** [comment]
To be super clear on the effect of this PR:

- `ant check` is unaffected.
- `ant exhaustiveCheck` is unaffected.
- `ant checkTest` is unaffected when the target test is not exhaustive.
- `ant checkTest` will now run target tests even if they are exhaustive; before, it would skip them because they were exhaustive.

**Pull request merged**
