### PR TITLE
ICU-22549 Revert "ICU-22549 Improve fuzzer to test more locale"

### PR DESCRIPTION
**Pull request by FrankYFTang**
This reverts commit 11d1148e5680fe62456659af85b37f690612ba73.

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22549
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by richgillam — APPROVED** [review]
Really interested to see if this fixes the problem you're seeing...

**Comment by FrankYFTang** [comment]
we got "build failure" on fuzzer . Revert to stop the bleeding first.

**Comment by FrankYFTang** [comment]
The revert did fix that "build failure" as automatically find out by the oss-fuzz project. 

see  https://oss-fuzz-build-logs.storage.googleapis.com/index.html#icu 
notice the build of "1/2/2024, 11:56:04 PM  (Pacific Standard Time)" is bad which is based on git commit 1a60a038e14f0c56f50052c03fe76c4933cda339

then the build of "1/3/2024, 10:44:22 PM (Pacific Standard Time)" is good which is based on git commit 
539e8f41a35fec30fba4cfb3a65ea4db67978f85

and the diff between these two commits are only
52ff51e82c74adc52629b411d8cf6718c45e2210 ICU-22532 Compiler warning: conversion from 'double' to 'int32_t'.

and
539e8f41a35fec30fba4cfb3a65ea4db67978f85 ICU-22549 Revert "Improve fuzzer to test more locale"


I think what happen is the reverted part expose too many crash at once and make the system think it is a bad build. I will crate separated smaller impact PR of what got reverted and land into the fuzzer one by one so the system will not consider the PR itself is bad.

**Comment by FrankYFTang** [comment]
I believe I found the bug of my PR. I incorrectly pass the fuzzer data, which is not guarantee to be null terminated into the Locale constructor which expect null terminated const char* . That is not an API issue but my bad in fuzzer code.

**Pull request merged**
