### PR TITLE
ICU-21363 Add support for IBM's XL compiler

### PR DESCRIPTION
**Pull request by datalogics-robb**
IBM's XL compiler can only support c++11 when the 'clang front end' is used.
This change modifies the configure step to use xlclang and  xlclang++

##### Checklist

- [*] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21363
- [*] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included (not applicable)
- [*] Documentation is changed or added

### CODE REVIEW

**Review by yumaoka — DISMISSED** [review]
LGTM

**Comment by yumaoka** [comment]
@datalogics-robb We need your commit message stating with `ICU-21363: Resurect support for IBM's XL compiler...` to merge this PR. Can you amend the commit comment?

**Comment by yumaoka** [comment]
@datalogics-robb Thanks for taking action. It looks the PR seems to be messed up. Would you mind if I just create a new PR based on master HEAD, just applying your original change?

**Comment by datalogics-robb** [comment]
What happened to this repo?  It's really messed up - did the history change?

**Comment by datalogics-robb** [comment]
```
(python-env-robs-macbook-pro-2) robb@Robs-MacBook-Pro-2:~/OpenSource$ git clone git@github.com:unicode-org/icu.git
Cloning into 'icu'...
remote: Enumerating objects: 47, done.
remote: Counting objects: 100% (47/47), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 498629 (delta 23), reused 13 (delta 6), pack-reused 498582
Receiving objects: 100% (498629/498629), 235.48 MiB | 3.24 MiB/s, done.
Resolving deltas: 100% (396592/396592), done.
git-lfs smudge 'icu4j/main/shared/data/icudata.jar': git-lfs: command not found
error: external filter 'git-lfs smudge %f' failed 127
error: external filter 'git-lfs smudge %f' failed
fatal: icu4j/main/shared/data/icudata.jar: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

(python-env-robs-macbook-pro-2) robb@Robs-MacBook-Pro-2:~/OpenSource$ 
```

**Comment by datalogics-robb** [comment]
I can't even clone the repo, let alone rebase.

**Comment by jefgen** [comment]
>  git-lfs: command not found

Do you have git lfs (https://git-lfs.github.com/) installed?
I wonder if maybe that might be the issue.
(FWIW, the ICU repo uses/requires Git LFS for some of the binary files.)

**Comment by yumaoka** [comment]
@datalogics-robb I created the equivalent PR - https://github.com/unicode-org/icu/pull/1499
Could you please review the changes in the PR is exactly what you proposed?

We'd like to include this fix for ICU 68.2 coming soon.

**Comment by yumaoka** [comment]
This is done by PR #1499. Closing this one. Thanks @datalogics-robb

**Pull request closed without merging**
