### PR TITLE
ICU-21179 Remove unused code in Java break engines

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21179
- [x] Required: The PR title must be prefixed with a JIRA Issue number. For example: "ICU-1234 Fix xyz"
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. For example: "ICU-1234 Fix xyz"
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by FrankYFTang** [comment]
why are we making this change? This change the logic and is not remove unused code.

**Comment by markusicu** [comment]
> why are we making this change? This change the logic and is not remove unused code.

In the review of the C++ PR #1192 Andy requested making the same change in Java. So this should be a port. (Haven't looked yet.)

**Comment by FrankYFTang** [comment]
I have hard time to see this is a removal of "unused code".

**Comment by aheninger** [comment]
> I have hard time to see this is a removal of "unused code".

The code being removed does nothing. The " if (wordsMatched < 2) {" is unconditionally true every time. After the assignment 
"wordsMatched = 2;" the variable is never referenced again before going out of scope.

Maybe "unused" is not the best word, but it's close enough.

**Review by aheninger — APPROVED** [review]

**Pull request merged**
