### PR TITLE
ICU-13709 fix shadow param inside #ifdef

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-13709
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [X] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
There are a number of methods that have a `length` parameter.  Does this warning only affect constructors?

Do you want this on the ICU 64 maintenance branch?

**Comment by sffc** [comment]
Also, how about these constructors?

```cpp
inline UnicodeString(const std::nullptr_t text, int32_t length);
UnicodeString(const char *src, int32_t length, enum EInvariant inv);
```

**Comment by sffc** [comment]
Thanks for the commit.  Looks like that answers my third question.  Can you comment on my first two questions?

> There are a number of methods that have a `length` parameter. Does this warning only affect constructors?
> 
> Do you want this on the ICU 64 maintenance branch?

**Comment by FrankYFTang** [comment]
> There are a number of methods that have a `length` parameter. Does this warning only affect constructors?

The bug report is only about constructor, not other method. I have no idea the warning only affect constructors or not. It is out of the scope of this bug report.
 
> Do you want this on the ICU 64 maintenance branch?

No.

**Comment by sffc** [comment]
OK.  There may be future work, but that's no reason to block this PR.  LGTM, please squash

**Comment by FrankYFTang** [comment]
squashed

**Pull request merged**
