### PR TITLE
ICU-22309 Clarify CLA instructions

### PR DESCRIPTION
**Pull request by catamorphism**
- Make it clear in the documentation that any initial pull request triggers an opportunity to sign the CLA.

When reading the "Contributor Licensing Agreement" section of the contributing guidelines, it was unclear to me what "just open a Pull Request" meant. Some projects require a pull request to a specific contributor-list file in order to join the organization. I realized that what this meant was that opening *any* pull request initiates the process. I edited the document to make that more obvious.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22309
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by catamorphism** [comment]
cc @srl295

**Comment by srl295** [comment]
What is a contributor-list file?

**Comment by catamorphism** [comment]
> What is a contributor-list file?

For example, WebKit has a contributor list in its repository: https://github.com/WebKit/WebKit/blob/main/metadata/contributors.json

New contributors have to submit a pull request to add their name to this list. When I was reading the icu `CONTRIBUTING.md` file and saw the words, "just open a Pull Request", I assumed that meant to open a pull request against a metadata file like this one, but I wasn't sure what that file was. Then I realized it was referring to the `CLAassistant` comment that shows up automatically on any initial pull request. But it wasn't obvious to me at first.

**Comment by srl295** [comment]
> > What is a contributor-list file?
> 
> 
> 
> For example, WebKit has a contributor list in its repository: https://github.com/WebKit/WebKit/blob/main/metadata/contributors.json
> 
> 
> 
> New contributors have to submit a pull request to add their name to this list. When I was reading the icu `CONTRIBUTING.md` file and saw the words, "just open a Pull Request", I assumed that meant to open a pull request against a metadata file like this one, but I wasn't sure where that file was in the icu repo. Then I realized it was referring to the `CLAassistant` comment that shows up automatically on any initial pull request. But it wasn't obvious to me at first.

Ok makes sense. 

This wording is managed org-wide so I will be back with changes on it a bit later 

Fyi @annebright

**Comment by srl295** [comment]
@catamorphism I've created a PR 'upstream' to make this exact change.

**Comment by markusicu** [comment]
> This wording is managed org-wide.

@srl295 Just to be clear: We still want to approve & merge this ICU PR here so that we are back in sync with the unicode-org language about this, right?

**Comment by srl295** [comment]
> > This wording is managed org-wide.
> 
> 
> 
> @srl295 Just to be clear: We still want to approve & merge this ICU PR here so that we are back in sync with the unicode-org language about this, right?

Yes go ahead

**Review by srl295 — APPROVED** [review]

**Review by markusicu — APPROVED** [review]

**Comment by markusicu** [comment]
I see that this was stuck on a failed (flaky) CI check, but also that this was subsumed by PR #2552.

**Pull request closed without merging**
