### PR TITLE
Compiling with fPIC error: recipe for target 'out/tmp/icudata.lst' failed

### PR DESCRIPTION
**Pull request by jobs-git**
In addition `libicudata*.so*` (should be shared) files are static libraries while in fact configured with `--enable-shared` making them unusable, defeating the purpose of ICU.

How to fix this?

### CODE REVIEW

**Comment by srl295** [comment]
@jobs-git the commit seems unrelated.  Please file bugs at https://bugs.icu-project.org/trac

**Comment by srl295** [comment]
@jobs-git did you ever file a ticket? Can you put its URL here?

**Comment by jobs-git** [comment]
Hi, I have not filed any ticket yet, I could not access the site you have given https://bugs.icu-project.org/tracking

**Comment by srl295** [comment]
http://bugs.icu-project.org/trac or https://ssl.icu-project.org/trac/

**Comment by jobs-git** [comment]
Hi, this is the ticket for the bug report http://bugs.icu-project.org/trac/ticket/12974

**Pull request closed without merging**
