### PR TITLE
ICU-22151 Update timezone-region supplementation mapping data for Jan…

### PR DESCRIPTION
**Pull request by yumaoka**
… Mayen and some others

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22151
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
FYI @macchiati @gnrunge

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Review by macchiati — APPROVED** [review]

**Review by pedberg-icu — APPROVED** [review]

**Comment by markusicu** [comment]
@yumaoka ok if I merge your PR here?

**Pull request merged**
