### PR TITLE
ICU-22326 logKnownIssue skip for exhaustive test failures with kxv(_Deva)? day/month names

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22326
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
tnx!

**Comment by pedberg-icu** [comment]
Any TC member, feel free to merge when this passes tests and is approved, thanks

**Review by markusicu — APPROVED** [review]

**Comment by pedberg-icu** [comment]
> Hooray! The files in the branch are the same across the force-push. 😃

Oops, needed separate skips for day names and month names, fixed now.

**Pull request merged**
