### PR TITLE
ICU-22576 Remove now obsolete pre-C11 backward compatibility code

### PR DESCRIPTION
**Pull request by roubert**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22576
- [X] Required: The PR title must be prefixed with a JIRA Issue number.
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number.
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by roubert** [comment]
@jefgen Would you please be so kind and help me take a look at this puzzling MSVC compilation error?

As far as I can tell from the documentation, the code in question should be just fine the way it is, also for MSVC:

https://learn.microsoft.com/en-us/cpp/c-language/alignment-c

But instead the result is this:

```
icu4c\source\test\cintltst\ccapitst.c(1838,72): Error C2275: 'UConverter': expected an expression instead of a type
            if( actualSizes[idx] <= (bufferSizes[j] - (int32_t)alignof(UConverter)) &&
                                                                       ^
```

Do you have any idea what might be going on here?

**Comment by markusicu** [comment]
> @jefgen Would you please be so kind and help me take a look at this puzzling MSVC compilation error?

@rp9-next @jalaj-microsoft FYI

**Comment by markusicu** [comment]
> As far as I can tell from the documentation, the code in question should be just fine the way it is, also for MSVC:
> 
> https://learn.microsoft.com/en-us/cpp/c-language/alignment-c

Do we need to explicitly set the C version?
Do we need to abandon an old compiler?

> Requirements
> Compile with /std:c11.
> Windows SDK 10.0.20348.0 (version 2104) or later.

**Comment by roubert** [comment]
> Do we need to explicitly set the C version?

As it turns out, yes, we do. Apparently the MSVC configuration for ICU4C doesn't specify the language standard versions to use, at all, but instead just relies on the default (or a commandline override) to be at least the version required by ICU4C (and this has apparently happened to be true until now, with the unwelcome but unnoticed side-effect of our MSVC CI accepting C++14 for quite some time now even though ICU4C was only to require C++11).

So I've uploaded PR #2767 to explicitly set C11 & C++17 in the MSVC configuration, which will solve the mystery in this PR here, but unfortunately create a new mystery of one particular unit test that for no discernable reason fails in two particular MSVC configurations when compiled as C++17.

**Comment by roubert** [comment]
> So I've uploaded PR #2767 to explicitly set C11 & C++17 in the MSVC configuration,

With that merged this PR now builds fine on every sufficiently new version of MSVC, but shows that _C11 Standard library features_ weren't introduced until VS 2019, so we'll have to drop older versions from our CI in order to actually use things from the C11 standard library (such as `alignof`) in our code:

https://learn.microsoft.com/en-us/cpp/overview/visual-cpp-language-conformance?view=msvc-170#c-standard-library-features-1

So I've now uploaded PR #2790 to remove VS 2015 and VS 2017.

**Comment by roubert** [comment]
> So I've now uploaded PR #2790 to remove VS 2015 and VS 2017.

With also that merged this PR now finally builds fine with all tests passing on every configuration in our CI, as expected. Ready for review.

**Review by cjchapman — APPROVED** [review]
👍

**Review by markusicu — APPROVED** [review]

**Pull request merged**
