### PR TITLE
ICU-21578 Merge maint/maint-69 into main

### PR DESCRIPTION
**Pull request by sffc**
Unfortunately it wasn't a clean merge, because icudata.jar changed on both branches separately (CLDR 39 on the maint branch, and laodict on the main branch).  So I had to make an intermediate branch with the merge commit.  I re-generated the jar files using the instructions in icu4j-readme.txt.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21578
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

ALLOW_MANY_COMMITS=true
DISABLE_JIRA_ISSUE_MATCH=true

### CODE REVIEW

**Comment by sffc** [comment]
> Azure Pipelines could not run because the pipeline triggers exclude this branch/path.

What does this mean?  @jefgen

**Comment by jefgen** [comment]
> > Azure Pipelines could not run because the pipeline triggers exclude this branch/path.
> 
> What does this mean? @jefgen 

Hmm, I thought at first that maybe this might be due to the rename of `master` to `main`. Perhaps the YML file might still have `master`, which would explain why the branch `main` didn't work.
However, looking in the intermediate branch I do see `main` in the config file here:
https://github.com/sffc/icu/blob/ICU-21578-merge/.ci-builds/.azure-exhaustive-tests.yml#L13

I checked the manual config for the azp bot, and FWIW, it did still have `master` in a few places. I updated them just now and I'll try a build request again. But if that doesn't work then I'll kick off a manual build.

**Comment by jefgen** [comment]
> Azure Pipelines could not run because the pipeline triggers exclude this branch/path.

Hm, I'm not sure off-hand... I'll need to take another look later.

I've kicked off a manual build here for now:
https://dev.azure.com/ms/icu/_build/results?buildId=154271&view=results
(though the status should still be reported as one of the "checks").

**Comment by jefgen** [comment]
Update: The manual run for the Exhaustive tests all passed.

**Comment by jefgen** [comment]
Note: For comparison I looked at the diffs here: https://github.com/unicode-org/icu/compare/main...maint/maint-69
However, they aren't quite the same as the diffs on GitHub seem to show changes that are already in *both* branches (like the 'zzzz' change in [locid.cpp](https://github.com/unicode-org/icu/compare/main...maint/maint-69#diff-57a1b687829da97c47474809de6546f01672a20a5902054e78b32bdb2cd6d62fR1524) for example).
Otherwise, going through the changes for each commit, the merge here looks good. 👍

**Review by jefgen — APPROVED** [review]
lgtm, thanks @sffc!

**Comment by sffc** [comment]
Merged via merge commit.

**Pull request merged**
