### PR TITLE
ICU-22495 Added support for "genitive" and "vocative" field modifiers…

### PR DESCRIPTION
**Pull request by richgillam**
…; cleaned up PersonNameConsistencyTest.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22495
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by macchiati — APPROVED** [review]

**Comment by FrankYFTang** [comment]
API proposal under discussion in https://docs.google.com/document/d/1o6FDnf1fVZTETOPlQvwR_XrE_O1F--qIjGyhkCCVnI8/edit#heading=h.ho9q42cxraz9

**Review by pedberg-icu — APPROVED** [review]

**Comment by richgillam** [comment]
@macchiati @pedberg-icu  The latest CLDR-to-ICU integration exposed a bug in my implementation of the "retain" keyword.  I've added a new commit that fixes that.  PTAL and let me know what you think.

And while I've got you, do we want to do something about the Tongan-initials problem while I'm in here?  This seems to have fallen through the cracks.  Do we know what to do?

**Review by pedberg-icu — DISMISSED** [review]

**Review by macchiati — DISMISSED** [review]

**Review by FrankYFTang — DISMISSED** [review]
LGTM

**Comment by DraganBesevic** [comment]
Looks good to me

**Review by DraganBesevic — APPROVED** [review]

**Pull request merged**
