### PR TITLE
ICU-22539 Fix BRS instructions for binary releases of ICU4C

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22539
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Issue: The blocks-release ICU ticket says what needs to be fixed in ICU 74, but the instructions are updated in main so that they become immediately visible -- which means that they go into ICU 75. So we either need to retarget the ticket to ICU 75, which will be confusing because the problem will be gone in the 74 release artifacts -- or else we need to keep this ticket in 74 and change the commit+PR to use an ICU 75 ticket (e.g., the one for minor docs fixes, or the rc BRS one).

WDYT?

**Comment by markusicu** [comment]
(actual changes here rslgtm)

**Review by srl295 — APPROVED** [review]
can't speak to the branch policy, but changes LGTM

**Review by markusicu — CHANGES_REQUESTED** [review]
adding a block until we have figured out the ticket situation

**Comment by markusicu** [comment]
@sven-oly did this get fixed elsewhere?

**Pull request closed without merging**
