### PR TITLE
ICU-21003 Fix Git LFS in CI config, add timeout to ICU4J exhaustive test

### PR DESCRIPTION
**Pull request by jefgen**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21003
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by daniel-ju** [comment]
Should we re-run the exhaustive tests with your latest changes?

**Comment by jefgen** [comment]
> Should we re-run the exhaustive tests with your latest changes?

Yes! Feel free to do so, or I can kick it off in a bit. :)

**Comment by jefgen** [comment]
Thanks Daniel!

Looking at the results:
The ICU4C exhaustive tests are clean
The ICU4J exhaustive tests fail with the following:

```
Testsuite: com.ibm.icu.dev.test.format.IntlTestNumberFormat
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.714 sec

Testcase: TestMonster took 2.673 sec
	FAILED
**** FAIL: Parse of -¤ 0,00 failed.
junit.framework.AssertionFailedError: **** FAIL: Parse of -¤ 0,00 failed.
	at com.ibm.icu.dev.test.AbstractTestLog.errln(AbstractTestLog.java:80)
	at com.ibm.icu.dev.test.format.IntlTestNumberFormat.tryIt(IntlTestNumberFormat.java:177)
	at com.ibm.icu.dev.test.format.IntlTestNumberFormat._testFormat(IntlTestNumberFormat.java:94)
	at com.ibm.icu.dev.test.format.IntlTestNumberFormat._testLocale(IntlTestNumberFormat.java:48)
	at com.ibm.icu.dev.test.format.IntlTestNumberFormat.TestMonster(IntlTestNumberFormat.java:298)

Testcase: TestLocale took 0.002 sec
Testcase: TestAvailableLocales took 0.037 sec
```

I believe this is expected due to https://unicode-org.atlassian.net/browse/ICU-21005 -- so I think this is clean to merge.

**Pull request merged**
