### PR TITLE
ICU-20826 Updating C++ ListFormatter impl to be more like Java

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20826
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
I re-implemented ICU4C ListFormatter using the logic from ICU4J.  This should result in performance improvements as it avoids a quadratic sort.

@jefgen, the MSVC bots are complaining:

```
icu4c\source\i18n\formattedval_impl.h(156,0): Error C4251: 'icu_67::FormattedValueStringBuilderImpl::spanIndices': class 'icu_67::MaybeStackArray<int32_t,8>' needs to have dll-interface to be used by clients of class 'icu_67::FormattedValueStringBuilderImpl' (compiling source file formattedval_iterimpl.cpp)
```

I could export MaybeStackArray, but that's a widely used class.  Suggestions?

**Comment by jefgen** [comment]
> I re-implemented ICU4C ListFormatter using the logic from ICU4J. This should result in performance improvements as it avoids a quadratic sort.

Nice!

> @jefgen, the MSVC bots are complaining:
> 
> ```
> icu4c\source\i18n\formattedval_impl.h(156,0): Error C4251: 'icu_67::FormattedValueStringBuilderImpl::spanIndices': class 'icu_67::MaybeStackArray<int32_t,8>' needs to have dll-interface to be used by clients of class 'icu_67::FormattedValueStringBuilderImpl' (compiling source file formattedval_iterimpl.cpp)
> ```
> 
> I could export MaybeStackArray, but that's a widely used class. Suggestions?

There's already various specializations of `MaybeStackArray` conditionally exported in various places in the ICU4C code, so this wouldn't be anything new I suppose.

You could do something like what is done here:
https://github.com/unicode-org/icu/blob/master/icu4c/source/i18n/collationiterator.h#L34

So perhaps something that looks like this (in the header `formattedval_impl.h`): 
```c++
#if U_PF_WINDOWS <= U_PLATFORM && U_PLATFORM <= U_PF_CYGWIN
template class U_I18N_API MaybeStackArray<int32_t, 8>;
#endif
```

Or perhaps as an alternative, could try something like what `LocalePriorityList` does, and wrap it with a struct that inherits from `UMemory`:

https://github.com/unicode-org/icu/blob/master/icu4c/source/common/localeprioritylist.cpp#L98

Though would mean that the `MaybeStackArray` is no longer directly part of the class `FormattedValueStringBuilderImpl`, and would be dynamically allocated. Maybe for perf having it be part of the class is better though (ie: one less heap memory allocation and also a pointer to deference rather frequently).

**Comment by sffc** [comment]
Perfect; I adopted the pattern from https://github.com/unicode-org/icu/blob/master/icu4c/source/i18n/collationiterator.h#L34

**Comment by jefgen** [comment]
Ugh, I don't think it likes the `typedef` unfortunately. :(

**Review by FrankYFTang — APPROVED** [review]
LGTM

**Pull request merged**
