### PR TITLE
ICU-9961 replace U_DRAFT/U_STABLE/U_INTERNAL with U_CAPI

### PR DESCRIPTION
**Pull request by markusicu**
https://unicode-org.atlassian.net/browse/ICU-9961

### CODE REVIEW

**Review by srl295 — DISMISSED** [review]
guidelines LGTM, 102 files RSLGTM

**Review by pedberg-icu — DISMISSED** [review]
Wow, I did not realize there were so many cpp files that used the likes of U_STABLE, U_DRAFT, U_INTERNAL etc. Thanks for cleaning this up!

**Review by pedberg-icu — COMMENTED** [review]
Should we update the comments for the following in umachine.h to inicate thay are not longer used?
```
/** This is used to declare a function as a stable public ICU C API*/
#define U_STABLE U_CAPI
/** This is used to declare a function as a draft public ICU C API  */
#define U_DRAFT  U_CAPI
/** This is used to declare a function as a deprecated public ICU C API  */
#define U_DEPRECATED U_CAPI U_ATTRIBUTE_DEPRECATED
/** This is used to declare a function as an obsolete public ICU C API  */
#define U_OBSOLETE U_CAPI
/** This is used to declare a function as an internal ICU C API  */
#define U_INTERNAL U_CAPI
```

**Comment by markusicu** [comment]
> Should we update the comments for the following in umachine.h to indicate thay are not longer used?

Yes! Thanks for reminding me!
Fixed/amended, please review again.

**Review by pedberg-icu — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
