### PR TITLE
ICU-20322 Install dll in $prefix/bin instead of $prefix/lib

### PR DESCRIPTION
**Pull request by vtorri**
before the patch: dll files are in $prefix/lib : 
$ ls -l /opt/icu_1/bin/*.dll /opt/icu_1/lib/*.dll
ls: impossible d'accéder à '/opt/icu_1/bin/*.dll': No such file or directory
-rwxr-xr-x 1 vtorri None 295K 13 déc.  20:59  /opt/icu_1/lib/icudt.dll*
-rwxr-xr-x 1 vtorri None  28M 13 déc.  21:00  /opt/icu_1/lib/icudt66.dll*
-rwxr-xr-x 1 vtorri None 4,8M 13 déc.  20:59  /opt/icu_1/lib/icuin.dll*
-rwxr-xr-x 1 vtorri None 4,8M 13 déc.  20:59  /opt/icu_1/lib/icuin66.dll*
-rwxr-xr-x 1 vtorri None 377K 13 déc.  20:59  /opt/icu_1/lib/icuio.dll*
-rwxr-xr-x 1 vtorri None 377K 13 déc.  20:59  /opt/icu_1/lib/icuio66.dll*
-rwxr-xr-x 1 vtorri None 605K 13 déc.  20:59  /opt/icu_1/lib/icutest.dll*
-rwxr-xr-x 1 vtorri None 605K 13 déc.  20:59  /opt/icu_1/lib/icutest66.dll*
-rwxr-xr-x 1 vtorri None 990K 13 déc.  20:59  /opt/icu_1/lib/icutu.dll*
-rwxr-xr-x 1 vtorri None 990K 13 déc.  20:59  /opt/icu_1/lib/icutu66.dll*
-rwxr-xr-x 1 vtorri None 3,0M 13 déc.  20:59  /opt/icu_1/lib/icuuc.dll*
-rwxr-xr-x 1 vtorri None 3,0M 13 déc.  20:59  /opt/icu_1/lib/icuuc66.dll*

after the patch, dll files are in $prefix/bin : 
$ ls -l /opt/icu_2/bin/*.dll /opt/icu_2/lib/*.dll
-rwxr-xr-x 1 vtorri None 295K 14 déc.  08:16 /opt/icu_2/bin/icudt66.dll*
-rwxr-xr-x 1 vtorri None 4,8M 14 déc.  08:16 /opt/icu_2/bin/icuin66.dll*
-rwxr-xr-x 1 vtorri None 377K 14 déc.  08:16 /opt/icu_2/bin/icuio66.dll*
-rwxr-xr-x 1 vtorri None 605K 14 déc.  08:16 /opt/icu_2/bin/icutest66.dll*
-rwxr-xr-x 1 vtorri None 990K 14 déc.  08:16 /opt/icu_2/bin/icutu66.dll*
-rwxr-xr-x 1 vtorri None 3,0M 14 déc.  08:16 /opt/icu_2/bin/icuuc66.dll*
-rwxr-xr-x 1 vtorri None  28M 14 déc.  08:16 /opt/icu_2/lib/icudt66.dll*

##### Checklist
- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20322
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by srl295** [comment]
icudt needs to be in bin also

**Comment by vtorri** [comment]
it **is** in bin/

 -rwxr-xr-x 1 vtorri None 295K 14 déc. 08:16 /opt/icu_2/bin/icudt66.dll*

but there is a make rule that create a icudt66.dll, with a very big size, in lib/

 -rwxr-xr-x 1 vtorri None 28M 14 déc. 08:16 /opt/icu_2/lib/icudt66.dll*

The build system is very complicated and i don't know where this file is copied in lib/

**Comment by jefgen** [comment]
Thanks for creating this PR @vtorri! 

I got some time to investigate this a bit, and created a branch in my fork here: https://github.com/unicode-org/icu/compare/master...jefgen:jefgen/mingw-changes 

I cherry-picked your commit and used that as a starting point. (Thank you!)
I made some more changes on top of yours.
I made it so that the move to "bin" is controlled by a setting in the `mh-mingw*` files (`MOVEDLLSTOBINDIR`) rather than the platform `U_MINGW` macro.

This way in case somebody doesn't want to have this change they can change the variable in one spot, rather than having to patch lots of files.
 
Here is what I see with the changes in my branch (your commit + my commit): 


    $ ./runConfigureICU MinGW --prefix=/opt/icu_3 --enable-tools
    ...
    $ make install
    ...

    $ ls -l /opt/icu_3/bin/*.dll
    -rwxr-xr-x 1 jefgen Domain Users   301225 Jan  7 14:50 /opt/icu_3/bin/icudt.dll
    -rwxr-xr-x 1 jefgen Domain Users 28561029 Jan  7 14:52 /opt/icu_3/bin/icudt66.dll
    -rwxr-xr-x 1 jefgen Domain Users  5000216 Jan  7 14:51 /opt/icu_3/bin/icuin.dll
    -rwxr-xr-x 1 jefgen Domain Users  5000216 Jan  7 14:51 /opt/icu_3/bin/icuin66.dll
    -rwxr-xr-x 1 jefgen Domain Users   385611 Jan  7 14:51 /opt/icu_3/bin/icuio.dll
    -rwxr-xr-x 1 jefgen Domain Users   385611 Jan  7 14:51 /opt/icu_3/bin/icuio66.dll
    -rwxr-xr-x 1 jefgen Domain Users   618603 Jan  7 14:51 /opt/icu_3/bin/icutest.dll
    -rwxr-xr-x 1 jefgen Domain Users   618603 Jan  7 14:51 /opt/icu_3/bin/icutest66.dll
    -rwxr-xr-x 1 jefgen Domain Users  1012758 Jan  7 14:51 /opt/icu_3/bin/icutu.dll
    -rwxr-xr-x 1 jefgen Domain Users  1012758 Jan  7 14:51 /opt/icu_3/bin/icutu66.dll
    -rwxr-xr-x 1 jefgen Domain Users  3047391 Jan  7 14:51 /opt/icu_3/bin/icuuc.dll
    -rwxr-xr-x 1 jefgen Domain Users  3047391 Jan  7 14:51 /opt/icu_3/bin/icuuc66.dll

    $ ls -l /opt/icu_3/lib/*.dll
    ls: cannot access '/opt/icu_3/lib/*.dll': No such file or directory

There are no more DLLs in the lib folder. 

The DLLs seem somewhat duplicated in the bin folder, but this is how they were in the lib folder before the changes. So perhaps that could/should be another bug.

(Also, I think the stubdata icudt.dll is still there and not the real data, but I'm not sure why off-hand).

**Comment by vtorri** [comment]
thank you !

all the duplicated ic*66.dll are here because of

 	cd $(DESTDIR)$(INSTALLDIR) && $(RM) $(notdir $(SO_TARGET)) && ln -s $(notdir $(FINAL_SO_TARGET)) $(notdir $(SO_TARGET))

Indeed, on Windows, there is no notion of symbolic links, hence with MSYS2, ln is a synonym of cp

that's why i have in my PR did only a installation if we are on Windows. This is a useless duplicated file. Would it be possible to add a test before

  && ln

which checks we are not on MSYS2 ?

**Comment by vtorri** [comment]
hey

any news on this ?

**Comment by jefgen** [comment]
I pushed more changes to my branch here:
https://github.com/unicode-org/icu/compare/master...jefgen:jefgen/mingw-changes

I have the DLLs all in the correct locations now when doing a `make install`.

```
$ ls -sh bin
total 45M
552K derb.exe       536K gencfu.exe    620K gennorm2.exe   28M icudt66.dll  532K icupkg.exe     424K makeconv.exe
340K escapesrc.exe  320K gencmn.exe    744K genrb.exe     4.8M icuin66.dll  608K icutest66.dll  564K pkgdata.exe
540K genbrk.exe     336K gencnval.exe  332K gensprep.exe  320K icuinfo.exe  992K icutu66.dll    576K uconv.exe
320K genccode.exe   548K gendict.exe    28K icu-config    380K icuio66.dll  3.0M icuuc66.dll

$ ls -sh lib
total 9.8M
   0 icu             6.8M libicuin.dll.a  132K libicutest.dll.a  2.7M libicuuc.dll.a
4.0K libicudt.dll.a   72K libicuio.dll.a  248K libicutu.dll.a       0 pkgconfig

```

However, I seem to have broken something with the data DLL as the `icuinfo.exe` program fails to load the data. (I get the error: `U_MISSING_RESOURCE_ERROR`).

```
    <param name="icudata.name">icudt66l</param>
    <param name="icudata.path"></param>
  <!-- n="cldr.version" ERROR: U_MISSING_RESOURCE_ERROR -->
  <!-- n="tz.version" ERROR: U_MISSING_RESOURCE_ERROR -->
```

I didn't have time to look into it more though. I'll try to look more this weekend. (Its late here, so I probably made a silly mistake somewhere...).

**Comment by jefgen** [comment]
Okay, some good news... It looks like the `U_MISSING_RESOURCE_ERROR` that was I seeing with the `icuinfo` program was simply due to my build environment being in a bad state.

Doing a clean checkout and rebuilding works now.

I'm going to open up a separate pull-request with the extra commits. However, I will keep your original commit so that you get credit for it. One of the reasons for the separate PR is that I had to slightly edit your commit message to add ICU-20322 in front of the message. (I'll tag you on the PR as well).

Thanks again for your PR, and for continuing to check up on this as well. :)

**Comment by vtorri** [comment]
thank you for your work :-)

**Comment by jefgen** [comment]
Hello @vtorri, The changes in PR #975 have been merged to `master` and should be part of the upcoming version 67.1 release of ICU.

Since that PR includes the commit from this PR, would you be okay with closing this PR?

Thanks!

**Comment by vtorri** [comment]
i  have just tested master and it works, so closing it
thank  you !

**Pull request closed without merging**
