### PR TITLE
ICU-22718 backport Export disallowed/ignored UTS 46 data for ICU4X

### PR DESCRIPTION
**Pull request by hsivonen**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22718
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Hi @roubert I see the MSYS CI check failing here. Can you please cherry-pick your fix for that to the maint/maint-75 branch?

**Review by sffc — APPROVED** [review]
It is a clean pick of 398890853d4937e8ea886d44776edb2cc49f1081

**Comment by roubert** [comment]
> Hi @roubert I see the MSYS CI check failing here. Can you please cherry-pick your fix for that to the maint/maint-75 branch?

PR #3011

**Comment by markusicu** [comment]
> > Hi @roubert I see the MSYS CI check failing here. Can you please cherry-pick your fix for that to the maint/maint-75 branch?
> 
> PR #3011

... and merged. @hsivonen please rebase past that.

**Comment by hsivonen** [comment]
Rebased.

**Pull request merged**
