### PR TITLE
ICU-22730 Fix Japanese extended year int32 overflow

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22730
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by FrankYFTang** [comment]
This PR is not yet ready.

**Comment by FrankYFTang** [comment]
Please review. This int32_t overflow issue is not too important for 75.1 but we should fix it sooner than later.

**Review by mihnita — APPROVED** [review]

**Comment by richgillam** [comment]
You already merged this, but I looked at it and it looked good to me too.

**Comment by sffc** [comment]
Should this be cherry-picked to the maintenance branch?

**Comment by FrankYFTang** [comment]
> Should this be cherry-picked to the maintenance branch?

I do not think this is important enough for cherrypick.

**Pull request merged**
