### PR TITLE
ICU-22143 Increase COMPACT_MAX_DIGITS from 15 to 20, needed for new ja data

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22143
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

Well this indeed turned out to be very straightforward, just increasing the value of the constant; then everything else was handled (including locales that do not have data that covers all the way up to COMPACT_MAX_DIGITS). Added tests for ja.

This will be useful to have back in the ICU4J libs in CLDR (e.g. for chart generation), will update those soon.

### CODE REVIEW

**Comment by pedberg-icu** [comment]
@sffc @macchiati This should be a very easy review...thanks

**Review by sffc — CHANGES_REQUESTED** [review]
Please undo the change from [#2176](https://github.com/unicode-org/icu/pull/2176) because the assertion did its job of alerting us that there was a problem. Without the assertion we may never know that there is a problem.

**Comment by pedberg-icu** [comment]
> Please undo the change from [#2176](https://github.com/unicode-org/icu/pull/2176) because the assertion did its job of alerting us that there was a problem. Without the assertion we may never know that there is a problem.

I am not going to just undo the change from #2176 because (a) the asset was in the wrong place, after we would already have had a crash from writing past an array boundary, and (b) I strongly believe we should not have asserts in production code, especially for conditions that do not cause a fatal problem with the operation of ICU (and this condition does not rise to that level). I agree we should have some kind of notification that there is an issue; do you have a suggestion for another more benign kind of notification?

**Comment by sffc** [comment]
I think a debug assertion is the right behavior. `U_ASSERT` is a debug assertion.

**Comment by sffc** [comment]
A unit test is also fine, but more work.

**Comment by pedberg-icu** [comment]
> I think a debug assertion is the right behavior. `U_ASSERT` is a debug assertion.

OK, I can restore the U_ASSERT for C The Java assert is not necessarily debug-only, depends on the runtime and/or other parameters. In any case, we only need one of these to check the data, and it is probably more useful in ICU4C since that is where we first check the data.

**Comment by pedberg-icu** [comment]
@sffc OK restored the U_ASSERT in a better place, PTAL, thanks.

**Review by sffc — APPROVED** [review]

**Pull request merged**
