### PR TITLE
ICU-22532 Improve commit checker instructions

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22532
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Ready to set an assignee and reviewers?

**Review by markusicu — APPROVED** [review]
rslgtm

**Comment by sffc** [comment]
Changed to ICU-22532 since the RC is already tagged.

**Review by markusicu — APPROVED** [review]

**Comment by sffc** [comment]
Force-pushed to bump CI. When it passes please feel free to merge

**Pull request merged**
