### PR TITLE
ICU-20528 Fill in testdata/rules.mk when there is no Python.

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20528
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
If you want to require Python when running make install, then yeah, we can make configure exit with nonzero exit code.

The problem I'm trying to fix is to get "make install" to work without Python.  The only problem was that the file data/testdata/Makefile includes data/testdata/rules.mk, which fails when the latter file does not exist.  The "install" target in that Makefile is a no-op.

**Comment by srl295** [comment]
@sffc the question is if @jazkal ’s case would have eventually succeeded with this PR. Would a correct `make install` occur? If so, then this is OK.

**Comment by sffc** [comment]
> @sffc the question is if @jazkal ’s case would have eventually succeeded with this PR. Would a correct `make install` occur? If so, then this is OK.

I believe this to be the case based on my local testing.  I disabled Python by removing the AC_CHECK_PROG earlier in the file, and I set a temp directory as the `--prefix`.  I then ran `make install` and it appears to have succeeded.

**Comment by srl295** [comment]
@sffc this probably makes for an important known issues for 64.1…

**Comment by sffc** [comment]
What does the "cherry-pick" tag mean?

**Comment by srl295** [comment]
@sffc doesn't it mean "this needs to be cherry picked back to master"?

**Comment by sffc** [comment]
If the commit goes onto maint/maint-64, then it's assumed it should be merged back to master at some point in the near future.  I changed the description of the label to make it say that it should annotate PRs that themselves are cherry-picks.

**Pull request merged**
