### PR TITLE
ICU-22402 Add support in ICU and in the CLDR-to-ICU tool for the new …

### PR DESCRIPTION
**Pull request by richgillam**
…nativeSpaceReplacement and parameterDefault

resources for PersonNameFormatter in CLDR.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22402
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by pedberg-icu — APPROVED** [review]
Excellent!

**Comment by pedberg-icu** [comment]
There is known issue with the contents of  icu4j/maven-build/extract-data-files.sh having been deleted, Rich is investigating. Not ready to approve just yet.

**Comment by richgillam** [comment]
> There is known issue with the contents of icu4j/maven-build/extract-data-files.sh having been deleted, Rich is investigating. Not ready to approve just yet.

I think the "empty file" thing was a weird quirk in GitHub's UI, but I went ahead and reverted my change to `extract-data-files.sh`.  The change was just a change to the file's permissions that I was led to do by following the wrong set of instructions.  The file no longer shows in the list of changed files for the PR.  Hopefully that straightens things out...

**Review by pedberg-icu — APPROVED** [review]
Problems fixed, re-approving

**Pull request merged**
