### PR TITLE
ICU-22404 Unicode 15.1 data 20230811

### PR DESCRIPTION
**Pull request by markusicu**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22404
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by richgillam — APPROVED** [review]

**Comment by markusicu** [comment]
After working with the Unicode properties & algorithms group, we have a UTS46 spec change that keeps capital sharp s mapping to ss in transitional processing. I updated IdnaTestV2.txt, and the UTS46Test now passes.

**Review by eggrobin — DISMISSED** [review]
I’ll look at switching grapheme segmentation to InCB once that’s merged.

**Review by richgillam — DISMISSED** [review]

**Comment by markusicu** [comment]
Tests seem happy, except one that regenerates the data and complains that unihan.icu differs. Weird.
I will regenerate, test, and squash.

**Review by richgillam — APPROVED** [review]

**Comment by markusicu** [comment]
> I’ll look at switching grapheme segmentation to InCB once that’s merged.

We don't yet have an API nor UnicodeSet support for InCB or some of the other new properties.

Also, @macchiati noted that CLDR is about to add at least one more script to the Aksara set, so we need to find a way to keep some of the old mechanism alive -- I guess using a union of InCB=xyz with what we need for the new scripts.

**Comment by eggrobin** [comment]
> we need to find a way to keep some of the old mechanism alive 

Good point. We will need to do that in unicodetools too.

**Pull request merged**
