### PR TITLE
ICU-22635 Avoid integer-overflow for invalid large UChar32

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22635
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Would you mind fixing the typo in the commit message?

**Comment by FrankYFTang** [comment]
> Would you mind fixing the typo in the commit message?

done

**Comment by FrankYFTang** [comment]
PTAL

**Review by richgillam — APPROVED** [review]
LOKTM

**Pull request merged**
