### PR TITLE
ICU-20769 refactor UResourceBundle.fResData & init_resb_result()

### PR DESCRIPTION
**Pull request by markusicu**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-20769
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
@jefgen could you please take a look at the MSVC compiler errors that I have been getting for a couple of commits now? They are all the same; for example:
```
icu4c\source\common\uresbund.cpp#L1259
icu4c\source\common\uresbund.cpp(1259,0): Error C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data
```
but the line that it's complaining about is one that I have not changed, and I don't see any `size_t` there:
```
ures_appendResPath(resB, RES_PATH_SEPARATOR_S, 1, status);
```
I don't understand...

FYI:
```
#define RES_PATH_SEPARATOR_S   "/"
```

**Comment by jefgen** [comment]
> @jefgen could you please take a look at the MSVC compiler errors that I have been getting for a couple of commits now? 

This one is rather odd... I end up getting the error on a different line number when building locally compared to the CI build logs.

This is the error reported in the CI builds:
```
##[error]icu4c\source\common\uresbund.cpp(1269,89): Error C4267: 'argument': conversion from 'size_t' to 'int32_t', possible loss of data
```

And you're quite right, the line that it is complaining about seems fine:

```c++
ures_appendResPath(resB, RES_PATH_SEPARATOR_S, 1, status);
```

However, building locally, I get an error on a **different line number** though -- which makes more sense.

It is complaining about this line:
https://github.com/unicode-org/icu/blob/8570f73fff2254d5b62cf1be0ce443a94ce16d3e/icu4c/source/common/uresbund.cpp#L1257

Adding the following cast makes it happy, and fixes the build (locally) for me:

```diff
    if(containerResPath != resB->fResPath) {
-      ures_appendResPath(resB, containerResPath, uprv_strlen(containerResPath), status);
+     ures_appendResPath(resB, containerResPath, static_cast<int32_t>(uprv_strlen(containerResPath)), status);
    }
```

**Comment by markusicu** [comment]
> Adding the following cast makes it happy, and fixes the build (locally) for me:

Thank you for tracking down the correct line!
I just pushed a commit with that cast.

I had looked at the error after two or three commits, and it was always off, but I hadn't compared the commit IDs with the latest one... I wish that the build bot didn't just print the line number but also the actual line contents.

**Comment by jefgen** [comment]
> I wish that the build bot didn't just print the line number but also the actual line contents.

This made me curious... I also have often wished that MSVC would output the line in question (similar to GCC/Clang) when it hits an error. So I went looking through the documentation and it turns out that MSVC (somewhat recently) added a new config option which will do just that.

I'll file a follow-up ticket to enable this.

**Review by richgillam — DISMISSED** [review]
I went through this commit by commit.  Most of the commits were pretty straightforward and looked like big improvements.  A couple were more complicated and the way GitHub rendered the diffs made it harder to tell what was going on.  But from the descriptions, I like what you're trying to do here, and if the unit tests and other CI checks are all passing, which I presume they are, I'd say you're good to go.

I'm going to start trying to rebase my changes for ICU-20992 on top of this stuff, and I think that's where we'll really know if we're getting somewhere.  If I run into trouble with that, I'll let you know.  If you want to wait to land this until I know it's working, great.  If you'd rather go ahead and land now and fix potential problems later (maybe with me rolling them into my PRs), that's fine with me too.

**Comment by markusicu** [comment]
> Hooray! The files in the branch are the same across the force-push.

squashed, please re-approve

**Review by richgillam — APPROVED** [review]

**Comment by markusicu** [comment]
Wow, that was fast re-approval! :-)
I will wait for a few build bots, just in case.

**Comment by markusicu** [comment]
still waiting for required "CI" to finish...

**Pull request merged**
