### PR TITLE
ICU-21348 tz database 2020c updates

### PR DESCRIPTION
**Pull request by yumaoka**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21348
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
rslgtm

**Comment by markusicu** [comment]
- conflict in icutzdata.jar
- please accept the ticket
- otherwise ready to merge?

**Comment by yumaoka** [comment]
Rebased and force-pushed to resolve binary conflict.
Please approve this again.

**Review by markusicu — APPROVED** [review]
rslgtm

**Pull request merged**
