### PR TITLE
ICU-22012 Add more Japanese words into the dictionary

### PR DESCRIPTION
**Pull request by allensu05**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22012
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by FrankYFTang** [comment]
We discuss this in ICUTC last Th. Peter was on vacation and I express the need for Peter to take a look at this first.

**Review by pedberg-icu — DISMISSED** [review]

**Comment by FrankYFTang** [comment]
@pedberg-icu PTAL

**Review by pedberg-icu — APPROVED** [review]
Mostly these are additions for o-xxxx or go-xxxx, plus a few kanji phrases. They seem fine to me, and beneficial for our usage.

**Comment by allensu05** [comment]
@pedberg-icu
It seems that ICU keeps checking code.
I've fixed the conflict again. Could you help review it?
Thanks

**Review by pedberg-icu — APPROVED** [review]

**Review by FrankYFTang — APPROVED** [review]

**Pull request merged**
