### PR TITLE
ICU-21654 Fix skeleton output for rounding increment

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21654
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by FrankYFTang** [comment]
could you also add those cases I put in https://unicode-org.atlassian.net/browse/ICU-21654 to your test?

**Comment by sffc** [comment]
> could you also add those cases I put in https://unicode-org.atlassian.net/browse/ICU-21654 to your test?

on it

**Comment by sffc** [comment]
The output for your test in my branch is:

```
Precision::increment(0.05000).withMinFraction(1) 'precision-increment/0.05'
Precision::increment(0.50000).withMinFraction(1) 'precision-increment/0.5'
Precision::increment(5.00000).withMinFraction(1) 'precision-increment/5.0'
Precision::increment(50.00000).withMinFraction(1) 'precision-increment/50.0'
Precision::increment(500.00000).withMinFraction(1) 'precision-increment/500.0'
Precision::increment(5000.00000).withMinFraction(1) 'precision-increment/5000.0'
Precision::increment(50000.00000).withMinFraction(1) 'precision-increment/50000.0'
Precision::increment(500000.00000).withMinFraction(1) 'precision-increment/500000.0'
Precision::increment(0.05000).withMinFraction(2) 'precision-increment/0.05'
Precision::increment(0.50000).withMinFraction(2) 'precision-increment/0.50'
Precision::increment(5.00000).withMinFraction(2) 'precision-increment/5.00'
Precision::increment(50.00000).withMinFraction(2) 'precision-increment/50.00'
Precision::increment(500.00000).withMinFraction(2) 'precision-increment/500.00'
Precision::increment(5000.00000).withMinFraction(2) 'precision-increment/5000.00'
Precision::increment(50000.00000).withMinFraction(2) 'precision-increment/50000.00'
Precision::increment(500000.00000).withMinFraction(2) 'precision-increment/500000.00'
Precision::increment(0.05000).withMinFraction(3) 'precision-increment/0.050'
Precision::increment(0.50000).withMinFraction(3) 'precision-increment/0.500'
Precision::increment(5.00000).withMinFraction(3) 'precision-increment/5.000'
Precision::increment(50.00000).withMinFraction(3) 'precision-increment/50.000'
Precision::increment(500.00000).withMinFraction(3) 'precision-increment/500.000'
Precision::increment(5000.00000).withMinFraction(3) 'precision-increment/5000.000'
Precision::increment(50000.00000).withMinFraction(3) 'precision-increment/50000.000'
Precision::increment(500000.00000).withMinFraction(3) 'precision-increment/500000.000'
Precision::increment(0.05000).withMinFraction(4) 'precision-increment/0.0500'
Precision::increment(0.50000).withMinFraction(4) 'precision-increment/0.5000'
Precision::increment(5.00000).withMinFraction(4) 'precision-increment/5.0000'
Precision::increment(50.00000).withMinFraction(4) 'precision-increment/50.0000'
Precision::increment(500.00000).withMinFraction(4) 'precision-increment/500.0000'
Precision::increment(5000.00000).withMinFraction(4) 'precision-increment/5000.0000'
Precision::increment(50000.00000).withMinFraction(4) 'precision-increment/50000.0000'
Precision::increment(500000.00000).withMinFraction(4) 'precision-increment/500000.0000'
Precision::increment(0.05000).withMinFraction(5) 'precision-increment/0.05000'
Precision::increment(0.50000).withMinFraction(5) 'precision-increment/0.50000'
Precision::increment(5.00000).withMinFraction(5) 'precision-increment/5.00000'
Precision::increment(50.00000).withMinFraction(5) 'precision-increment/50.00000'
Precision::increment(500.00000).withMinFraction(5) 'precision-increment/500.00000'
Precision::increment(5000.00000).withMinFraction(5) 'precision-increment/5000.00000'
Precision::increment(50000.00000).withMinFraction(5) 'precision-increment/50000.00000'
Precision::increment(500000.00000).withMinFraction(5) 'precision-increment/500000.00000'
Precision::increment(0.05000).withMinFraction(6) 'precision-increment/0.050000'
Precision::increment(0.50000).withMinFraction(6) 'precision-increment/0.500000'
Precision::increment(5.00000).withMinFraction(6) 'precision-increment/5.000000'
Precision::increment(50.00000).withMinFraction(6) 'precision-increment/50.000000'
Precision::increment(500.00000).withMinFraction(6) 'precision-increment/500.000000'
Precision::increment(5000.00000).withMinFraction(6) 'precision-increment/5000.000000'
Precision::increment(50000.00000).withMinFraction(6) 'precision-increment/50000.000000'
Precision::increment(500000.00000).withMinFraction(6) 'precision-increment/500000.000000'
Precision::increment(0.05000).withMinFraction(7) 'precision-increment/0.0500000'
Precision::increment(0.50000).withMinFraction(7) 'precision-increment/0.5000000'
Precision::increment(5.00000).withMinFraction(7) 'precision-increment/5.0000000'
Precision::increment(50.00000).withMinFraction(7) 'precision-increment/50.0000000'
Precision::increment(500.00000).withMinFraction(7) 'precision-increment/500.0000000'
Precision::increment(5000.00000).withMinFraction(7) 'precision-increment/5000.0000000'
Precision::increment(50000.00000).withMinFraction(7) 'precision-increment/50000.0000000'
Precision::increment(500000.00000).withMinFraction(7) 'precision-increment/500000.0000000'
```

Do you want me to convert that to an actual test (with assertions), or are you satisfied if the output is as you expect?

**Comment by FrankYFTang** [comment]
> Do you want me to convert that to an actual test (with assertions), or are you satisfied if the output is as you expect?

Could you add those "cases" w/ correct assertion (which I was not sure 100% what is the expecation should be when I wrote my test code last time)

**Comment by FrankYFTang** [comment]
so... was the java code correct before so you don't need to change any java impl files? Please also add those cases with assertion to Java

**Comment by sffc** [comment]
I added the test.

**Review by FrankYFTang — APPROVED** [review]
thanks for adding the test.

**Comment by sffc** [comment]
Squashed; need another approval

**Review by FrankYFTang — APPROVED** [review]

**Pull request merged**
