### PR TITLE
ICU-20886 Implement trailingZeroDisplay

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20886
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [x] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
@markusicu PTAL at unumberformatter.h.  I couldn't hide the `@draft` enum inside of `U_HIDE_DRAFT_API` because it is used as a private field of the non-draft struct `Precision`.  Not sure how to make the CI tool happy.  Advice?

**Comment by markusicu** [comment]
> U_HIDE_DRAFT_API

In such a case you should be able to use `U_FORCE_HIDE_DRAFT_API`. It hides from the test but not from normal compilation.

**Review by markusicu — COMMENTED** [review]
looks plausible, just needs API discussion, force-hide guard, and squashing

**Review by markusicu — COMMENTED** [review]
lgtm pse squash

**Comment by sffc** [comment]
There are merge conflicts originating from #1598; I will address those soon by rebasing and squashing

**Comment by sffc** [comment]
I resolved the merge conflicts.  Still good to squash?

**Review by markusicu — DISMISSED** [review]
still +1 AFAICT

**Comment by sffc** [comment]
@mihnita Do you have feedback on this? It was originally your suggestion.

**Review by markusicu — APPROVED** [review]

**Pull request merged**
