### PR TITLE
ICU-20439 64 BRS, integrate CLDR release-35-alpha3 (superseded)

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20439
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

There may be another one or two CLDR data fixes after this, but this should at least be most of the post RC fixes.

### CODE REVIEW

**Comment by sffc** [comment]
Data file changes LGTM, but PTAL at what's wrong with the Java tests

**Comment by pedberg-icu** [comment]
> Data file changes LGTM, but PTAL at what's wrong with the Java tests

Seems to be some kind of resource access issue, once the problem starts all tests are failing. I am trying to re-run the tests.

**Comment by sffc** [comment]
I pressed the restart button on Travis

**Comment by sffc** [comment]
Looks like both builds failed again even with a re-run.  These builds are passing on other PRs today.  So there is probably something wrong with jar file in this PR.

**Comment by pedberg-icu** [comment]
> Looks like both builds failed again even with a re-run. These builds are passing on other PRs today. So there is probably something wrong with jar file in this PR.

OK, since there are new changes in CLDR perhaps I will tag CLDR release-35-alpha4 and start over. I was also waiting for PR-527 to merge in because that will also force regenerating the data jars...

**Pull request closed without merging**
