### PR TITLE
ICU-11276 Apply the approximately pattern inside of the unit string.

### PR DESCRIPTION
**Pull request by sffc**
One small improvement I noticed.

##### Checklist

- [x] Issue filed at https://unicode-org.atlassian.net :  ICU-______
- [x] Update PR title to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
@macchiati Thoughts on this?

This PR makes the modifiers (affixes) applied in the following order, from inner to outer:

1. Inner (e.g., scientific notation)
2. Middle (the primary pattern)
3. Approximately
4. Outer (e.g., the measure unit)

This makes the approximately sign appear adjacent to the number when a unit is used.  However, this does not work for currency ISO codes.  With this ordering, we get:

~GBP 1.00

A better output might be:

GBP ~1.00

We could get something like that by moving the approximately modifier above the middle modifier.  However, this would break strings with a single currency symbol.  We would get:

$~1.00

With the current solution, we get:

~$1.00

Currency spacing also gets interesting.  For the GBP example, what I actually end up getting if I switch the order of approximately and middle is:

GBP~1.00

This happens because the currency space is added only if it is adjacent to a number, but now there's an approximately sign there, not a number, so no extra space is added.

**Comment by macchiati** [comment]
Longer term, we might add some more structure so that the vetters can control some of these features. But for the current situation:

Most languages have picked a ~ sign or something closely related. https://www.unicode.org/cldr/charts/34/by_type/numbers.number_formatting_patterns.html#39bebc189a5828a2

approximately
~ {0}	·et·
~{0}	·all·others·
≈{0}	·be· ·de· ·fr· ·ka· ·ru· ·sq·
約 {0}	·ja·

We should have @yumaoka look over the Japanese case.

Where the approximately sign and the unit are on opposite sides, no problem.
~32 USD
~32 kg

It appears that in very few languages does a regular unit (eg km) come before the number; slightly more common in the longer form. However, it is quite common for the currency unit/symbol to come before the number. So it looks like the main issue will be the currency + approx. sign. (Of course, we don't want the others to look bad either, but just in terms of focus right now.)

So as to your question. I googled "$~1.00" vs "~$1.00", and the results match my intuitions, that the most common form is:

$~1.00

Note that while I think Google devalues leading ~, the first page results mostly contained ~. I was not able to get results for "GBP ~1.00" vs "GBP~1.00" vs  "~GBP1.00" vs "~GBP 1.00", however. I'm guessing that ~ in that context is 

What looks right to me would be to bind the ~ sign more closely than a symbol, but less closely than a spelled out unit. That might be hard to do, but as a fallback, having ~ bind more closely than both in this release is probably the best choice.

~$1.00
GBP ~1.00

I would favor treating the ~ as a digit in that case in terms of spacing away from the currency. That's in terms of the outcome: the internal ways to do that can differ. I don't think this is a showstopper for the release, but I think it is less confusing.

As I said above, we should talk more about a more nuanced approach in the future.

**Comment by sffc** [comment]
Thanks for the comments.  The reason why currencies are a little bit harder is because currency formats come from Excel-style patterns, whereas unit formats come from MessageFormat-style patterns.

Currency: `¤0.00` and `¤¤0.00`
Unit: `{0} meters` (or equivalent)

The approximately sign is MessageFormat-style: `~{0}`

What's easy to say is that the approximately pattern is unconditionally applied either *after the unit* (this is what is on trunk currently), *between currency and unit* (this is what this PR does), or *before currency*.  Anything more granular than that is getting murky.  Here are the three options:

*Option 1:*

    ~$1.00
    ~GBP 1.00
    ~long unit 1.00

*Option 2:*

    ~$1.00
    ~GBP 1.00
    long unit ~1.00

*Option 3:*

    $~1.00
    GBP~1.00
    long unit ~1.00

I interpret your comment here to mean you prefer Option 3:

> That might be hard to do, but as a fallback, having ~ bind more closely than both in this release is probably the best choice.

If we did Option 3 and also want to add a space between GBP and the `~`, the most correct way to do that would be to modify the currency spacing data in root.xml.  I don't think I want to do this at this point in the release cycle.  Thoughts?

Another heuristic we can do, similar to RangeCollapse.AUTO, could be to look at the length of the currency symbol, apply inside if it is longer than 1 code point long, and apply outside if it is exactly 1 code point long.

**Comment by sffc** [comment]
Since today is the code freeze, I am merging the PR, which implements Option 2, and I filed an issue to follow up:

https://unicode-org.atlassian.net/browse/ICU-20163

**Comment by macchiati** [comment]
Agree that option 2 is the best for now; that we need more flexibility to get something like option B in the new ticket (plus better structured CLDR data to drive it).

**Pull request merged**
