### PR TITLE
ICU-21814 Fix small typos in docs/userguide

### PR DESCRIPTION
**Pull request by jbrianceau**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21814
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by sven-oly** [comment]
Thanks for fixing these typos!

**Comment by markusicu** [comment]
Hi @jbrianceau -- the changes look good, but we are preparing for the ICU 71 release and are between branches right now.

Could you please either redirect these changes to the `maint/maint-71` branch, or else change the PR title and commit message to using ICU-21959 for ICU 72?

**Comment by jbrianceau** [comment]
> Hi @jbrianceau Julien Brianceau FTE -- the changes look good, but we are preparing for the ICU 71 release and are between branches right now.
> 
> Could you please either redirect these changes to the `maint/maint-71` branch, or else change the PR title and commit message to using [ICU-21959](https://unicode-org.atlassian.net/browse/ICU-21959) for ICU 72?

Hi @markusicu, sure I've just updated this PR's base branch to `maint/maint-71`.

Are changes made in `maint/maint-71` automatically reported to `main` or do I need to create another PR to add this small fix in `main` as well? (using ICU-21959)

**Comment by markusicu** [comment]
> Hi @markusicu, sure I've just updated this PR's base branch to `maint/maint-71`.

Merci beaucoup!

> Are changes made in `maint/maint-71` automatically reported to `main` or do I need to create another PR to add this small fix in `main` as well?

No need. We will merge the whole maint/maint-71 branch onto main after the release of ICU 71 in a couple of weeks.

**Pull request merged**
