### PR TITLE
ICU-21508 Rename 'master' to 'main' in docs, maven files, scripts, etc

### PR DESCRIPTION
**Pull request by hugovdm**
This PR touches links to the following repositories: icu-data icu-docs cldr-staging cldr.

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21508
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [X] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — COMMENTED** [review]
changes lgtm

Question/curious: Are there still uses of "master" in the repo that you are *not* changing, such as for non-CLDR/ICU repo links or other uses not related to git repos?

**Comment by hugovdm** [comment]
(done). The word also shows up in a few other contexts in general text, unrelated to branch names. And icu-docs has ICU_collation_design.htm which talks about "master" and "slave" and could do with a rewrite, but that's unrelated to the branch rename.

**Comment by hugovdm** [comment]
I'm squashing. The new edits were e2ed3cb - the initial commit was 587ab67.

**Review by markusicu — APPROVED** [review]
lgtm

Please don't merge until we have "green light" in the meeting.

**Pull request merged**
