### PR TITLE
ICU-21451 Implement inverse unit handling for new consumption unit preferences in CLDR

### PR DESCRIPTION
**Pull request by hugovdm**
- [X] C++ consumption case fixed
- [X] Java changes made, untested
- [x] Correctly update icudata.jar, test the fixes
- [X] *File a ticket for:* Generalize for all inverse units, not just consumption

Fixes: https://github.com/icu-units/icu/issues/124

##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21451
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [X] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by hugovdm** [comment]
Needing to update JAR files. I look at icu4c/source/data/icu4j-readme.txt for instructions.

```
$ export icu4c_root=~/git/icu2/icu4c
$ export icu4j_root=~/git/icu2/icu4j
$ which jar
/usr/bin/jar
$ cd $icu4c_root/source ; ICU_DATA_BUILDTOOL_OPTS=--include_uni_core_data ./runConfigureICU Linux
$ make
$ export icu4c_build=$icu4c_root/source
$ cd $icu4c_build/data
$ make JAR=/usr/bin/jar ICU4J_ROOT=$icu4j_root icu4j-data-install
$ cd $icu4j_root
$ ant main

```

**Comment by hugovdm** [comment]
I thought I had Java generally working a couple of commits ago. :-/

**Comment by hugovdm** [comment]
Trying jar rebuild again, with a "make clean" and full rebuild - currently with this runConfigureICU command-line:

ICU_DATA_BUILDTOOL_OPTS=--include_uni_core_data ./runConfigureICU --enable-debug --disable-release Linux --disable-layoutex

**Comment by hugovdm** [comment]
(Another jar file rebuild might be necessary after #1545 is merged...)

**Review by sffc — DISMISSED** [review]

**Comment by hugovdm** [comment]
Squashed!

**Review by sffc — APPROVED** [review]

**Pull request merged**
