### PR TITLE
ICU-21462 ICULocaleService.java has a race condition

### PR DESCRIPTION
**Pull request by grhoten**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21462
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

I'm reordering the assignment that gets into this double check synchronized block to be the last step within the block. We want to avoid a scenario where loc is assigned to fallbackLocale before returning the fallbackLocaleName from this function.

### CODE REVIEW

**Comment by grhoten** [comment]
Good point. Apparently my default email address was used when checking this out. I'll have to fix that.

**Comment by jefgen** [comment]
Looks like the CLA checker is happier now. :)

**Comment by markusicu** [comment]
@yumaoka looks ok? Making it work with the before-synchronized `if` in the double-checked locking?

Besides that, does it make sense to use `==` for the locales? Should we not use Locale.equals or Objects.equals?

**Comment by yumaoka** [comment]
>Besides that, does it make sense to use == for the locales? Should we not use Locale.equals or Objects.equals?

ULocale instance is immutable and ULocale#getDefault() returns a singleton. ULocale#getDefault() may return a new ULocale instance when ULocale#setDefault(ULocale) is called. If fallbackLocale is always initialized with ULocale#getDefault(), then `==` makes sense with the current implementation. However, ULocale#equals(Object) is supposed to check object's equality, ULocale#equals(Object) should not have any overhead. I don't think ULocale#getDefault() returning a singleton object is an API contract, so I prefer equals() method over `==` (in this code `!=`).

This code uses synchronize(this), so fallbackLocale / fallbackLocaleName are guarded by the synchronized block. However, when ULocale.setDefault(ULocale) is called between `fallbackLocaleName = loc.getBaseName()` and `fallbackLocale = loc`, then I think it will introduce inconsistent state. So I'm not sure if the fix really resolves the problem. I'll carefully look at this again tomorrow.

**Comment by yumaoka** [comment]
OK - I now understand the problematic case.

Thread 1 enters synchronized block, updating fallbackLocale.
Thread 2 evaluate `if (loc != fallbackLocale)` outside of the synchronized block, then found `loc == fallbackLocale` .
Thread 2 returns fallbackLocaleName before Thread 1 is updating fallbackLocaleName in the synchronized block.

**Review by yumaoka — APPROVED** [review]
LGTM.

**Review by markusicu — APPROVED** [review]
lgtm

**Pull request merged**
