### PR TITLE
ICU-21416 Fix markdown formatting in userguide/strings

### PR DESCRIPTION
**Pull request by pxeger**
Fix some broken markdown formatting in `userguide/strings/index.md`.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21416
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [x] Documentation is changed or added

### CODE REVIEW

**Comment by echeran** [comment]
Hi, thanks for the fix! Can you 2 little things (according to our [PR guidelines](http://site.icu-project.org/repository/gitdev#TOC-Trivial-changes)), and I can approve?

1. put the Jira ticket number `ICU-21416` at the beginning of the commit message
1. update the PR description's checklist's first item with that ticket number (ICU-21416)?

(Or alternatively, if it's easier and you want to allow updates on your PR branch from other people, I can do that for you.)

**Comment by pxeger** [comment]
It seems a little excessive to require an issue number for something this trivial. But ok

**Review by echeran — DISMISSED** [review]

**Comment by echeran** [comment]
We fixed up some uncommon issues we had with our CI on the main branch. I think if you rebase, then the CI checks will pass, and that will unblock the ability to merge. Would you be okay to rebase from the latest upstream and force push?

**Comment by pxeger** [comment]
Hopefully I did that right - I've never fully understood rebasing

**Review by echeran — APPROVED** [review]

**Comment by echeran** [comment]
Looks good, thanks! Now that the checks are passing, as they should, I'll go ahead and merge on your behalf.

Yeah, learning git has been a gradual, iterative process for me. What really helped me get comfortable with rebase and reset (including reset's 3 diff modes) is to combine the use of a GUI client during those operations with making "defensive copy" branches before attempting the command. I like SourceTree on Windows and macOS, and QGit + git-cola/gitg on Linux.

**Pull request merged**
