### PR TITLE
ICU-20119 ICU 63 API promotion & change report

### PR DESCRIPTION
**Pull request by aheninger**
##### Checklist

- [x] Issue filed at https://unicode-org.atlassian.net :  ICU-20119
- [x] Update PR title to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by pedberg-icu** [comment]
1. There are many API that have misleading removed/added entries due to addition of const, for example:
- in Removed from ICU 62
compactdecimalformat.h | Format* icu::CompactDecimalFormat::clone() | StableICU 51 | (missing)
- in Promoted to stable in ICU 63
compactdecimalformat.h | Format* icu::CompactDecimalFormat::clone() const | (missing) | StableICU
in Added in ICU 63
compactdecimalformat.h | Format* icu::CompactDecimalFormat::clone() const | (missing) | StableICU 51

For these it might be good to manually add a comment (in the 62 or 63 column, or appended after) explaining what is going on.

2. There are many entries for just "#define"
- in Changed in ICU 63 (old, new)
platform.h | #define | StableICU 2.0 | Internal
umachine.h | #define | (untagged) | Internal
umachine.h | #define | (untagged) | StableICU 2.0
umachine.h | #define | StableICU 2.0 | 
- in Promoted to stable in ICU 63
umachine.h | #define | (untagged) | StableICU
utypes.h | #define | (missing) | StableICU 2.0
- in Added in ICU 63
utypes.h | #define | (missing) | StableICU 2.0

For these, need to figure out what is going on and manually either update the entry to what it should have (if missing something) or just remove it.

3. in Changed in ICU 63 (old, new)
usearch.h | enum USearchAttributeValue::USEARCH_ANY_BASE_WEIGHT_IS_WILDCARD | StableICU 2.4 | StableICU 4.4 (changed)

Is this an artifact of the tool, or an actual change, and if the latter, why? Maybe need an explanatory note.

4. In Promoted to stable in ICU 63 and Added in ICU 63
uobject.h | #define U_NO_THROW | (missing) | StableICU 4.2
utypes.h | #define U_COMBINED_IMPLEMENTATION | (missing) | StableICU 2.0

Are these an artifact of the tool, or an actual change, and if the latter, why? Maybe need an explanatory note.

**Comment by srl295** [comment]
internal to preview due to #8

**Comment by aheninger** [comment]
The latest version of the change report clears the remaining problems I am aware of, by manually editing the generated html. Hopefully it's done. Generated after picking up #172, reverting the @ preview tagging. 

  - items that changed from untagged to internal are removed from the report (there were many, caused by the cleanup of Doxygen warnings with this release).
  - Fallout of renaming enum UGroupingStrategy to UNumberGroupingStrategy. Renamed items treated as changed, not as unrelated removes and adds.
  - C++ functions declared =delete are removed from the report.

**Comment by pedberg-icu** [comment]
Looks good to me now. But since I am just listed as assignee but not also as a reviewer I don't think there is anything I can do to formally approve the PR. Anyway Markus has to remove his change request.

**Pull request merged**
