### PR TITLE
ICU-21250 BRS68GA Update version numbers for 68GA and regenerate jar files

### PR DESCRIPTION
**Pull request by erik0686**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21250
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by jefgen** [comment]
FYI: I think the PR should be going into the `maint/maint-68` branch, rather than `master`.

**Comment by daniel-ju** [comment]
It seems like the full JAR files are being added, instead of using Git LFS. Do you have Git LFS configured?

**Review by daniel-ju — APPROVED** [review]

**Review by jefgen — APPROVED** [review]
Thanks!

**Comment by yumaoka** [comment]
You don't need to regenerate ICU4J data files with the change, but it's not harmful.

We somewhat agreed that deprecating the process for putting RC/Release Candidate to API doc, etc. I think I did not document this  in BRS description.

**Pull request merged**
