### PR TITLE
ICU-22633 Fix more int overflow issues in calendar

### PR DESCRIPTION
**Pull request by FrankYFTang**
Rename the int64_t version of floorDivide to floorDivideInt64 to avoid confusion and ambiguity. 

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22633
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by richgillam — DISMISSED** [review]
LOKTM...

**Review by richgillam — COMMENTED** [review]
What did you change since the last time I looked at this?

**Comment by FrankYFTang** [comment]
> What did you change since the last time I looked at this?

I add test

**Review by richgillam — APPROVED** [review]
Still LOKTM.  (That's quite a year number in that test there!)

**Pull request merged**
