### PR TITLE
ICU-22666 Update ML model to improve Japanese phrase breaking quality

### PR DESCRIPTION
**Pull request by tushuhei**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22666
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by FrankYFTang** [comment]
What is the process for you to measure the quality?
What is the measured value of quality improvement before/after this PR? 
What is the size impact of this change?
How can we make sure this change only making thing better instead of making thing worst?

**Comment by tushuhei** [comment]
> What is the process for you to measure the quality?

We measure model quality using two methods:
**F1-score on validation data:** The model must achieve an F1-score (harmonic mean of precision and recall) of at least 95% on validation data unseen during training.
**Quality test cases:** The model must pass the quality test cases defined in 
https://github.com/google/budoux/blob/main/tests/quality/ja.tsv.

> What is the measured value of quality improvement before/after this PR?

The previous model, trained solely on the [KNBC corpus](https://nlp.ist.i.kyoto-u.ac.jp/kuntt/), had issues handling edge cases not well-represented in the corpus. See: [BudouX Issues tagged with `quality`](https://github.com/google/budoux/issues?q=label%3Aquality)

To address this, we created a supplemental dataset covering reported edge cases. The updated model is trained on data from both KNBC and our supplemental dataset. We evaluate it using a test sample of reported cases; it now passes 100% of these, compared to 0% for the previous model.

We prevent overfitting by also tracking the F-value on validation data composed of a KNBC subset and our quality tests.

> What is the size impact of this change?

11.4KB → 43.9KB

> How can we make sure this change only making thing better instead of making thing worst?

Quality-wise, we ensure positive changes through the evaluation process described above. To evaluate performance impact, we need to quantify any speed degradation in the new JA model. @allensu05, could you help measure this?

**Comment by FrankYFTang** [comment]
> > What is the process for you to measure the quality?
> 
> We measure model quality using two methods: **F1-score on validation data:** The model must achieve an F1-score (harmonic mean of precision and recall) of at least 95% on validation data unseen during training. **Quality test cases:** The model must pass the quality test cases defined in https://github.com/google/budoux/blob/main/tests/quality/ja.tsv.
> 
> > What is the measured value of quality improvement before/after this PR?
> 
> The previous model, trained solely on the [KNBC corpus](https://nlp.ist.i.kyoto-u.ac.jp/kuntt/), had issues handling edge cases not well-represented in the corpus. See: [BudouX Issues tagged with `quality`](https://github.com/google/budoux/issues?q=label%3Aquality)
> 
> To address this, we created a supplemental dataset covering reported edge cases. The updated model is trained on data from both KNBC and our supplemental dataset. We evaluate it using a test sample of reported cases; it now passes 100% of these, compared to 0% for the previous model.
> 
> We prevent overfitting by also tracking the F-value on validation data composed of a KNBC subset and our quality tests.
> 
> > What is the size impact of this change?
> 
> 11.4KB → 43.9KB
> 
> > How can we make sure this change only making thing better instead of making thing worst?
> 
> Quality-wise, we ensure positive changes through the evaluation process described above. To evaluate performance impact, we need to quantify any speed degradation in the new JA model. @allensu05, could you help measure this?

so... what is the **F1-score on validation data:**  before this PR?
And what is the **F1-score on validation data:**  after this PR?

**Comment by tushuhei** [comment]
Here's the quality metrics over the validation dataset. Sorry the metric that passed 95% was Accuracy actually.

|Parser	|Accuracy	|Recall	|Precision	|F-value|
|---|---|---|---|---|
|Before	|0.960219	|0.919155	|0.876478	|0.897309|
|After	|0.971597	|0.929324	|0.927289	|0.928305|

Here's how I reproduced the results.
https://colab.research.google.com/drive/1Tyjj_0uenB_xmsBrbjx-pddzDXOMmC0p?usp=sharing

**Review by FrankYFTang — APPROVED** [review]
LGTM. In the future, please include those measured improvement and size impact into the commit description so we can justify the change. Thanks

**Pull request merged**
