### PR TITLE
ICU-22403 Uplift icuexportdata out-of-bounds fix

### PR DESCRIPTION
**Pull request by Manishearth**
Uplifts https://github.com/unicode-org/icu/pull/2470

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22403
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by Manishearth** [comment]
r? and merge? @markusicu

**Comment by markusicu** [comment]
Sorry, I don't like the mismatch of ICU tickets between the pull request and one of the commits.
Since the commits are from different tickets, could you please make two separate cherry-pick PRs?
It should work without the DISABLE_JIRA_ISSUE_MATCH.

**Comment by markusicu** [comment]
Beyond "like", this would mess up our automatic cross-referencing between PRs and tickets.

**Review by markusicu — APPROVED** [review]
lgtm tnx

**Pull request merged**
