### PR TITLE
ICU-22164 Replace switch+getType with subclass

### PR DESCRIPTION
**Pull request by FrankYFTang**
Introduce 6 new subclasses of Calendar to put the code by OOP instead of switch(getType) statements:
* internal ISO8601Calendar subclassing GregorianCalendar 
* internal EthiopicAmeteAlemCalendar subclassing EthiopicCalendar 
* internal IslamicCivilCalendar subclassing IslamicCalendar 
* internal IslamicTBLACalendar subclassing IslamicCivilCalendar
* internal IslamicUmalquraCalendar subclassing IslamicCalendar 
* internal IslamicRGSACalendar subclassing IslamicCalendar

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22164
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Frank, are you going to add more tests as Peter suggested? Peter, how much testing do you want Frank to add?

**Comment by pedberg-icu** [comment]
> Frank, are you going to add more tests as Peter suggested? Peter, how much testing do you want Frank to add?

I would be happy with verifying that a single date converts correctly from Gregorian to one of the modified calendars, and back.

**Comment by FrankYFTang** [comment]
sorry , just back from 2 weeks of vacation and 1 week of COVID sickness. I will try to add the tests this week.

**Review by richgillam — APPROVED** [review]
Didn't review in great detail, but I like what you're doing here.

**Review by pedberg-icu — DISMISSED** [review]
Looks good (thanks for adding the tests!), need to resolve file conflicts.

**Comment by FrankYFTang** [comment]
rebase and resolve the conflict. PTAL

**Review by richgillam — APPROVED** [review]
Still looks good.

**Pull request merged**
