### PR TITLE
ICU-22357 Update gb18030 mappings for the -2022 version

### PR DESCRIPTION
**Pull request by pedberg-icu**
Update ICU gb18030 converter mappings from gb18030-2005 to gb18030-2022: Cherry-pick #2430 from main to maint/maint-73 branch.

(cherry picked from commit 7f5d679a982cf8fc9308a01159a1ccb071c7b508)

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22357
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by caobaokang419** [comment]
@pedberg-icu @markusicu
 
Dear Sir，
When will this commit be merged into google android branch.

The google android icu branch commited url as following(has not found this commit yet):
https://android-review.googlesource.com/q/status:open+-is:wip+repo:platform/external/icu

We urgently need to merge this commit on the Android platform, wait for your help, thanks a lot.

**Comment by gvictor** [comment]
It's submitted into AOSP here. https://r.android.com/2611011

**Comment by pedberg-icu** [comment]
> It's submitted into AOSP here. https://r.android.com/2611011

@gvictor thanks for responding to @caobaokang419. The open-source ICU project generally, and me personally, are not directly involved with contributing to Google Android so I had no idea about schedule for that.

**Comment by caobaokang419** [comment]
@gvictor @pedberg-icu 

thanks for your help, we got the patch on google android u0 branch.

thanks again.

**Pull request merged**
