### PR TITLE
ICU-21249 integrate CLDR release 38 alpha0 to ICU trunk

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21249
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added (N/A)

This integrates into ICU master a preliminary CLDR "release 38 alpha0" which does not correspond to a CLDR repository tag, but consists of the following:
Everything in CLDR trunk through the following
```
commit 6a0389a7b2ad5b0f4863490bb27a1ce320cc85a6 (HEAD -> master, origin/master, origin/HEAD)
Author: Peter Edberg <42151464+pedberg-icu@users.noreply.github.com>
Date:   Mon Aug 31 23:47:15 2020 -0700
	CLDR-14128 revert en_001 changes for date formats, fluid-ounce-imperial as in PR-168 (#685)
```
**_except_** for the following commit:
```
commit 4116d5414204244adfaf44e830b32271aae91e4d
Author: Mark Davis <mark@macchiato.com>
Date:   Fri Aug 28 18:31:21 2020 -0700
	CLDR-12010 add plural operand. (#638)
```

The latter unincluded commit for [PR-638](https://github.com/unicode-org/cldr/pull/638) introduces for French a &lt;pluralRule count="many"&gt; which uses keyword 'e'; this is not currently handled by plural rule parsing. The following ICU ticket is to make the ICU changes necessary to roll in this CLDR change:
- [ICU-21254](https://unicode-org.atlassian.net/browse/ICU-21254) Cannot parse plural rules with 'e' for suppressed exponent

There are two other CLDR changes which **_are_** included in this integration that do not work properly with existing ICU code; I have added logKnownIssues to skip the corresponding tests until the ICU code is fixed:
- CLDR supplementalMetadata &lt;languageAlias&gt; data has changed in certain ways; for example the item that used to map "no_BOKMAL" to "nb" now maps "no_bokmal" to "nb". Frank Tang said he is already working on  a fix to handle this in [PR-1254](https://github.com/unicode-org/icu/pull/1254), corresponding to [ICU-21236](https://unicode-org.atlassian.net/browse/ICU-21236)
- CLDR French long compact decimals introduce a plural case for keyword "1", but StandardPlural cannot handle this. I have filed [21258](https://unicode-org.atlassian.net/browse/ICU-21258) to fix this.

### CODE REVIEW

**Comment by pedberg-icu** [comment]
[gitDiffVsMaster-for-CLDR-38-alpha0-integration.txt](https://github.com/unicode-org/icu/files/5154783/gitDiffVsMaster-for-CLDR-38-alpha0-integration.txt)

To facilitate review I have attached this diff of the changes in this PR (vs master branch) excluding header or Version changes, showing 707 files with "real" changes

**Comment by pedberg-icu** [comment]
[gitDiffVsMaster-for-CLDR-38-alpha0-integration.txt](https://github.com/unicode-org/icu/files/5154832/gitDiffVsMaster-for-CLDR-38-alpha0-integration.txt)

To facilitate review I have attached this diff of the changes in this PR (vs master branch) excluding header or Version changes, showing 726 files with "real" changes

**Comment by hugovdm** [comment]
- cldr-icu-readme.txt, units.txt: look good to me.
- MeasureUnit code changes, units locale data: skimmed, looked into some samples here and there, look good as far as I can tell.

**Review by hugovdm — COMMENTED** [review]
- cldr-icu-readme.txt, units.txt, number_skeletons.cpp: look good to me.
- MeasureUnit code changes, units locale data: skimmed, looked into some samples here and there, look good as far as I can tell.

**Review by hugovdm — COMMENTED** [review]
How thorough a review do you need to feel the reviewer is qualified to approve?

(I'm hoping more people chip in with their fields of expertise - but if necessary/preferred, I'm willing to get more thorough, to become comfortable with Approving myself?)

**Comment by pedberg-icu** [comment]
Yoshito agreed to do the review. Thanks Yoshito!

**Comment by pedberg-icu** [comment]
> CLDR TC agreed to drop these undesired data changes.

That will be done in a subsequent integration pass (today or tomorrow) under the following ticket: https://unicode-org.atlassian.net/browse/CLDR-14160. Should not block integration of this current PR.

**Comment by jefgen** [comment]
Quick heads up, it looks like CI builds (Travis/Azure/AppVeyor) have a test failure with the new data from CLDR.

```
   NumberPermutationTest {
      testPermutations {
      Quick mode: stopped after 1095 lines
      FAIL: Line #6 differs; got "    0%"; expected "    0\u00A0%"
      FAIL: Line #7 differs; got "    92\u00A0k%"; expected "    92\u00A0k\u00A0%"
      FAIL: Line #8 differs; got "    -0.22%"; expected "    -0.22\u00A0%"
   
      } ERRORS (3) in testPermutations (29ms) 
   } ERRORS (3) in NumberPermutationTest (29ms) 
} ERRORS (3) in NumberTest (169ms) 

-------------
| ***     FAILING TEST SUMMARY FOR:              intltest  
            testPermutations
         NumberPermutationTest
      NumberTest
   format
| *** END FAILING TEST SUMMARY FOR:              intltest
---------------
```

The test doesn't say what locale, but from taking a quick look, this is for `es_MX` in the file `numberpermutationtest.txt`

It looks like the following change might possibly conflict with the new data perhaps:
https://github.com/unicode-org/icu/commit/196d5e1182302612f851c93248c89af7677897f9#diff-5eba3f684c4d6be6eb53a8b16b452be8 (from ICU-20923).

From the test data file:
```
compact-short percent unit-width-narrow
  es-MX
    0 %
    92 k %
    -0.22 %
```

There's a U+00A0 character, so this is actually more like this:
```
compact-short percent unit-width-narrow
  es-MX
    0\u00A0%
    92\u00A0k\u00A0%
    -0.22\u00A0%
```

Should this file just be updated to remove the U+00A0?

**Comment by pedberg-icu** [comment]
Hmm. I did not see this failure even though I had rebased my branch onto master Monday night.

**Comment by sffc** [comment]
The test failure originated from #1231, which was checked in early Tuesday morning.  I fixed it in #1292.

**Pull request merged**
