### PR TITLE
ICU-22261 Remove MF2 formatter caching optimization

### PR DESCRIPTION
**Pull request by catamorphism**
The implementation was keeping a cache of FormatterFactory objects so that subsequent calls to the same formatter re-use the same object.
The problem is that this is unsafe, because
`MFFunctionRegistry::getFormatter()` returns a non-const `FormatterFactory*`; so if the caller deleted the resulting pointer, the formatter cache would contain a dangling pointer.

This optimization was added because of an ICU4J test that checked for the presence of the optimization. However, for separate reasons (making `adoptFormatter()` actually adopt its argument), this test was already removed.

The caching could be re-added later if that optimization is needed, but for now, remove it (also, no tests were checking for its presence).

No public APIs are changed.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22261
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by catamorphism** [comment]
Converted to draft because of the valgrind errors (I'll look at that on Monday).

**Comment by catamorphism** [comment]
asan/valgrind errors should be fixed now.

**Comment by catamorphism** [comment]
I'm unable to reproduce the CI failure (`clang-options-build-and-test (--enable-static)`) locally. I ran:

```
$ ../icu4c/source/runConfigureICU Linux/clang --enable-static
$ make -j -l4.5 tests
$ make check
```

with no errors. I'm not sure what's going on. I've rebased against the most recent `maint/maint-75` from upstream.

**Review by echeran — APPROVED** [review]
LGTM

**Comment by echeran** [comment]
I can't reproduce the problem either. Everything runs fine to completion, including `make check`. I'm running a Debian system, FWIW.

The [log from the failing CI job](https://github.com/unicode-org/icu/actions/runs/8514628320/job/23320688133?pr=2941#step:3:2015) looks like:
```
echo "$ZONE_INDEX_TXT_CONTENT" > ./out/tmp/zone/res_index.txt
LD_LIBRARY_PATH=../lib:../stubdata:../tools/ctestfw:$LD_LIBRARY_PATH  ../bin/makeconv -s . -d ./out/build/icudt75l -c mappings/windows-950-2000.ucm
make[1]: *** [../data/rules.mk:20237: out/build/icudt75l/brkitr/res_index.res] Segmentation fault (core dumped)
make[1]: *** Waiting for unfinished jobs....
genrb number of files: 906
number of shared strings: 5063
16-bit units for strings:  75653 = 151306 bytes
16-bit units saved:       367300 = 734600 bytes
16-bit units not saved:    16055 =  32110 bytes
genrb number of files: 510
number of shared strings: 3545
16-bit units for strings:  52676 = 105352 bytes
16-bit units saved:       109661 = 219322 bytes
16-bit units not saved:    12898 =  25796 bytes
make[1]: Leaving directory '/home/runner/work/icu/icu/icu4c/source/data'
make: *** [Makefile:153: all-recursive] Error 2
```

Any ideas, @markusicu ?

**Comment by catamorphism** [comment]
I was able to reproduce the segfault by doing:

```
$ CPPFLAGS=-fsanitize=address LDFLAGS=-fsanitize=address ../icu4c/source/runConfigureICU --enable-debug --disable-release Linux/clang --enable-static --disable-renaming --enable-tracing
$ make -j -l4.5 check
[snip]
genrb number of files: 581
make[1]: *** [../data/rules.mk:2591: out/build/icudt75b/pool.res] Segmentation fault (core dumped)
make[1]: *** Waiting for unfinished jobs....
number of shared strings: 5381
16-bit units for strings:  94725 = 189450 bytes
16-bit units saved:       270668 = 541336 bytes
16-bit units not saved:     3201 =   6402 bytes
make[1]: Leaving directory '/home/tjc/icu/build_clang_enable_static/data'
make: *** [Makefile:153: all-recursive] Error 2
```

Well, sort of, anyway -- in the line ending with "Segmentation fault (core dumped)", the file being built is different, but I'm going to assume it's a similar problem.

I'll keep investigating. (I'm running Ubuntu 23.10, btw.)

**Comment by catamorphism** [comment]
The coredumps, btw, are pretty non-useful, even though it's from a debug build. A representative one:

```
Core was generated by `../bin/genrb -s ../../icu4c/source/data/locales -d ./out/build/icudt75l/ -i ./o'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00006254883345a0 in ?? ()
(gdb) bt
#0  0x00006254883345a0 in ?? ()
#1  <signal handler called>
#2  0x00006254883345a0 in ?? ()
#3  <signal handler called>
#4  0x00006254883345a0 in ?? ()
#5  <signal handler called>
#6  0x00006254883345a0 in ?? ()
#7  <signal handler called>
#8  0x00006254883345a0 in ?? ()
#9  <signal handler called>
#10 0x00006254883345a0 in ?? ()
#11 <signal handler called>
#12 0x00006254883345a0 in ?? ()
#13 <signal handler called>
#14 0x00006254883345a0 in ?? ()
#15 <signal handler called>
#16 0x00006254883345a0 in ?? ()
#17 <signal handler called>
#18 0x00006254883345a0 in ?? ()
#19 <signal handler called>
#20 0x00006254883345a0 in ?? ()
#21 <signal handler called>
#22 0x00006254883345a0 in ?? ()
#23 <signal handler called>
#24 0x00006254883345a0 in ?? ()
#25 <signal handler called>
#26 0x00006254883345a0 in ?? ()
#27 <signal handler called>
#28 0x00006254883345a0 in ?? ()
#29 <signal handler called>
#30 0x00006254883345a0 in ?? ()
#31 <signal handler called>
#32 0x00006254883345a0 in ?? ()
#33 <signal handler called>
#34 0x0000625488349b65 in ?? ()
#35 0x0000000000000000 in ?? ()
```

**Comment by catamorphism** [comment]
Using `rr`, I was eventually able to get a more useful stack trace for the `genrb`/`gendict`/etc. crashes:

```
(rr) bt
#0  0x00006218075e9585 in __sanitizer::internal_mmap(void*, unsigned long, int, int, int, unsigned long long) ()
#1  0x00006218075eae3d in __sanitizer::MmapNamed(void*, unsigned long, int, int, char const*) ()
#2  0x00006218075f4e7c in __sanitizer::ReservedAddressRange::Init(unsigned long, char const*, unsigned long) ()
#3  0x00006218075398c1 in __sanitizer::SizeClassAllocator64<__asan::AP64<__sanitizer::LocalAddressSpaceView> >::Init(int, unsigned long) ()
#4  0x0000621807536bf1 in __asan::Allocator::InitLinkerInitialized(__asan::AllocatorOptions const&) ()
#5  0x00006218075da209 in __asan::AsanInitInternal() ()
#6  0x0000729fb64bc4ba in _dl_init (main_map=0x729fb64ef2d0, argc=10, argv=0x7ffc85905418, env=0x7ffc85905470) at ./elf/dl-init.c:122
#7  0x0000729fb64d5b70 in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
```

It looks like it's segfaulting in asan's initialization. This is still with the `maint/maint-75` branch without local changes.

I think that means that what I'm seeing locally (though also troubling) is not what's happening on CI, since the CI build that's failing is without asan. :/

**Comment by catamorphism** [comment]
To summarize what I've tried (all on Ubuntu 23.10 with clang 16.0.6):

### No asan, no debug, enable static

```
../icu4c/source/runConfigureICU  Linux/clang --enable-static
```

This **should** be the same config as the failing CI job. Couldn't reproduce the crash.

### No asan, debug, enable static

```
../icu4c/source/runConfigureICU --enable-debug --disable-release Linux/clang --enable-static
```

Also couldn't reproduce the crash.

### Asan, debug, enable static

This results in a crash in the asan initialization code as described in previous comments. Because asan crashes on startup, it's not possible to determine if `genrb` itself has any errors that would be caught by asan. (This occurs both with my branch and the upstream `maint/maint-75` branch.) (Separately, this is mysterious since CI builds run with asan, but maybe it's something in my environment.)

### Running `make tests` without parallelism

I also tried running `make tests` instead of `make -j -l4.5 tests` and still couldn't reproduce the crash.

So I'm not able to reproduce the CI error locally; the crashes I got while running with asan were a red herring. @roubert - do you have any ideas? (I see that you worked on `genrb` the most recently.)

**Comment by catamorphism** [comment]
I also filed [a JIRA ticket](https://unicode-org.atlassian.net/browse/ICU-22725) for the apparently-unrelated crashes under asan.

**Comment by catamorphism** [comment]
On the off chance it will help, I rebased off the latest `maint/maint-75` (as of right now) and force-pushed.

**Comment by catamorphism** [comment]
> > @roubert - do you have any ideas? (I see that you worked on `genrb` the most recently.)
> 
> Sorry, all changes I've ever made to genrb have been part of global refactorings, nothing particular to genrb (into which I have no particular insight).

No worries, it seems to have been just CI flakiness!

**Pull request merged**
