### PR TITLE
ICU-21730 fix nan in java

### PR DESCRIPTION
**Pull request by younies**
Closes: https://github.com/icu-units/icu/issues/132

##### Checklist

- [ ] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21730
- [ ] Required: The PR title must be prefixed with a JIRA Issue number. 
- [ ] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by sffc** [comment]
Converting to Draft until the CI is fixed.

**Comment by younies** [comment]
@sffc , this bug will open a big can of worms. Shall we consider it for future?

**Comment by sffc** [comment]
> @sffc , this bug will open a big can of worms. Shall we consider it for future?

I agree.  Your PR is going in the correct direction, but it is not high enough priority to justify this amount of change this late in the ICU cycle.  Let's punt the bug to future.

**Comment by sffc** [comment]
@younies, I suggest closing this PR and perhaps referencing it from a Jira issue for follow-up work on this subject (double in C++ vs BigDecimal in Java).

**Comment by hugovdm** [comment]
I think this PR is more related to https://github.com/icu-units/icu/issues/132 than to https://github.com/icu-units/icu/issues/131 - 132 is generally about NaN and Inf in Java, while 131 is about what we might want to do for NaN instead of taking the smallest unit preference and formatting a mixed unit with zeros for the more significant values, e.g.: "0 m, NaN cm"

**Pull request closed without merging**
