### PR TITLE
ICU-21107 Update ICU4C minimum standard version from C++11 to C++17

### PR DESCRIPTION
**Pull request by roubert**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21107
- [X] Required: The PR title must be prefixed with a JIRA Issue number.
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number.
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [X] API docs and/or User Guide docs changed or added, if applicable

ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by markusicu** [comment]
Please also look for where U_CPLUSPLUS_VERSION is defined and used. Examples:
- [definition here](https://github.com/unicode-org/icu/blob/7d3cd7cba5a08304eec8f193ef070a89dd3bd31e/icu4c/source/common/unicode/platform.h#L502) --> set it to value 17 if `__cplusplus >= 201703L` (https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html)
- [tell doxygen](https://github.com/unicode-org/icu/blob/7d3cd7cba5a08304eec8f193ef070a89dd3bd31e/icu4c/source/Doxyfile.in#L2087) to set that
- Maybe we don't currently actually use it other than checking whether it's 0 (for just C)? Let's not delete it.

**Comment by roubert** [comment]
> Please also look for where U_CPLUSPLUS_VERSION is defined and used. Examples:
> 
> * [definition here](https://github.com/unicode-org/icu/blob/7d3cd7cba5a08304eec8f193ef070a89dd3bd31e/icu4c/source/common/unicode/platform.h#L502) --> set it to value 17 if `__cplusplus >= 201703L` (https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html)
> * [tell doxygen](https://github.com/unicode-org/icu/blob/7d3cd7cba5a08304eec8f193ef070a89dd3bd31e/icu4c/source/Doxyfile.in#L2087) to set that
> * Maybe we don't currently actually use it other than checking whether it's 0 (for just C)? Let's not delete it.

Done.

**Comment by markusicu** [comment]
lgtm tnx -- but we might wait until the meeting on Thursday just so that everyone is on the same page

**Comment by roubert** [comment]
> lgtm tnx -- but we might wait until the meeting on Thursday just so that everyone is on the same page

Please merge whenever you find that the timing is right.

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Pull request merged**
