### PR TITLE
ICU-22534 ICU4J 75 frontload: API status update

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22534
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — CHANGES_REQUESTED** [review]
Please _amend_ the commit so that the commit message refers to 75 not 74.

**Comment by markusicu** [comment]
... and you also need the `ICU-22534 ` prefix on the commit message

**Comment by markusicu** [comment]
@richgillam If you have qualms about the Java PersonName etc. API, speak up now before we make it stable!

**Comment by richgillam** [comment]
> @richgillam If you have qualms about the Java PersonName etc. API, speak up now before we make it stable!

We talked about this in email.  It sounds like we really did promote this from "tech preview" to "draft" some time ago, and that having a C++ implementation isn't a prerequisite for exiting "tech preview," so I'm okay with this.  I have a small worry we might end up with slightly inconsistent C++ and Java APIs, but it'll probably be fine.

**Comment by richgillam** [comment]
I'd approve, but Markus is blocking this on fixing the commit message, and I don't want to risk removing that block.

**Review by markusicu — APPROVED** [review]

**Comment by markusicu** [comment]
> I'd approve, but Markus is blocking this on fixing the commit message, and I don't want to risk removing that block.

AFAIK Your approval would not remove my block. Only an explicit dismissal would to that.

**Pull request merged**
