### PR TITLE
ICU-21191 Fixing testtagsguards.sh

### PR DESCRIPTION
**Pull request by sffc**
Fixing bug introduced by #1196

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21191
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
As expected, Travis CI is failing, due to the script being fixed and exposing a problem.

```
*** testtagsguards.sh TMPDIR=/tmp/tmp.6RhKITG9RM
source/common/unicode/appendable.h
    @draft
    /**
     * The input is impractically long for an operation.
     * It is rejected because it may lead to problems such as excessive
     * processing time, stack depth, or heap memory requirements.
     *
     * @draft ICU 68
     */
    U_INPUT_TOO_LONG_ERROR = 31,


    /**
*** error: @draft not hidden in /tmp/tmp.6RhKITG9RM/ht-appendable.h-draft.i
```

Since Travis CI is now required, this PR cannot be checked in until said problem is fixed.

**Comment by markusicu** [comment]
> As expected, Travis CI is failing, due to the script being fixed and exposing a problem.
> ...
> Since Travis CI is now required, this PR cannot be checked in until said problem is fixed.

--> PR #1345

**Comment by sffc** [comment]
Rebased on top of master.  If the CI passes, then we should be good to check in.

**Comment by sffc** [comment]
The AppVeyor error looks unrelated:

```
make[1]: Making `check' in `toolutil'
make[2]: Entering directory '/cygdrive/c/projects/icu/icu4c/source/tools/toolutil'
make[2]: Entering directory '/cygdrive/c/projects/icu/icu4c/source/tools/toolutil'
ln -fs libicutu68.dll.a ../../lib/libicutu.dll.a
ln -fs libicutu68.dll.a ../../lib/libicutu.dll.a
ln: failed to create symbolic link '../../lib/libicutu.dll.a': File exists
make[2]: Leaving directory '/cygdrive/c/projects/icu/icu4c/source/tools/toolutil'
make[2]: *** [../../config/mh-cygwin64:108: ../../lib/cygicutu.dll] Error 1
make[2]: Leaving directory '/cygdrive/c/projects/icu/icu4c/source/tools/toolutil'
make[1]: Making `all' in `ctestfw'
make[1]: *** [Makefile:47: check-recursive] Error 2
```

**Review by markusicu — APPROVED** [review]
lgtm, thanks!

Seems to work again: Travis "c linux clang":
```
*** testtagsguards.sh TMPDIR=/tmp/tmp.2nRfViXPCZ
source/common/unicode/appendable.h
    @draft
    @deprecated
    @system
    @obsolete
source/common/unicode/brkiter.h
    @draft
    @deprecated
...
    @system
    @obsolete
source/io/unicode/ustream.h
    @draft
    @deprecated
    @system
    @obsolete
pass
The command "( cd .. && source/test/hdrtst/testtagsguards.sh )" exited with 0.
```

And yes, the AppVeyor failure is the known threading issue in cygwin make.

**Comment by markusicu** [comment]
I will merge your PR now in return, to prevent further regressions.

**Pull request merged**
