### PR TITLE
ICU-13259 Check whether ulocdata_getDelimiter works in various locales including fr_CA

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-13259
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

Original plan was to add a test to demonstrate that the reported problem no longer occurs. But in fact it does still occur, so this will need to be expanded to actually fix the problem.

### CODE REVIEW

**Comment by pedberg-icu** [comment]
Oops, need to actually call the test 🙄

**Comment by jefgen** [comment]
I think this might have been fixed by https://github.com/unicode-org/icu/pull/1399

I re-based the changes on top of the most recent master (with Frank's fix), and the tests are now all passing.

Here is the branch in my fork: https://github.com/jefgen/icu/commits/ICU-13259-addTestForDelimiters
Test results: https://dev.azure.com/ms/icu/_build/results?buildId=114703&view=results

So I think if this PR could rebased on top of the most recent master, then it could be merged and the bug resolved. :)

**Comment by pedberg-icu** [comment]
> I think this might have been fixed by #1399
> 
> I re-based the changes on top of the most recent master (with Frank's fix), and the tests are now all passing.
> 
> Here is the branch in my fork: https://github.com/jefgen/icu/commits/ICU-13259-addTestForDelimiters
> Test results: https://dev.azure.com/ms/icu/_build/results?buildId=114703&view=results
> 
> So I think if this PR could rebased on top of the most recent master, then it could be merged and the bug resolved. :)

Yes indeed, thanks, I rebased and the test passes, looks like #1399 fixed this. Removing the incomplete label.

**Review by jefgen — APPROVED** [review]
lgtm

**Comment by FrankYFTang** [comment]
Could you also add similar test to ICU4J and make sure Java do the right thing. I forget to check on Java.

**Review by FrankYFTang — APPROVED** [review]
LGTM

**Comment by FrankYFTang** [comment]
> Could you also add similar test to ICU4J and make sure Java do the right thing. I forget to check on Java.

Don't need to do in this PR. A separate PR is ok.

**Pull request merged**
