### PR TITLE
ICU-21344 merge localebuilder into resourcebundle

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21344
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [X] Tests included
- [X] Documentation is changed or added

This is to fix the dep breakage I introduced in #1422

### CODE REVIEW

**Comment by FrankYFTang** [comment]
I am not sure this work. I try to run it locally but not sure how to make it work. I blindly created this PR and push here to see would the tryBot work or not.
What I did locally:
```
~/icu/icu/icu4c/source$ ./runConfigureICU    Linux -disable-layoutex
~/icu/icu/icu4c/source$ make clean
~/icu/icu/icu4c/source$ make -j 120 tests
~/icu/icu/icu4c/source$ cd test/depstest
~/icu/icu/icu4c/source/test/deptest$./depstest.py ../.. 
```
and I got
```
Info:  group platform  does not need to depend on  PIC

Info:  group platform  does not need to depend on  ubsan

Info:  group platform  does not need to depend on  system_debug

Info:  ignoring common/umutex.o imports std::__throw_system_error(int)

Info:  ignoring common/umutex.o imports __tls_get_addr

Info:  ignoring common/umutex.o imports std::__once_call

Info:  ignoring common/umutex.o imports __once_proxy

Error: in group platform: common/putil.o imports bcmp - is this a new system symbol?
Error: in group platform: common/charstr.o imports bcmp - is this a new system symbol?
Error: in group platform: common/stringpiece.o imports bcmp - is this a new system symbol?
Error: in group platform: common/unistr.o imports bcmp - is this a new system symbol?
Info:  ignoring common/umutex.o imports std::__once_callable

Info:  group utypes  does not need to depend on  ubsan

Info:  group patternprops  does not need to depend on  PIC

Info:  group patternprops  does not need to depend on  ubsan

Error: in group resourcebundle: common/uloc.o imports bcmp - is this a new system symbol?
Error: in group ulist: common/ulist.o imports bcmp - is this a new system symbol?
Error: in group currency: common/ucurr.o imports bcmp - is this a new system symbol?
Error: in group bytestriebuilder: common/bytestriebuilder.o imports bcmp - is this a new system symbol?
Error: in group breakiterator: common/rbbidata.o imports bcmp - is this a new system symbol?
Info:  group icuplug  does not need to depend on  platform

Info:  ignoring common/unifiedcache.o imports std::__throw_system_error(int)

Error: in group collation: i18n/rulebasedcollator.o imports bcmp - is this a new system symbol?
Error: in group collation: i18n/sortkey.o imports bcmp - is this a new system symbol?
Error: in group collation: i18n/collationdatareader.o imports bcmp - is this a new system symbol?
Error: in group propsvec: common/propsvec.o imports bcmp - is this a new system symbol?
Error: in group collation_builder: i18n/collationdatabuilder.o imports bcmp - is this a new system symbol?
Info:  group formatting  does not need to depend on  floating_point

Error: in group formatting: i18n/tznames_impl.o imports bcmp - is this a new system symbol?
Error: in group formatting: i18n/dtptngen.o imports bcmp - is this a new system symbol?
Error: in group formatting: i18n/olsontz.o imports bcmp - is this a new system symbol?
Info:  group universal_time_scale  does not need to depend on  ubsan

Error: in group string_search: i18n/search.o imports bcmp - is this a new system symbol?
Info: ignored symbols:
[u'DW.ref.__gxx_personality_v0', u'__cxa_atexit', u'__cxa_bad_typeid', u'__cxa_begin_catch', u'__cxa_pure_virtual', u'__dso_handle', u'__gxx_personality_v0', u'vtable for __cxxabiv1::__class_type_info', u'vtable for __cxxabiv1::__si_class_type_info', u'vtable for __cxxabiv1::__vmi_class_type_info']
Error: There were errors, please fix them and re-run. Processing may have terminated abnormally.
```

**Comment by srl295** [comment]
Please reassign to another

**Comment by FrankYFTang** [comment]
Looks like the test is passed now 
https://travis-ci.org/github/unicode-org/icu/jobs/738104089#L13024

**Comment by sffc** [comment]
LGTM but I would like Markus to approve the changes.

**Review by sffc — APPROVED** [review]
You are adding localebuilder.cpp to a very low-level dependency group, but it is only 468 lines, which is small compared to some of the other files in that dependency group, like loclikely.cpp (1410 lines).  So I will give approval.

**Review by markusicu — APPROVED** [review]
lgtm

**Comment by FrankYFTang** [comment]
ok, the issue I have with my local build seems addressed if I run the config with Linux/gcc instead of Linux

**Pull request merged**
