### PR TITLE
ICU-20567 Use 7Zip to package Windows binaries on CI build bots

### PR DESCRIPTION
**Pull request by daniel-ju**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20567
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by daniel-ju** [comment]
I couldn't find where in the CI build `distrelease.ps1` was being run, but I tested this on my fork's `master` branch build and the build bots didn't complain.

**Comment by jefgen** [comment]
> I couldn't find where in the CI build `distrelease.ps1` was being run, but I tested this on my fork's `master` branch build and the build bots didn't complain.

Ah right, that because the script isn't yet being used as part of the CI builds yet...
I have a ticket ICU-20549 for doing that. I'll send out a PR shortly. If we can merge that one first, then if you rebase this one, we can check if the Azure CI build machines have 7Zip on them. :)

**Comment by daniel-ju** [comment]
Checked that it publishes fine with the build bots on my `master` branch!

**Comment by jefgen** [comment]
Double-checked on Linux and the zip file is much better now!

**Pull request merged**
