### PR TITLE
ICU-22220 BRS 73rc ICU4J API signature data file

### PR DESCRIPTION
**Pull request by echeran**
@yumaoka Let me know if I did this correctly. It seemed pretty straightforward. Also, I fixed some typos in the User Guide for this task, so review those changes. (I also made formatting fixes for the User Guide to stop some of the text from disappearing.)

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22220
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [X] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
rslgtm fwiw tnx

**Comment by markusicu** [comment]
@yumaoka ok if we merge this PR?

**Comment by yumaoka** [comment]
I wanted to add some extra notes in BRS instruction. At this moment, if you run `ant gatherapi` to main / HEAD, you see some warnings as below.
```
  [javadoc] Constructing Javadoc information...
  [javadoc] D:\unicode\icu\icu4j\main\classes\core\src\com\ibm\icu\text\SimplePersonName.java:159: warning - @return tag has no arguments.
  [javadoc] D:\unicode\icu\icu4j\main\classes\core\src\com\ibm\icu\text\SimplePersonName.java:217: warning - @return tag has no arguments.
  [javadoc] warning: no @deprecated tag for @internal API: com.ibm.icu.text.SimplePersonName.toString()
  [javadoc] warning: no tag for com.ibm.icu.text.PersonName.PreferredOrder.DEFAULT
  [javadoc] warning: no tag for com.ibm.icu.text.PersonName.PreferredOrder.SURNAME_FIRST
  [javadoc] warning: no tag for com.ibm.icu.text.PersonName.PreferredOrder
  [javadoc] 2 warnings
```
This is caused by inappropriate or missing API doc tags. We should fix them first before generating API signature data.

We may even include this check, and change warning to error as a part of CI build.

**Review by yumaoka — CHANGES_REQUESTED** [review]
See my comments above. We should fix API doc tagging issues first before this.

**Comment by echeran** [comment]
I rebased after the latest from upstream included @yumaoka 's fix of the API doc tagging issues (https://github.com/unicode-org/icu/commit/6ddf63ed926c7d934ffa01a1c841cec300207aae).

**Review by yumaoka — APPROVED** [review]
LGTM

**Pull request merged**
