### PR TITLE
c: add @preview

### PR DESCRIPTION
**Pull request by srl295**
ICU-13685

Tech Preview should not be 'do not use', but `@internal` in Doxygen comes with an ominous warning.

Add `@preview` as a doxygen command such that:

> `@preview ICU 4.4` 

gives:

atpreview

### CODE REVIEW

**Comment by srl295** [comment]
@jefgen just trying to test the workflow…

**Comment by jefgen** [comment]
It seems that the most recent force push to the ICU repo caused the outstanding pull-requests to be auto-closed when the repo was updated. I'm sorry for any inconvenience this might caused.
It also seems that I am unable to "Reopen" the pull-request on GitHub either. :(

**Comment by srl295** [comment]
@jefgen https://github.com/isaacs/github/issues/361

**Comment by srl295** [comment]
@jefgen I'm unable to reopen it either, see above link. I will open a new PR.

**Comment by jefgen** [comment]
Thanks for the link @srl. (Still, might be nice if GitHub at least has some small text on the PR saying "why" the PR was auto-closed and un-reopenable...)

**Pull request closed without merging**
