### PR TITLE
ICU-20479 don’t leave junk in source directory on configure or check

### PR DESCRIPTION
**Pull request by srl295**
- similar to ICU-20062, add a `-B` option to the two python invocations
- also to a test case

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20479
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted

### CODE REVIEW

**Comment by sffc** [comment]
Do you need these in the Windows files, too?

I usually just ignore the pycache files.

**Comment by srl295** [comment]
@sffc 
> I usually just ignore the pycache files.

the problem is that the pycache files are created _in the source directory_. The source shouldn't be modified.

**Comment by srl295** [comment]
> `-B`
Would this solve the issue on Windows also? Because the .py is not invoked directly, but with `-m`

> Do you need these in the Windows files, too?

Yes, good catch.

**Comment by srl295** [comment]
@roubert these aren't invoked as scripts but as python modules. So I don't think -B can be put in the module header because python's already running.

**Comment by roubert** [comment]
> @roubert these aren't invoked as scripts but as python modules. So I don't think -B can be put in the module header because python's already running.

Ah, I see. What I want to achieve here is to minimize the risk that this is forgotten somewhere in the future, when editing or adding new build rules. Another idea to mitigate that risk could be to export the `PYTHONDONTWRITEBYTECODE` environment variable in `configure.ac` so that it gets propagated from there to everywhere.

It seems you haven't checked _Allow edits from maintainers_ on this PR, so I've instead attached a git patch file that you can apply if you think this seems like a good idea.

[0001-Code-review-Set-PYTHONDONTWRITEBYTECODE-in-configure.patch.txt](https://github.com/unicode-org/icu/files/2941307/0001-Code-review-Set-PYTHONDONTWRITEBYTECODE-in-configure.patch.txt)

**Comment by roubert** [comment]
> […], so I've instead attached a git patch file that you can apply if you think this seems like a good idea.

Oops, I forgot the change to `Makefile.in`.

[0002-Code-review-Set-PYTHONDONTWRITEBYTECODE-in-Makefile..patch.txt](https://github.com/unicode-org/icu/files/2941397/0002-Code-review-Set-PYTHONDONTWRITEBYTECODE-in-Makefile.patch.txt)

**Comment by roubert** [comment]
> Oops, I forgot the change to `Makefile.in`.

But thinking about it, modifying `icudefs.mk.in` instead is probably a better idea. That way it'd be used everywhere anyone would ever invoke Python from any of our makefiles.

[0002-Code-review-Set-PYTHONDONTWRITEBYTECODE-in-icudefs.m.patch.txt](https://github.com/unicode-org/icu/files/2946068/0002-Code-review-Set-PYTHONDONTWRITEBYTECODE-in-icudefs.m.patch.txt)

**Comment by srl295** [comment]
@roubert 
> It seems you haven't checked Allow edits from maintainers on this PR

actually, i had checked that.

**Comment by srl295** [comment]
@roubert merged your patches.

@jefgen  can you test the above on windows?

**Comment by sffc** [comment]
Why do you use `-B` on Windows but `PYTHONDONTWRITEBYTECODE` on Unix?  Does the latter not work on Windows?

**Comment by roubert** [comment]
> actually, i had checked that.

Very mysterious, I got some kind of permission denied error. (If it happens again, I'll investigate it then.)

The autoconf / Unix changes look good to me like this.

**Comment by sffc** [comment]
> > actually, i had checked that.
> 
> Very mysterious, I got some kind of permission denied error. (If it happens again, I'll investigate it then.)
> 
> The autoconf / Unix changes look good to me like this.

Sometimes when pushing to other people's ICU branches, I've had to temporarily remove (or comment out) the file `.git/hooks/pre-push`

**Comment by roubert** [comment]
> Sometimes when pushing to other people's ICU branches, I've had to temporarily remove (or comment out) the file `.git/hooks/pre-push`; seems to be a bug with GitHub LFS

Fascinating! That was indeed the problem. I managed to work around it by adding my own fork as the upstream LFS also for this remote in my `.git/config`, like this:

```
[remote "srl295"]
        url = git@github.com:srl295/icu.git
        fetch = +refs/heads/*:refs/remotes/srl295/*
        lfsurl = git@github.com:roubert/icu.git
```

With that last line added, `git push` suddenly worked like a charm! ;-)

**Comment by srl295** [comment]
@roubert @sffc indeed fascinating… can you file something at https://github.com/git-lfs/git-lfs/issues ? 

I'm going to rebase and squash this. I think it's ready to go if we can test it on windows.

**Comment by srl295** [comment]
^ the bot actually detected the effects of rebasing to master instead of maint. 

also, `Co-authored-by:` FTW

**Comment by jefgen** [comment]
I did a clean check-out of your branch, and FWIW, when building in Visual Studio 2017 I no longer see the `__pycache__` folders under the paths:
- icu/source/data/buildtool
- icu/source/data/buildtool/renderers
- icu/source/test/testdata

**Comment by srl295** [comment]
OK i think we are then ready to go once reviews are in…

**Comment by srl295** [comment]
> The bot works best when the parent sha stays the same across the squash.
Twas my err.

**Pull request merged**
