### PR TITLE
ICU-22724 BRS_76_GA Update version number to 76.1 (No more -SNAPSHOT)

### PR DESCRIPTION
**Pull request by rp9-next**
Updates ICU version number to 76.1
Ready to merge once approved

#### Checklist
- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22724
- [x] Required: The PR title must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
thank you!

**Comment by mihnita** [comment]
This file still needs to be updated: icu4j/releases_tools/shared.sh

Contains an `rc` (`export github_rel_version='76rc'`)

Thank you,
Mihai

**Comment by markusicu** [comment]
> This file still needs to be updated: icu4j/releases_tools/shared.sh
> 
> Contains an `rc` (`export github_rel_version='76rc'`)

Rahul _is_ updating that in this PR, to `github_rel_version='76_1'`.
Looks like this is complete and can be merged?

**Review by mihnita — APPROVED** [review]
Thank you,
M

**Pull request merged**
