### PR TITLE
ICU-22073 Do not throw away CompactDecimalFormat's affixes

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22073
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by macchiati — DISMISSED** [review]

**Comment by macchiati** [comment]
Thanks!!

**Comment by sffc** [comment]
I pushed an extra test demonstrating that it works with CompactCustomData. Note that I needed to pass the third argument to the pattern parser:

```java
                PatternStringParser.parseToExistingProperties(
                    "0 foo", props, PatternStringParser.IGNORE_ROUNDING_ALWAYS);
```

Otherwise the pattern started overriding the rounding behavior, which is undesirable.

**Comment by macchiati** [comment]
Great, I'll add that to the CLDR code.

Note: am now debugging another CompactNumber bug:
https://unicode-org.atlassian.net/browse/CLDR-15762

"Upon review of https://st.unicode.org/cldr-apps/v#r_compact/cs// our Czech vetter noted that some of the plural formats are incorrect. For example, “1,1 milionů” should be “1,1 milionu”, as directed by https://st.unicode.org/cldr-apps/v#/cs/Compact_Decimal_Formatting/6cbd4b7d742691c (“many”). 

It appears that the examples in the report do not take the appropriate plural rules into account."

I looked into it, and verified that "1,1 milionu" (pattern for 'many') should be generated, not “1,1 milionů” (pattern for 'other'). So I'll try to find out where the wrong answer is coming from.

**Comment by macchiati** [comment]
I fixed the 1,1 milionů problem on the CLDR side, so that doesn't need ICU changes.

**Review by macchiati — APPROVED** [review]

**Pull request merged**
