### PR TITLE
ICU-21546 BRS69GA Update version numbers for 69GA

### PR DESCRIPTION
**Pull request by erik0686**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21546
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by daniel-ju — APPROVED** [review]
lgtm, thanks!

**Review by jefgen — CHANGES_REQUESTED** [review]
Thanks! However, IIRC, this needs to go into `maint/maint-69` though. :)
(It will get merged back into `main` later on as part of the large merge commit later).

**Comment by erik0686** [comment]
@jefgen thanks :) I think since my branch was checked out from main, the history doesn't exactly match maint/maint-69, I will probably have to redo this with a branch that was checked from maint/maint-69

**Comment by jefgen** [comment]
> I think since my branch was checked out from main, the history doesn't exactly match maint/maint-69, I will probably have to redo this with a branch that was checked from maint/maint-69

Sounds good. Thanks!

Note: The new PR is here: https://github.com/unicode-org/icu/pull/1677

**Pull request closed without merging**
