### PR TITLE
ICU-22549 Add fuzzer for NumberFormatter

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22549
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [X] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by richgillam — APPROVED** [review]
This looks okay to me, I think, but I'd like @sffc or somebody else more familiar with `NumberFormatter` to weigh in on whether there are additional APIs on this class you should be fuzzing.

**Review by sffc — COMMENTED** [review]
Suggestion: take 4 bytes of the input and make them into a floating point number to be formatted. Parsing the skeleton is good, but we can also cover data loading. However, doing so will make the fuzzer a bit slower.

**Review by richgillam — APPROVED** [review]
I like it.  Hopefully Shane does too.

**Review by sffc — COMMENTED** [review]
Looks right; it's possible I missed something in all the pointer math

**Pull request merged**
