### PR TITLE
ICU-21825 Integrate tzdata2021a4 including America/Coral_Harbour Link…

### PR DESCRIPTION
**Pull request by yumaoka**
… fix

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21825
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — COMMENTED** [review]
Data changes lgtm.

Is ICU-21825 a duplicate of ICU-21818 ? The test failure logs look related but different. Does this fix both?

**Comment by markusicu** [comment]
Sibling icu-data PR: https://github.com/unicode-org/icu-data/pull/25

**Comment by yumaoka** [comment]
>Is ICU-21825 a duplicate of ICU-21818 ? The test failure logs look related but different. Does this fix both?

I think it requires test case change for ICU-21818. I'm so swamped this week and had no time to carefully think about test cases in previous version of ICU with recent tz changes. It's related to Coral_Harbour's messy situation although.

**Review by markusicu — APPROVED** [review]
lgtm tnx

**Pull request merged**
