### PR TITLE
ICU-13543 Do not remove -std=c++11 from compiler flags on Solaris

### PR DESCRIPTION
**Pull request by mojca**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-13543
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)

### CODE REVIEW

**Comment by mojca** [comment]
@srl295

**Review by srl295 — COMMENTED** [review]
Seems plausible from the bug report but I'd like to check the history. 

Also the pr needs a rebase.

**Comment by mojca** [comment]
> Seems plausible from the bug report but I'd like to check the history.

The history (8d4fe67a1e0da427a0ff57a45785bcefa62c73e7) says

```
commit 8d4fe67a1e0da427a0ff57a45785bcefa62c73e7
Author: Michael Ow <mow@svn...>
Date:   Tue Apr 19 21:00:50 2016 +0000

    ICU-11942 Disable certain gcc flags on solaris

    X-SVN-Rev: 38632
```

For all I know the sun studio doesn't **need** the `--std=c++11` flag, but it's plain wrong to remove flags based on operating system anyway. (If anything, they should be removed based on the compiler used.) I would be very very surprised if ICU was still capable of being compiled with the Sun studio on Solaris 10 though. (I won't even bother trying, it's usually a mission impossible for anything but trivial stuff.)

This has been broken for us for a very long time (we keep patching it locally).

> Also the pr needs a rebase.

What exactly do you mean by that?

I fail to see any newer commits in the main branch (I created the PR from a fresh copy). But even if there were some, I fail to see why a rebase of all the pull requests would be needed after every single commit in the main branch, unless there are merge conflicts, of course. GitHub offers a "Rebase and squash" option when merging via the web interface which does the rebase automatically.

**Comment by srl295** [comment]
Thanks for doing the research. 

You're right, it doesn't need a rebase. I misread.

**Review by srl295 — APPROVED** [review]
Seems fine to me; odd original behavior.

**Review by markusicu — APPROVED** [review]
rslgtm

**Comment by mojca** [comment]
@srl295: thank you very much!

Is there any chance to also look at #1961?

**Pull request merged**
