### PR TITLE
mingw-w64: add 'd' ending to binaries with Debug configuration

### PR DESCRIPTION
**Pull request by sav-ix**
Prior to pushing this to master need to figure out, why it was omitted, after this code was added to MSVC toolchain with [ICU-9985](https://unicode-org.atlassian.net/browse/ICU-9985).

### CODE REVIEW

**Comment by srl295** [comment]
@sav-ix is there an existing bug in JIRA for this^ ?

**Comment by sav-ix** [comment]
It was reported as suggestion [here](https://unicode-org.atlassian.net/browse/ICU-13138?focusedCommentId=40628&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-40628).

**Comment by jefgen** [comment]
It seems that the most recent force push to the ICU repo caused the outstanding pull-requests to be auto-closed when the repo was updated. I'm sorry for any inconvenience this might caused.
It also seems that I am unable to "Reopen" the pull-request on GitHub either. :(

**Comment by srl295** [comment]
@sav-ix  you can clone icu again and cherry pick the commit. i did it for you at https://github.com/srl295/icu/tree/sav-ix6

**Comment by sav-ix** [comment]
Done in PR https://github.com/unicode-org/icu/pull/9.

**Pull request closed without merging**
