### PR TITLE
ICU-22314 Refactor Azure CI into workflows conditional on modified paths

### PR DESCRIPTION
**Pull request by echeran**
I am guessing that this would need some special configuration on the Azure side in order to recognize these new workflow files and give them an official display name.

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22314
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
looks plausible; @rp9-next ?

**Comment by markusicu** [comment]
@rp9-next @jefgen @daniel-ju @erik0686 @jalaj-microsoft could you please take a look at this? It should reduce our CI time and resources significantly. tnx

**Review by rp9-next — DISMISSED** [review]
lgtm

**Review by rp9-next — APPROVED** [review]

**Comment by rp9-next** [comment]
@echeran I merged above triggers, renamed [existing CI pipeline](https://dev.azure.com/ms/icu/_build?definitionId=629) and created a [new pipeline for ICU4J](https://dev.azure.com/ms/icu/_build?definitionId=629) inside ADO dashboard. 

I created two draft PRs for testing.
https://github.com/unicode-org/icu/pull/2830
https://github.com/unicode-org/icu/pull/2831

However, in both I can see that only the CI-ICU4C(earstwhile CI) pipeline is triggered and the newer one is not triggerd.
I couldn't find any other settings on the ADO dashboard. I think there could be some pipeline triggers that are configured from GitHub repo settings whenever a PR is created that I do not have access to change. 

Could you check once ?

+cc @markusicu, @jefgen

**Comment by markusicu** [comment]
> @echeran I merged above triggers, renamed [existing CI pipeline](https://dev.azure.com/ms/icu/_build?definitionId=360) and created a [new pipeline for ICU4J](https://dev.azure.com/ms/icu/_build?definitionId=629) inside ADO dashboard.
> 
> I created two draft PRs for testing. #2830 #2831
> 
> However, in both I can see that only the CI-ICU4C(erstwhile CI) pipeline is triggered and the newer one is not triggerd. I couldn't find any other settings on the ADO dashboard. I think there could be some pipeline triggers that are configured from GitHub repo settings whenever a PR is created that I do not have access to change.
> 
> Could you check once ?
>

> +cc @markusicu, @jefgen

Sorry, I have no idea where to look.

+ @erik0686 @daniel-ju @mihnita

**Comment by echeran** [comment]
@rp9-next I took a look into the settings and went through a few different hypotheses. I can only rule out 1. The other hypotheses will require either you taking a look or us working together.

1. (not likely the cause) There is different syntax for Azure Pipelines for PRs vs. when you merge a PR (["PR triggers"](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers) vs. ["CI triggers"](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#ci-triggers)). So I created https://github.com/unicode-org/icu/pull/2835 to properly add triggers to the pipelines for PRs (even though the previous pipeline's syntax worked just fine on PRs and post-PR-merge commits without needing this change). I created test PRs for [ICU4C](https://github.com/unicode-org/icu/pull/2837) and [ICU4J](https://github.com/unicode-org/icu/pull/2836), but I don't think I see a difference in behavior. I then looked at the file path filter pattern syntax because according [to the docs](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&preserve-view=true&tabs=yaml#wildcards), Azure DevOps Server (ADO) only supports wildcards (ex: `*` in `icu4j/*`) in version 2022+, but not in 2020 or earlier. Removing the `/*` from `icu4j/*` didn't make a difference, either. The `CI-ICU4C` pipeline is recognized, and is executed only in the PR that touches ICU4C code, but the `CI-ICU4J` pipeline is never executed, and it is not visible in the Github admin settings for the branch protection rules in the same way that `CI-ICU4C` is visible.
2. Maybe the `CI-ICU4J` pipeline does not have permissions enabled to be publicly visible to the ICU Github repository? In the [Azure project for ICU](https://dev.azure.com/ms/icu/_build), it seems like there are multiple pipelines, but only some of them are run automatically, while the rest are ignored. The ignored pipelines seem to have been made for testing purposes. The [Github Azure app has all of the permissions its needs](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#github-app-permissions) from the ICU GH repo.
3. Maybe there needs to be a one-time initialization of the new pipelines? According to the instructions for Azure Devops (ADO) on [configuring pipelines to run for a Github repository](https://learn.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#permissions-needed-in-github-1), it says:
    > If the repo is in a GitHub organization that you own, at least once, authenticate to GitHub with OAuth using your personal GitHub account credentials. This can be done in Azure DevOps project settings under Pipelines > Service connections > New service connection > GitHub > Authorize. Grant Azure Pipelines access to your organization under "Organization access" [here](https://github.com/settings/connections/applications/0d4949be3b947c3ce4a5). You must be added as a collaborator, or your team must be added, in the repository's settings under "Collaborators and teams".

Hypothesis number 2 is something you can look at on your own and confirm. If that is not the problem, then let's work on investigating hypothesis 3 together.

It is good to figure this out. Thankfully, the Azure CI jobs for ICU4J so far seem to be similar to our existing Github Actions jobs for ICU4J, so we have test coverage for now. But in the future, if we want to have Microsoft/Windows-specific Java tests, etc., then this will become an urgent problem. Let's fix this soon before it becomes a real problem.

**Comment by echeran** [comment]
As far as getting `CI-ICU4J` into the list of checks required for a PR targeting `main` and `maint/*`, I can configure it in the repo's settings under [Branches > Branch Protection Rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule). The UI for this is peculiar: there is a text box with a prompt that says: "Search for status checks for the last week for this repository". As you start typing, it dynamically updates an autocomplete dropdown list. I was able to use this yesterday to change `CI` to `CI-ICU4C` to get Fredrik's and others' PRs unstuck. After the PR merge, I don't see `CI-ICU4J` appearing yet. 

Maybe we need to give it some time? Maybe another PR with Java changes needs to come around and trigger the check before it can be detected?

The fact that we have the `CI-ICU4J` pipeline set up properly in Azure Pipelines and being triggered automatically by Github PRs seems like the hard part. Let's make sure to keep track and get this require check configure because this is important to get the full benefit of all the work.

**Pull request merged**
