### PR TITLE
ICU-20511 Update master from maint/maint-64

### PR DESCRIPTION
**Pull request by sffc**
https://unicode-org.atlassian.net/browse/ICU-20511

### CODE REVIEW

**Comment by sffc** [comment]
Let's see if this works.  This is nothing fancier than a PR from maint/maint-64 to master.  I am prepared to rollback master if something screws up after rebase-merging this PR.

I added a new feature to the bot to put a flag in the PR description and disable the Jira issue match requirement.

https://github.com/unicode-org/jira-github-pr-check/commit/a3de9a3973bcf6a97243cee0ea3786e94be33bef

**Comment by sffc** [comment]
Actually, I think we should probably actually merge this as a merge commit.  Then we avoid any possible issues later on.  In terms of process, merging as a merge commit is actually slightly easier; just temporarily enable the merge commit green button, then disable it again when done.  Still requires you to be an admin, but at least it doesn't have to touch the command line or the protected branch privileges.

**Comment by srl295** [comment]
@sffc on the new feature: https://github.com/unicode-org/jira-github-pr-check/issues/9

**Comment by sffc** [comment]
I changed the checker again.  Now it has special behavior specifically for maintenance merges.  The var in the OP is still allowed but is no longer required.

**Comment by sffc** [comment]
I created and accepted https://unicode-org.atlassian.net/browse/ICU-20511 for the merge commit.

Can I get an approval?

I will do another merge commit next week after 64.1 is tagged.

**Pull request merged**
