### PR TITLE
ICU-22323 Remove broken link from the Chinese Calendar documentation

### PR DESCRIPTION
**Pull request by mihnita**
Reusing a generic "Documentation bugs" issue.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22323
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by mihnita** [comment]
Matches b/267168809

**Comment by markusicu** [comment]
The change is good, but the ticket is for something else, despite its generic title.
Please use ICU-22323 instead.

**Comment by mihnita** [comment]
> The change is good, but the ticket is for something else, despite its generic title. Please use [ICU-22323](https://unicode-org.atlassian.net/browse/ICU-22323) instead.

Done, updated everything to ICU-22323
Thank you,
M

**Review by markusicu — APPROVED** [review]
lgtm tnx

**Pull request merged**
