### PR TITLE
ICU-21009 LocaleMatcher() order[] always set all elements

### PR DESCRIPTION
**Pull request by markusicu**
https://unicode-org.atlassian.net/browse/ICU-21009

FYI I introduced this problem just recently in PR #1018.

### CODE REVIEW

**Comment by markusicu** [comment]
FYI I had run `valgrind ./intltest utility/LocaleMatcherTest` before & after the fix to verify the bug and the fix.

**Comment by jefgen** [comment]
> FYI I had run `valgrind ./intltest utility/LocaleMatcherTest` before & after the fix to verify the bug and the fix.

Thanks Markus! :)

**Pull request merged**
