### PR TITLE
ICU-21340 Don't coalesce adjacent list formatter fields in ICU4C

### PR DESCRIPTION
**Pull request by sffc**
I managed to fix forward.  The new code is simpler than the old code.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21340
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
The failing Travis test is a symptom of #1422.

The failing MSVC tests are because apparently I have to update the export to keep it happy.

**Review by FrankYFTang — DISMISSED** [review]
LGTM. Could you also file a ticket to remind you to also make the change in Java later too.

**Comment by pedberg-icu** [comment]
Probably needs rebasing onto latest maint/maint-68 so travis-ci test will pass.

**Comment by sffc** [comment]
https://unicode-org.atlassian.net/browse/ICU-21351

**Comment by sffc** [comment]
I squashed the branch (which should trigger an updated CI build) and filed ICU-21351 for follow-up.  PTAL

**Review by jefgen — APPROVED** [review]
rslgtm, (since Frank already reviewed and approved) -- thanks!

**Pull request merged**
