### PR TITLE
ICU-22220 BRS 73rc ICU4J Serialization test data for ICU 73.1

### PR DESCRIPTION
**Pull request by echeran**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22220
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
@yumaoka it looks like when you did this for ICU 72 (PR #2200) you removed the data for ICU 67 and added the data for ICU 72. Should this update always remove the oldest version and replace it with the newest?

**Comment by markusicu** [comment]
> @yumaoka it looks like when you did this for ICU 72 (PR #2200) you removed the data for ICU 67 and added the data for ICU 72. Should this update always remove the oldest version and replace it with the newest?

ping @yumaoka ...

**Comment by yumaoka** [comment]
> @yumaoka it looks like when you did this for ICU 72 (PR #2200) you removed the data for ICU 67 and added the data for ICU 72. Should this update always remove the oldest version and replace it with the newest?

Yes, I delete one version in every release.

**Comment by yumaoka** [comment]
In the BRS instruction, I have a step below - 
```
5. You may delete older serialization test data from the directory (but keep the oldest one - ICU_3.6).
```
We may simply change this to "Delete the oldest serialization test data after ICU 3.6 (do not delete ICU_3.6) from the directory.

**Review by yumaoka — CHANGES_REQUESTED** [review]
@echeran Can you delete `ICU_69.1` data? We delete the older one (but keeping ICU_3.6) in each release, and total of 5 back level versions including ICU 3.6.

**Comment by echeran** [comment]
The `ICU_69.1` folder was removed and the BRS task instructions updated.

**Review by yumaoka — APPROVED** [review]
LGTM

**Pull request merged**
