### PR TITLE
ICU-22888 Configure XML processors / external DTDs

### PR DESCRIPTION
**Pull request by mihnita**
#### Checklist
- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22888
- [x] Required: The PR title must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. Example: "ICU-1234 Fix xyz"
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — CHANGES_REQUESTED** [review]
It looks like you meant to make these changes for ICU-22888 not for ICU-22917.

**Comment by mihnita** [comment]
> It looks like you meant to make these changes for [ICU-22888](https://unicode-org.atlassian.net/browse/ICU-22888) not for [ICU-22917](https://unicode-org.atlassian.net/browse/ICU-22917).

Sorry. Thanks. DONE.

**Review by markusicu — APPROVED** [review]

**Comment by markusicu** [comment]
@mihnita remember to accept the ticket and merge this PR

**Comment by mihnita** [comment]
> @mihnita remember to accept the ticket and merge this PR

I discovered that there is a PR for this already: https://github.com/unicode-org/icu/pull/3243

So I reviewed it and waiting for them to update it, so that I can approve it.

I thing it would be good to let them do it.
It is their find, and their fix, not nice to "steal it".
And it might encourage them to contribute again :-)

**Comment by mihnita** [comment]
Approved and merged the Mozilla PR (#3243)

**Comment by mihnita** [comment]
Approved and merged the Mozilla PR (https://github.com/unicode-org/icu/pull/3243)

**Comment by mihnita** [comment]
Approved and merged the Mozilla PR (https://github.com/unicode-org/icu/pull/3243)

**Pull request closed without merging**
