### PR TITLE
ICU-21901 integrate CLDR release-41-beta2 to ICU main for 71ga

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21901
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

Integrate CLDR release-41-beta2 to ICU maint/maint-71 for final release. Only a couple of data changes that affect ICU:
- New SLE currency code (and name in English)
- Some updates to subdivisions

### CODE REVIEW

**Review by markusicu — COMMENTED** [review]
lgtm

**Comment by pedberg-icu** [comment]
> lgtm

@markusicu , thanks. Can you approve the PR?

**Review by markusicu — APPROVED** [review]
lgtm+approve (oops...)

**Pull request merged**
