### PR TITLE
ICU-20855 Add OSS-Fuzz fuzzing badge

### PR DESCRIPTION
**Pull request by inferno-chromium**
Add as per instructions at
https://google.github.io/oss-fuzz/getting-started/new-project-guide/#status-badge

### CODE REVIEW

**Comment by jungshik** [comment]
@FrankYFTang  , @markusicu  :  can you approve this 1-line CL?  

@inferno-chromium , I guess you need to file a ticket in the ICU bug tracker.

**Comment by inferno-chromium** [comment]
> @inferno-chromium , I guess you need to file a ticket in the ICU bug tracker.

I don't have a login for https://unicode-org.atlassian.net/projects/ICU/issues/?filter=allopenissues
This isn't a bug, so maybe can skip this step for this 1-liner.

**Comment by FrankYFTang** [comment]
> > @inferno-chromium , I guess you need to file a ticket in the ICU bug tracker.
> 
> I don't have a login for https://unicode-org.atlassian.net/projects/ICU/issues/?filter=allopenissues
> This isn't a bug, so maybe can skip this step for this 1-liner.

github won't let the PR land w/o  bug for this project.

**Comment by inferno-chromium** [comment]
> > > @inferno-chromium , I guess you need to file a ticket in the ICU bug tracker.
> > 
> > 
> > I don't have a login for https://unicode-org.atlassian.net/projects/ICU/issues/?filter=allopenissues
> > This isn't a bug, so maybe can skip this step for this 1-liner.
> 
> github won't let the PR land w/o bug for this project.

@FrankYFTang - Can you please file a one-liner bug, then add in description. I don't have permissions to create / login to issue tracker.

**Comment by sffc** [comment]
I made you ICU-20855.  Please note that you have to rewrite your commit message to include the ticket number.  You can do this manually or from the following UI:

https://us-central1-festive-cistern-138116.cloudfunctions.net/icu-jira-github-pr-check-test/squash/unicode-org/icu/877

**Comment by sffc** [comment]
Excellent; we will accept the ticket tomorrow in the weekly triage and then we can merge the PR.

**Comment by inferno-chromium** [comment]
Thank you!

**Pull request merged**
