### PR TITLE
ICU-20919 Merge maint/maint-66 into master

### PR DESCRIPTION
**Pull request by sffc**
There was a merge conflict in the jar file so I couldn't auto-merge through GitHub.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20919
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [x] Documentation is changed or added

DISABLE_JIRA_ISSUE_MATCH=true
ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by sffc** [comment]
#979 was merged into maint/maint-66, and I have reflected that in this PR.

**Comment by sffc** [comment]
There were test failures.  I re-built the jar files again and updated my branch.

**Remember:** Follow the special instructions on gitdev to merge this!  You should use a merge commit with the ICU-20919 ticket number.

**Comment by sffc** [comment]
OK, I re-built the jar files, and now most of the tests are passing again.  There is still one failure:

```
2020-02-21T01:10:37.1998842Z     [junit] Running com.ibm.icu.dev.test.rbbi.RBBITest
2020-02-21T01:10:41.7074484Z     [junit] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.529 sec
2020-02-21T01:10:41.7075704Z     [junit] TEST com.ibm.icu.dev.test.rbbi.RBBITest FAILED
```

Since this is an isolated failure, which is out of scope of this PR, I would like permission to merge this PR to master, and create a high-priority ticket to fix that test failure in a follow-up PR on master.

CC @aheninger

**Comment by sffc** [comment]
The test output is:

```
2020-02-21T01:12:03.0614150Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/5426dd4a-0843-472d-90fd-738bd1e4f337.sh
2020-02-21T01:12:03.2961261Z Testsuite: com.ibm.icu.dev.test.rbbi.RBBITest
2020-02-21T01:12:03.2963155Z Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.529 sec
2020-02-21T01:12:03.2963984Z 
2020-02-21T01:12:03.2964565Z Testcase: TestFollowing took 0.006 sec
2020-02-21T01:12:03.2965017Z Testcase: TestCurrent took 0.005 sec
2020-02-21T01:12:03.2965350Z Testcase: TestTableRebuild took 0.119 sec
2020-02-21T01:12:03.2965597Z 	FAILED
2020-02-21T01:12:03.2965927Z : Forward Table: expected true
2020-02-21T01:12:03.2966316Z junit.framework.AssertionFailedError: : Forward Table: expected true
2020-02-21T01:12:03.2966796Z 	at com.ibm.icu.dev.test.AbstractTestLog.errln(AbstractTestLog.java:80)
2020-02-21T01:12:03.2967257Z 	at com.ibm.icu.dev.test.TestFmwk.handleAssert(TestFmwk.java:666)
2020-02-21T01:12:03.2967715Z 	at com.ibm.icu.dev.test.TestFmwk.handleAssert(TestFmwk.java:647)
2020-02-21T01:12:03.2968161Z 	at com.ibm.icu.dev.test.TestFmwk.assertTrue(TestFmwk.java:548)
2020-02-21T01:12:03.2968616Z 	at com.ibm.icu.dev.test.rbbi.RBBITest.TestTableRebuild(RBBITest.java:654)
```

**Comment by FrankYFTang** [comment]
> OK, I re-built the jar files, and now most of the tests are passing again. There is still one failure:
> 
> ```
> 2020-02-21T01:10:37.1998842Z     [junit] Running com.ibm.icu.dev.test.rbbi.RBBITest
> 2020-02-21T01:10:41.7074484Z     [junit] Tests run: 20, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 4.529 sec
> 2020-02-21T01:10:41.7075704Z     [junit] TEST com.ibm.icu.dev.test.rbbi.RBBITest FAILED
> ```
> 
> Since this is an isolated failure, which is out of scope of this PR, I would like permission to merge this PR to master, and create a high-priority ticket to fix that test failure in a follow-up PR on master.
> 
> CC @aheninger

I believe you need to rebuid the jar file with the version of ICU4J of this branch. Did you do that? Or do you build the jar file with a different version of ICU4J. The test check the RBBI will build the table exactly during the test exactly as when you build the jar file. so if you are using a different version of ICU4J- say have different character property data, then the result won't match.

**Comment by sffc** [comment]
I definitely rebuilt the jar file, multiple times to make sure.  I'll check again in the morning since apparently this PR has a merge conflict again for some reason.

**Comment by FrankYFTang** [comment]
> I definitely rebuilt the jar file, multiple times to make sure. I'll check again in the morning since apparently this PR has a merge conflict again for some reason.

The question is not many times you build, but when you build it, is the version of unicode property file use to build the same one you put into the jar file. From my debugging, the rule in the jar and the rule rebuilt are the same, but the the generated stable table are not. 

I added the following to debug

--- a/icu4j/main/classes/core/src/com/ibm/icu/impl/RBBIDataWrapper.java
+++ b/icu4j/main/classes/core/src/com/ibm/icu/impl/RBBIDataWrapper.java
@@ -99,14 +99,39 @@ public boolean equals (Object other) {
                 return true;
             }
             if (!(other instanceof RBBIStateTable)) {
+              System.out.println("(!(other instanceof RBBIStateTable))");
                 return false;
             }
             RBBIStateTable otherST = (RBBIStateTable)other;
-            if (fNumStates != otherST.fNumStates) return false;
-            if (fRowLen    != otherST.fRowLen)    return false;
-            if (fFlags     != otherST.fFlags)     return false;
-            if (fReserved  != otherST.fReserved)  return false;
-            return Arrays.equals(fTable, otherST.fTable);
+            if (fNumStates != otherST.fNumStates) {
+              System.out.println("fNumStates != otherST.fNumStates");
+              return false;
+            }
+            if (fRowLen    != otherST.fRowLen) {
+              System.out.println("fRowLen    != otherST.fRowLen");
+              return false;
+            }
+            if (fFlags     != otherST.fFlags) {
+              System.out.println("fFlags     != otherST.fFlags");
+              return false;
+            }
+            if (fReserved  != otherST.fReserved)  {
+              System.out.println("fReserved  != otherST.fReserved");
+              return false;
+            }
+            if (!Arrays.equals(fTable, otherST.fTable)) {
+              System.out.println("!Arrays.equals(fTable, otherST.fTable)");
+              int tableLen = fRowLen * fNumStates / 2;  // fRowLen is bytes.
+              for (int i = 0; i < tableLen; i++) {
+                  if (fTable[i] != otherST.fTable[i]) {
+                    System.out.println("State " + i / (fRowLen / 2) + " Class " + i % (fRowLen / 2) +
+                        " are different " + fTable[i] + " vs " +  otherST.fTable[i]);
+                  }
+              }
+
+              return false;
+            }
+            return true;
         }
     }
 
diff --git a/icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITest.java b/icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITest.java
index 353d515150..f8bdf78f7a 100644
--- a/icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITest.java
+++ b/icu4j/main/tests/core/src/com/ibm/icu/dev/test/rbbi/RBBITest.java
@@ -651,6 +651,7 @@ public void TestTableRebuild() {
         for (RuleBasedBreakIterator bi: breakIterators) {
             String rules = bi.toString();
             RuleBasedBreakIterator bi2 = new RuleBasedBreakIterator(rules);
+            assertEquals("Forward Table rule", bi.toString(), bi2.toString());
             assertTrue("Forward Table",      RBBIDataWrapper.equals(bi.fRData.fFTable, bi2.fRData.fFTable));
             assertTrue("Reverse Table",      RBBIDataWrapper.equals(bi.fRData.fRTable, bi2.fRData.fRTable));

and got

State 14 Class 1 are different 27 vs 1
State 15 Class 0 are different 27 vs 1
State 15 Class 1 are different 27 vs 0
State 15 Class 12 are different 4 vs 0
State 15 Class 13 are different 4 vs 0
State 15 Class 15 are different 4 vs 0
State 15 Class 17 are different 4 vs 0
State 15 Class 21 are different 4 vs 0

Notice the rule are the same.

**Comment by FrankYFTang** [comment]
> > I definitely rebuilt the jar file, multiple times to make sure. I'll check again in the morning since apparently this PR has a merge conflict again for some reason.
> 
\\

Marks and I chat about this. What need to be rebuild probably is the C++ genbrk tool, it need to be build on top of the newer icu char property. Could you make sure clean that up and rebuild the tool (not just rebuild the data build by that tool)

**Comment by sffc** [comment]
Thanks @FrankYFTang for the investigation!  Java is passing now.  This can be checked-in as soon as I have a review.

**Comment by sffc** [comment]
Merged via merge commit.

**Pull request merged**
