### PR TITLE
Add .gitignore to ignore build artefacts

### PR DESCRIPTION
**Pull request by rsto**
Following up Steven Loommis' [comment](https://github.com/rsto/icu4c/commit/858fc93fc50ba363cdb57f6b8cfbfbe008e3e8f5#commitcomment-18530698): here is an adapted version of the .gitignore that we use in our libicu fork for the [Cyrus IMAP](https://github.com/cyrusimap/cyruslibs) project.

### CODE REVIEW

**Comment by rsto** [comment]
The Trac ticket is at http://bugs.icu-project.org/trac/ticket/12662

**Comment by srl295** [comment]
- I think ideally this would be generated from svn:ignore props. This looks like a good start though!
- out of curiosity- can you characterize your fork of ICU?

**Comment by srl295** [comment]
Also thanks for signing the Cla. As you can see, you are number one to sign via a PR. This mirror of Icu is not up to date and needs a rebase probably- but I think it will be in final form soon

**Comment by rsto** [comment]
Our fork is just to vendor versions for a bunch of core libraries. We currently use libicu in Cyrus within the  iCalendar parser and CJK word boundary analysis, where is proves to be immensely useful. Besides the .gitignore change, I don't expect any changes (but if, we'll try to get them upstream :))

Do you need anything from my side at this point for the .gitignore change?

**Comment by srl295** [comment]
> Our fork is just to vendor versions for a bunch of core libraries 

ok, great. node.js [does the same](https://github.com/nodejs/node/blob/master/tools/icu/README.md)

> Do you need anything from my side at this point for the .gitignore change?

No, think we're all set!

**Comment by srl295** [comment]
actual commit https://github.com/unicode-org/icu/commit/f4e9762723eb40a6f92c90b77c5a824aae1cd83b

**Comment by srl295** [comment]
Fixed in r39643

**Comment by srl295** [comment]
will land in ICU 59

**Pull request closed without merging**
