### PR TITLE
ICU-21249 API Change Reports for C++ and Java

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21249
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Documentation is changed or added

### CODE REVIEW

**Review by echeran — COMMENTED** [review]
Looks good.  So now you want to squash all the commits on your branch into one commit, here's how to do [that squashing](https://stackoverflow.com/a/40500677).  Once you do that, since your local branch and the branch on your personal fork on GH (`origin` remote, usually) will have diverged, you'll need to do a force push `git push -f origin [branch-name]` (branch-name optional).  Use the ticket number at the beginning of the single commit message for the squashed commit that you create.

If you would like to squash with precaution, you can create a "defensive copy" of the current state of your branch locally with `git checkout -b ReleaseDoc_68-backup`, and then switch back to your branch with `git checkout ReleaseDoc_68` and try out the git squash with confidence.  I like using the Linux program `qgit` to visualize the relationship of local and remote git branches to each other when I want to double check.

After the git commit squashing, then you'll need to update the checklist in the PR description with the ticket number as well.

**Review by echeran — DISMISSED** [review]
LGTM.

**Review by srl295 — DISMISSED** [review]

**Comment by sven-oly** [comment]
Updated to add ICU4J API Change file.

**Review by yumaoka — APPROVED** [review]
LGTM

**Comment by sven-oly** [comment]
Updated API change reports are complete.

**Comment by markusicu** [comment]
FYI  @sven-oly you can usually squash from the GitHub UI, via the "details" link on the bot that complains about multiple commits.

**Pull request merged**
