### PR TITLE
ICU-22404 new properties IDS_Unary_Operator, ID_Compat_Math_*, NFKC_SCF

### PR DESCRIPTION
**Pull request by markusicu**
- add new properties IDS_Unary_Operator, ID_Compat_Math_Start, ID_Compat_Math_Continue
- add NFKC_SCF Normalizer2
- adjust the changes.txt instructions for generating ICU4J data after recent mavenization

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22404
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by echeran — APPROVED** [review]
The updates to changes.txt and the data generation Bazel configs look good.

It makes sense to remove the instructions to update ICU4J data in the `/icu4j/maven-build` because we will not need that prorotype work directory anymore soon and will remove it.

**Review by macchiati — APPROVED** [review]

**Review by eggrobin — APPROVED** [review]

**Review by echeran — APPROVED** [review]

**Comment by FrankYFTang** [comment]
Somehow after the landing of this PR, we see a massive test failure on 
intltest format/CalendarTest/TestHebrewCalendarInTemporalLeapYear

https://unicode-org.atlassian.net/browse/ICU-22512

**Comment by FrankYFTang** [comment]
I roll back to d082de574ff13873123c55212ad20cf258ffb283 but still can reproduce the problem in format/CalendarTest/TestHebrewCalendarInTemporalLeapYear so it is unrelated to this PR. I guess that break is due to some time issue in the code and just happen that this PR land right after the time change.

**Comment by FrankYFTang** [comment]
the fix for https://unicode-org.atlassian.net/browse/ICU-22512 is in https://github.com/unicode-org/icu/pull/2610

**Pull request merged**
