### PR TITLE
ICU-20166 Adding commit-checker tool.

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed at https://unicode-org.atlassian.net :  ICU-20166
- [x] Update PR title to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
Rebased my branch against the new master.

**Comment by sffc** [comment]
@srl295 why did you label this as "incomplete"?  It isn't incomplete.  It's waiting for a review and then I can merge it into master.

**Comment by srl295** [comment]
@sffc sorry, mistake

**Comment by srl295** [comment]
@sffc 3 different tickets… how do you want to handle the merge?

**Comment by sffc** [comment]
I'll do a squash merge on the main ticket number, ICU-20166.

**Comment by sffc** [comment]
I pushed a squash commit to my branch.  I also removed REPORT.md.  Please re-approve.

**Pull request merged**
