### PR TITLE
Add Japanese new era name.

### PR DESCRIPTION
**Pull request by qiangzhao**

### CODE REVIEW

**Comment by jengelh** [comment]
`QQ`, `Qqqq`, etc. are placeholders. Reiwa/令和 ought to _replace_ them.

**Comment by qiangzhao** [comment]
> `QQ`, `Qqqq`, etc. are placeholders. Reiwa/令和 ought to _replace_ them.

Thanks for reviews, Fixed.

**Comment by yumaoka** [comment]
@qiangzhao We're not directly checking in these data changes to ICU - instead, we manage these data in Unicode CLDR project. We're working on these changes (except dictionary word break data) on CLDR side with other related changes right now, and they will be imported to ICU code base soon.

**Comment by qiangzhao** [comment]
> @qiangzhao We're not directly checking in these data changes to ICU - instead, we manage these data in Unicode CLDR project. We're working on these changes (except dictionary word break data) on CLDR side with other related changes right now, and they will be imported to ICU code base soon.

Hi, Do you mean "https://github.com/unicode-org/cldr",  But I found that it's totally an empty project, how could you manage these?

**Comment by yumaoka** [comment]
>Hi, Do you mean "https://github.com/unicode-org/cldr", But I found that it's totally an empty project, how could you manage these?

CLDR project is not yet migrated to Git yet. It's a place holder at this moment. CLDR repository is currently at SVN, and not opened for people outside of project members. (Note that, CLDR project is also migrating repo to Git soon)

In CLDR project, they are now collecting the new era name in some other locales, such as Korean, Vietnamese, Russian at this moment, and will be finalized before tomorrow in US time. This updated will be released as CLDR 35.1. CLDR SVN revision is tagged by ICU project member and convert data into ICU resource format. We plan to finish this by end of this week.

For Japanese era changes, we'll take care all necessary changes in CLDR and ICU, so you don't need to worry about it.

FYI - if you're interested in CLDR project, please look at http://cldr.unicode.org/

**Comment by qiangzhao** [comment]
> > Hi, Do you mean "https://github.com/unicode-org/cldr", But I found that it's totally an empty project, how could you manage these?
> 
> CLDR project is not yet migrated to Git yet. It's a place holder at this moment. CLDR repository is currently at SVN, and not opened for people outside of project members. (Note that, CLDR project is also migrating repo to Git soon)
> 
> In CLDR project, they are now collecting the new era name in some other locales, such as Korean, Vietnamese, Russian at this moment, and will be finalized before tomorrow in US time. This updated will be released as CLDR 35.1. CLDR SVN revision is tagged by ICU project member and convert data into ICU resource format. We plan to finish this by end of this week.
> 
> For Japanese era changes, we'll take care all necessary changes in CLDR and ICU, so you don't need to worry about it.
> 
> FYI - if you're interested in CLDR project, please look at http://cldr.unicode.org/

Okay, thanks!

**Comment by yumaoka** [comment]
Note: Transliterator_Han_Latin_EDICT.txt is not used by ICU4J library, so we won't touch it.
All other changes will be merge to ICU 64.2 through PR #587 and cherry picked to master branch after that. Closing.

Anyway, I appreciate your interest in this project.

**Pull request closed without merging**
