### PR TITLE
ICU-21430 propagate error code

### PR DESCRIPTION
**Pull request by FrankYFTang**
##### Checklist

- [X] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21430
- [X] Updated PR title and link in previous line to include Issue number
- [X] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm

**Comment by markusicu** [comment]
lots of CI failures...?

**Comment by FrankYFTang** [comment]
PTAL. I should sync to the trunk but forgot to do that and missed a test I added recently.

**Review by markusicu — APPROVED** [review]
lgtm

**Pull request merged**
