### PR TITLE
ICU-21535 Remove AppVeyor from top-level Readme

### PR DESCRIPTION
**Pull request by jefgen**
The Cygwin build was moved from AppVeyor to Azure CI in PR #1694.

This change removes the AppVeyor entry from the top-level Readme file as well.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21535
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by jefgen** [comment]
Ah, I missed this when reviewing the other PR... sorry about that.

**Comment by jefgen** [comment]
FYI: I noticed on another PR that the `/azp run` command wasn't working, so I'm going to test it here for this relatively simple PR.

**Review by daniel-ju — APPROVED** [review]

**Comment by jefgen** [comment]
> Azure Pipelines successfully started running 1 pipeline(s).

Yay, it's fixed now.

**Pull request merged**
