### PR TITLE
ICU-22401 fix build on MSVC with cpp20

### PR DESCRIPTION
**Pull request by gengjiawen**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22401
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by gengjiawen** [comment]
cc @srl295

**Review by roubert — APPROVED** [review]
LGTM

**Comment by gengjiawen** [comment]
@roubert Can you merge this ? thx

**Comment by gengjiawen** [comment]
ping

**Comment by roubert** [comment]
It'll become possible to merge this PR once the ICU-TC accepts the associated ticket in Jira (until that happens, merging is blocked).

**Review by markusicu — APPROVED** [review]
lgtm

**Pull request merged**
