### PR TITLE
ICU-21330 Use =0 and =1 plural forms in compact notation

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21330
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by echeran — APPROVED** [review]
LGTM.

Are there other instances of plural rules that use the `=0` and `=1` cases outside of compact numbers? In theory, it would be interesting to have a test that shows the difference between `ONE` and `=1`, or `ZERO` and `=0` for a non-compact number. But rules may not exist with such a pair of plural categories present. And if the original bug came up recently because this is the first known instance of a rule using `=1` / `=0`, then the question is moot.

**Review by pedberg-icu — APPROVED** [review]
Looks good, thanks

**Comment by sffc** [comment]
The model of "give me the plural form of this number" doesn't accommodate itself well to =0, =1, so other components needing this logic will need to have a bit of custom code as I did here with compact notation unfortunately.

**Review by echeran — APPROVED** [review]
Rubber stamping after the previous approval and squash + force push for single commit.

**Pull request merged**
