### PR TITLE
ICU-21369 Remove @provisional API doc tags in ICU4J

### PR DESCRIPTION
**Pull request by yumaoka**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21369
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by yumaoka** [comment]
Note: Internal JavaDoc tool `CheckTags` has been broken for long time - See [ICU-13797](https://unicode-org.atlassian.net/browse/ICU-13797).

When we started using Java enum, this tool should have been updated at that time. There some other issues in the tool because we did not run it for long time. This tool has some conditions for @provisional tag removed this time. I did not update the tool in this PR, because there are a bunch of other things out of date. Anyway, the tool does not block us to run build targets used for development/test/release.

**Review by markusicu — APPROVED** [review]
lgtm tnx

**Comment by markusicu** [comment]
Please also update documentation as appropriate.

I see "provisional" mentioned on http://site.icu-project.org/setup/java/ant

Also, don't we have some place where we have templates for what tags to use with what text? I don't see it on https://unicode-org.github.io/icu/userguide/design.html nor in the coding guidelines chapter.

**Comment by markusicu** [comment]
> Please also update documentation as appropriate.

FYI  I would be happy to get this PR merged and then the documentation updated.

**Comment by yumaoka** [comment]
>Please also update documentation as appropriate.

**Pull request merged**
