### PR TITLE
ICU-21374 Add a CFI build bot for ICU4C

### PR DESCRIPTION
**Pull request by erik0686**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21374
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [ ] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Progress? Assignee? Reviewers?
@erik0686 @jefgen @rp9-next @gnrunge

**Comment by rp9-next** [comment]
I checked with @erik0686 on this. It seems, enabling the bot opened gates for potential issues in ICU code that may have to be re-investigated. 

Considering the time gap, the build bot might also need to be re-done.

It seems @FrankYFTang was interested in helping last time. Maybe we can start working on it post 72.

**Comment by markusicu** [comment]
@FrankYFTang & @rp9-next please try to move this forward.

**Comment by FrankYFTang** [comment]
Move the content of this PR to https://github.com/unicode-org/icu/pull/2284 since I cannot push into https://github.com/erik0686/icu/tree/cfi-buildbot

**Pull request closed without merging**
