### PR TITLE
ICU-22378 Fix temperature format ignoring -u-mu-fahrenhe

### PR DESCRIPTION
**Pull request by mihnita**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22378
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by macchiati** [comment]
I suggest @younies or @sffc as reviewers.

**Review by sffc — APPROVED** [review]
Splendid!

**Comment by sffc** [comment]
MSVC failure:

```
            testIssue22378 {
            FAIL: -u-mu- honored (fr-FR); got "23\u202F\u00B0C"; expected "23\u00E2\u20AC\u00AF\u00C2\u00B0C"      
```

**Comment by mihnita** [comment]
> MSVC failure:

Noticed, thanks, on it.

**Review by sffc — APPROVED** [review]

**Review by markusicu — APPROVED** [review]
lgtm tnx

**Pull request merged**
