### PR TITLE
ICU-20019 Implement withSignificantDigits option

### PR DESCRIPTION
**Pull request by sffc**
TODO:

- [x] Update skeletons.md
- [x] Make sure all CI checks pass
- [x] Add test for behavior when number changes magnitude (9.99 -> 10)

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20019
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [x] Documentation is changed or added

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm

**Comment by sffc** [comment]
Note: the AppVeyor failure appears unrelated to this PR.

**Comment by sffc** [comment]
I added one more small commit with a few more docs and tests.

**Review by echeran — DISMISSED** [review]
LGTM

**Comment by sffc** [comment]
Squashed.

**Comment by sffc** [comment]
CI is passing.  All I need is a squash-approval.

**Review by echeran — APPROVED** [review]
Post-single commit squash approval

**Review by markusicu — APPROVED** [review]
lgtm2

**Pull request merged**
