### PR TITLE
ICU-22349 Build cygwin with -j  to run multiple cores

### PR DESCRIPTION
**Pull request by FrankYFTang**
Trying -j in the make check to see would it speed up the build process in cygwin. See https://github.com/unicode-org/icu/pull/2422 for other changes.

##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22349
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm tnx

**Comment by FrankYFTang** [comment]
Right now is "CI (C: Cygwin GCC x86_64 Release) Successful in 37m — C: Cygwin GCC x86_64 Release succeeded"
I will try to remove the cpu number after -j to see how fast it will be.

**Comment by FrankYFTang** [comment]
with just "-j" without a number after it, we got
Azure Pipelines / CI (C: Cygwin GCC x86_64 Release) succeeded 6 minutes ago in 30m 8s

so it is 7 minutes faster than the -j with 2x cores and much faster than what we use to have (> 70mins)

**Review by echeran — APPROVED** [review]
LGTM

**Review by markusicu — APPROVED** [review]
lgtm

**Comment by FrankYFTang** [comment]
@rp9-next please review. thanks

**Review by rp9-next — APPROVED** [review]
lgtm. Thanks

**Pull request merged**
