### PR TITLE
ICU-21652 add emoji properties of strings

### PR DESCRIPTION
**Pull request by markusicu**
- 7 new properties: API constants & property names
- u_stringHasBinaryProperty(s, property) & UCharacter.hasBinaryProperty(s, property)
- two additional source data files
- new genprops part for writing new binary data file uemoji.icu
- data for existing emoji properties moved from uprops.icu to uemoji.icu
  - in C++, only `Regional_Indicator` is still hardcoded; all of the other emoji properties, including existing ones like `Emoji`, now require loading uemoji.icu
- new EmojiProps implementation

Code points stored in a multi-property code point trie as usual.
Strings stored in single-property string tries.
Basic_Emoji has both code points and strings and thus uses both structures.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21652
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
FYI  just getting started, need additional commits

**Comment by markusicu** [comment]
I think I fixed the build bot failures.
Once they are all green, I plan to squash the commits. I don't think they are very useful for review one at a time.

FYI:  I walked Elango through almost all of the changes, and much context about properties in general, properties of strings, and how ICU handles them.

**Comment by markusicu** [comment]
build bots passed, squashed, PTAL

**Review by echeran — APPROVED** [review]
LGTM. I was able to get all my questions answered on all of the code (including tests, + build files, docs) in the PR during the review with Markus.

**Review by macchiati — APPROVED** [review]

**Comment by markusicu** [comment]
(The assignee is the main reviewer. Makes no sense to make the author the assignee.)

**Pull request merged**
