### PR TITLE
ICU-22535 BRS_75_GA: Update ICU version to 75.1 (no more -SNAPSHOT)

### PR DESCRIPTION
**Pull request by rp9-next**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22535
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by pedberg-icu — APPROVED** [review]

**Review by markusicu — APPROVED** [review]
thanks!

**Comment by mihnita** [comment]
Sorry, I had some days off.

I did several greps on everything we have and found these:

* `./tools/cldr/cldr-to-icu/pom.xml`:            `<version>75.0.1-SNAPSHOT</version>`
* `./tools/cldr/cldr-to-icu/build-icu-data.xml`:        `<property name="icuVersion" value="75.0.1.0"/>`
* `./tools/cldr/cldr-to-icu/build-icu-data.xml`:        `<property name="icuDataVersion" value="75.0.1.0"/>`

I don't think these are blockers.

`tools/cldr/cldr-to-icu` is used to generate the icu4c .txt data files from the CLDR .xml data files.
The resulting files don't contain an icu version, only a CLDR version.

---

General cleanup / decision:

* APIs are annotated with `InternalICU 75.0` and `@internal ICU 75.0 technology preview`, in the C/C++ version of MF2
*`./icu4c/APIChangeReport.html` contains many instances of `<span>ICU 75.0</span>`, all from the C/C++ MF2

All previous annotations only use the major version.

**Comment by rp9-next** [comment]
Thanks @mihnita for looking it up. 
I have raised a fresh PR #2965 for fixing version numbers in `./tools/cldr/cldr-to-icu/build-icu-data.xml`
For `./tools/cldr/cldr-to-icu/pom.xml`, I can't find 75.1 at the moment at https://github.com/unicode-org/icu/packages/1954682/versions (though 75.1-SNAPSHOT) is listed.

Do we want to create a seperate BRS item for updating `./tools/cldr/cldr-to-icu/pom.xml` ?

**Comment by markusicu** [comment]
> I have raised a fresh PR #2965 for fixing version numbers in `build-icu-data.xml`.

Thanks!

> For `./tools/cldr/cldr-to-icu/pom.xml`, I can't find 75.1 at the moment at https://github.com/unicode-org/icu/packages/1954682/versions (though 75.1-SNAPSHOT is listed).

It's a dependency. You can't find 75.1 until we tag that release.

> Do we want to create a seperate BRS item for updating the dependency version in `./tools/cldr/cldr-to-icu/pom.xml` ?

It seems like all of these dependency and output version numbers here should be updated in CLDR-to-ICU integrations, and so the instructions for that should say so. @mihnita @dra8an @pedberg-icu @echeran

**Comment by markusicu** [comment]
> General cleanup / decision:
> 
> * APIs are annotated with `InternalICU 75.0` and `@internal ICU 75.0 technology preview`, in the C/C++ version of MF2
> * `./icu4c/APIChangeReport.html` contains many instances of `<span>ICU 75.0</span>`, all from the C/C++ MF2
> 
> All previous annotations only use the major version (for example `InternalICU 73`, `DraftICU 74`).

I totally missed this :-(
It's inconsistent and a bit confusing, but I think it's not really bad. How about we clean this up (remove the .0) after 75?
Or do you think we should fix it now and regenerate the API change report?
@echeran @catamorphism

**Comment by catamorphism** [comment]
> > General cleanup / decision:
> > 
> > * APIs are annotated with `InternalICU 75.0` and `@internal ICU 75.0 technology preview`, in the C/C++ version of MF2
> > * `./icu4c/APIChangeReport.html` contains many instances of `<span>ICU 75.0</span>`, all from the C/C++ MF2
> > 
> > All previous annotations only use the major version (for example `InternalICU 73`, `DraftICU 74`).
> 
> I totally missed this :-( It's inconsistent and a bit confusing, but I think it's not really bad. How about we clean this up (remove the .0) after 75? Or do you think we should fix it now and regenerate the API change report? @echeran @catamorphism

No strong opinion. I just got back from vacation, but I can try to make the 75.0 => 75 change tomorrow (April 16) if it's needed.

**Comment by markusicu** [comment]
> > > General cleanup / decision:
> > > 
> > > * APIs are annotated with `InternalICU 75.0` and `@internal ICU 75.0 technology preview`, in the C/C++ version of MF2
> > > * `./icu4c/APIChangeReport.html` contains many instances of `<span>ICU 75.0</span>`, all from the C/C++ MF2
> > > 
> > > All previous annotations only use the major version (for example `InternalICU 73`, `DraftICU 74`).
> > 
> > 
> > I totally missed this :-( It's inconsistent and a bit confusing, but I think it's not really bad. How about we clean this up (remove the .0) after 75? Or do you think we should fix it now and regenerate the API change report? @echeran @catamorphism
> 
> No strong opinion. I just got back from vacation, but I can try to make the 75.0 => 75 change tomorrow (April 16) if it's needed.

@mihnita already did

**Pull request merged**
