### PR TITLE
ICU-22325 integrate release 44 alpha1 to icu

### PR DESCRIPTION
**Pull request by DraganBesevic**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22325
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

Integrated CLDR release-44-alpha1 plus the change from the following CLDR PR:
- [CLDR #3207](https://github.com/unicode-org/cldr/pull/3207) CLDR-17019 re-comment-out the mappings for jrb and jrb_Arab_MA

This is the first integration with data from the CLDR 44 Survey Tool phase; it replaces the abandoned CLDR release-44-alpha0 integration in ICU PR #2555.

Before squashing this was represented as multiple commits:
1. Binaries, binary-as-source. (no review needed)
2. Data sources from CLDR. (can spot check)
3. ICU lib/tool source, plus test data & dtd copied from CLDR.
4. Additional commits to address exhaustive test failures.

Notable changes:
- Fixed ICUCurrencyDataDisplayInfoProvider::getPluralName to properly handle the fallback setting: if fallback is false it should not prevent inheriting name data sideways across the different plural and display names for a particular currency in a particular locale.
- New unit conversion constant AMU

New logKnownIssue test skips:
- [CLDR-17021](https://unicode-org.atlassian.net/browse/CLDR-17021) Wrong mapping for und-150 in common/testData/localeIdentifiers/likelySubtags.txt
- [CLDR-17023](https://unicode-org.atlassian.net/browse/CLDR-17023) Number symbols and/or parseLenients messed up for N’Ko (nqo)
- [CLDR-17024](https://unicode-org.atlassian.net/browse/CLDR-17024) TestTimeZoneRoundTrip exhaustive fail with tz=America/Miquelon, locale=ku
- [CLDR-17026](https://unicode-org.atlassian.net/browse/CLDR-17026) Remaining roundtrip issues with new Cyrillic-Latin transform
- [CLDR-17028](https://unicode-org.atlassian.net/browse/CLDR-17028) ExhaustivePersonNameFormatterTest unit tests fails for many locales
- [ICU-22463](https://unicode-org.atlassian.net/browse/ICU-22463) ICU test failure for converting gasoline-equivalent
- [ICU-22464](https://unicode-org.atlassian.net/browse/ICU-22464) With CLDR 44 alpha0, in ee, formatting with BBB around midnight expects zã (night1), get ɣetrɔ (pm)

[CLDR-17001]: https://unicode-org.atlassian.net/browse/CLDR-17001?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ALLOW_MULTIPLE_COMMITS=true

[CLDR-17021]: https://unicode-org.atlassian.net/browse/CLDR-17021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by markusicu** [comment]
> This is currently represented as 3 commits:

Thank you!

**Review by markusicu — DISMISSED** [review]
rslgtm

**Comment by markusicu** [comment]
When the tests pass, then please rebase-and-merge the three commits.
This time I didn't really look at the generated data. Takes forever to look at that commit. I spot-checked last time.
I glanced over the code changes; look the same as before.

**Review by macchiati — APPROVED** [review]

**Comment by pedberg-icu** [comment]
@macchiati @markusicu There were 3 recent commits to fix exhaustive test failures, please re-approve when you get a chance. Then this will be squashed which will require another re-approval.

**Comment by pedberg-icu** [comment]
OK, passed all tests including exhaustive. I went ahead and squashed. @macchiati @markusicu  please revamp when you get a chance, thanks! Then we can finally merge this.

**Comment by pedberg-icu** [comment]
> rslgtm tnx

Thanks!

**Pull request merged**
