### PR TITLE
ICU-21210 Fix Visual Studio static builds

### PR DESCRIPTION
**Pull request by cgohlke**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21210
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

See also https://github.com/ovalhub/pyicu/issues/135

### CODE REVIEW

**Review by srl295 — DISMISSED** [review]

**Review by jefgen — APPROVED** [review]
lgtm, thanks!

**Comment by jefgen** [comment]
Thanks for fixing the commit message!

**Comment by cgohlke** [comment]
Sorry for the delay.

**Comment by jefgen** [comment]
> Sorry for the delay.

No problem. Thank you kindly for the fix!

**Pull request merged**
