### PR TITLE
ICU-21957 ICU4J API status and change report for ICU 72

### PR DESCRIPTION
**Pull request by sven-oly**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21957
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm tnx

I realized that you/we do need to update the API change report once more after the feature freeze, when things like the new MessageFormatter are in. But I think it's harmless to check this interim version into main now. @yumaoka ok?

@srl295 why does the CLA assistant seem to think that @sven-oly has not signed the CLA yet? Do I need to kick it to rescan PRs?

**Comment by sven-oly** [comment]
I'm also trying to understand the issue with the CLA. My github sven-oly has two emails attached: cwcornelius@gmail.com and ccornelius@unicode.org, both verified.

**Comment by srl295** [comment]
> I'm also trying to understand the issue with the CLA. My github sven-oly has two emails attached: [cwcornelius@gmail.com](mailto:cwcornelius@gmail.com) and [ccornelius@unicode.org](mailto:ccornelius@unicode.org), both verified.

It's not by email but by github id.

**Comment by sven-oly** [comment]
Thanks, Steven. I've added my Google email to sven-oly and verified the email. Hoping that this now ticks all the boxes.

**Comment by markusicu** [comment]
Great, thanks Steven!

However, I think I approved prematurely.
@sven-oly please send an email to the icu-team with a link to your spreadsheet and to the [API change report](https://htmlpreview.github.io/?https://github.com/unicode-org/icu/blob/main/icu4j/APIChangeReport.html), so that everyone is on notice on what's changing.

**Pull request merged**
