### PR TITLE
ICU-20453 Add more warning types to CI build.

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20453
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
I think there are still some warnings that might not be covered by the CI build.  At least, they don't seem to be included in -Wall.  Can you verify?

These are both warning categories that caused problems with the V8 integration last cycle.

**Comment by sffc** [comment]
According to this list, the two warnings I'm adding are not included in either Wall or Westra:

https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html

**Comment by sffc** [comment]
Also: I propose this PR for the maintenance branch.

**Comment by jefgen** [comment]
It doesn't look like Clang's setting for `-Wall` enables `-Wundef` or `-Wnon-virtual-dtor` either.

**Comment by markusicu** [comment]
ICU meeting says ok to merge into maint-65 branch.

**Pull request merged**
