### PR TITLE
ICU-22165 Update ICU tzdata to 2022d

### PR DESCRIPTION
**Pull request by yumaoka**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22165
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — DISMISSED** [review]
lgtm tnx!

**Comment by markusicu** [comment]
@yumaoka Unfortunately, you have a merge conflict, probably with Peter's CLDR-to-ICU update -- so please rebase, and rebuild the icutzdata.jar.

**Review by markusicu — APPROVED** [review]
lgtm

**Comment by FrankYFTang** [comment]
Could this be merged into trunk ASAP? chromium tz update process depends on the latest code on trunk.

**Comment by markusicu** [comment]
> Could this be merged into trunk ASAP? chromium tz update process depends on the latest code on trunk.

Yoshito merged it around lunch time (PT) last Friday.

**Comment by echeran** [comment]
> Could this be merged into trunk ASAP? chromium tz update process depends on the latest code on trunk.

By "trunk", do you mean the `main` branch? Or is the branch for the 72 release `maint/maint-72` sufficient?

**Pull request merged**
