### PR TITLE
ICU-22537 Fix CI checks to run with UCONFIG_NO_SERVICE

### PR DESCRIPTION
**Pull request by echeran**
##### Checklist

- [X] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22537
- [X] Required: The PR title must be prefixed with a JIRA Issue number. 
- [X] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [X] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [X] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by srl295 — APPROVED** [review]
no typo, no service

**Comment by srl295** [comment]
I'm a little confused as to why the test passed https://github.com/unicode-org/icu/actions/runs/6472786981/job/17574137794?pr=2667

**Review by markusicu — APPROVED** [review]
tnx!

**Comment by srl295** [comment]
😅 Ok! I looked in the wrong place, https://github.com/unicode-org/icu/actions/runs/6472786981/job/17574138437?pr=2667 did indeed fail.

**Comment by echeran** [comment]
Merged the latest from `maint/maint-74` into the branch to pick up @srl295 's fix. Need a rubber stamp is all goes well.

I'm glad that the CI test fix was able to reproduce the problem before merging in the code fix.

**Review by markusicu — APPROVED** [review]

**Comment by srl295** [comment]
> I'm glad that the CI test fix was able to reproduce the problem before merging in the code fix.

100% on that…

**Review by srl295 — APPROVED** [review]

**Pull request merged**
