### PR TITLE
ICU-20155 Add ARC architecture support

### PR DESCRIPTION
**Pull request by abrodkin**
This adds support for ARC architecture so we may build and use ICU on ARC cores.

##### Checklist

- [x] Issue filed at https://unicode-org.atlassian.net :  ICU-20155
- [x] Update PR title to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by srl295** [comment]
@abrodkin please rebase against current origin/master of ICU. (we did a rebase…)

**Comment by srl295** [comment]
@abrodkin you are changing code that's pulled from https://github.com/google/double-conversion - please submit a request there (and cross link these issues)

**Comment by sffc** [comment]
@abrodkin I see only one commit of yours on this PR, which changes only two files, both of which are from the double-conversion library.  As @srl295 said, please open your PR against that project.

**Comment by srl295** [comment]
closed, @sffc owns the ticket now

**Pull request closed without merging**
