### PR TITLE
ICU-20709 Change EXCEPT_ZERO to check sign after rounding.

### PR DESCRIPTION
**Pull request by sffc**
**Tips for reviewing this PR:** I was very careful to split this PR into 3 disjoint commits which all pass tests on their own.  I suggest looking at each commit individually.

**Background:** As discussed in the ticket, we have had more in-depth discussion about what would be the best semantics for SignDisplay.EXCEPT_ZERO. I would like to make these semantics the default behavior in ICU. The changes involve numbers very close to zero.

This PR does not belong on the maintenance branch.  It is going on master for ICU 67.

@jefgen: assigning to you, but feel free to send it over to Markus or someone else.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20709
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [x] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
Ping

**Comment by jefgen** [comment]
@sffc Unfortunately, I don't think I'll have time to fully review this change. Is there perhaps somebody else that might be able to review this? Thanks.

**Comment by sffc** [comment]
@FrankYFTang See tips for review in the first post.

**Comment by sffc** [comment]
I don't want to squash for reasons described in the OP. However I'll add one more commit to change the 4 to a constant

**Comment by sffc** [comment]
OK, fixed in a follow-up commit.  If there is a strong desire, I can rewrite the first commit on the branch to include the latest change.  My preference is to just put all four commits in order on master.

**Pull request merged**
