### PR TITLE
ICU-21405 Cherry-pick maintenance commits from master to maint/maint-68

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21405
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

ALLOW_MANY_COMMITS=true
DISABLE_JIRA_ISSUE_MATCH=true

### CODE REVIEW

**Comment by markusicu** [comment]
“AppVeyor was unable to build non-mergeable pull request” -- “non-mergeable”?!

**Review by markusicu — APPROVED** [review]
lgtm after refresh, now that it shows only one new commit

**Comment by markusicu** [comment]
@sffc only AppVeyor complains, other CI bots are happy. Merge so that @jefgen can tag?

**Review by jefgen — APPROVED** [review]
lgtm, thanks

**Comment by markusicu** [comment]
@jefgen ready to tag release-68-2

**Comment by jefgen** [comment]
@daniel-ju , can you please tag? (I'm currently OOF and AFK until later tonight).

**Pull request merged**
