### PR TITLE
ICU-20133 Undeprecate Transliterator.Position#hashCode

### PR DESCRIPTION
**Pull request by gvictor**
Create a proper hash code with Objects.hash instead of returning 42

##### Checklist

- [x] Issue filed at https://unicode-org.atlassian.net :  ICU-20133
- [x] Update PR title to include Issue number
- [ ] Issue accepted
- [x] Tests included
- [x] Documentation is changed or added

### CODE REVIEW

**Comment by markusicu** [comment]
[junit] TEST com.ibm.icu.dev.test.translit.TransliteratorTest FAILED

**Comment by gvictor** [comment]
Sorry for the obvious wrong test code...  I will fix it next Monday.

**Comment by gvictor** [comment]
Thanks for the approval. I will try to seek for an approval in the next ICU-TC meeting

**Comment by markusicu** [comment]
Discussed in the team meeting. Ticket is now "accepted".
Yoshito will later clean up all hashCode() & toString() in public ICU classes.

**Pull request merged**
