### PR TITLE
ICU-21293 Fix typo in rematch.cpp comment

### PR DESCRIPTION
**Pull request by eltociear**
arguements→arguments

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21293
- [x] Updated PR title and link in previous line to include Issue number

### CODE REVIEW

**Review by markusicu — APPROVED** [review]
lgtm tnx

**Review by markusicu — CHANGES_REQUESTED** [review]
undo lgtm

I see now that you are not just fixing the typo but also moving the file to a new folder, and that's why the build bots are failing. (Looks like translating "source/i18n" into Japanese.)

**Comment by eltociear** [comment]
Thank you @markusicu !
I'd try to check and correct it.

**Comment by eltociear** [comment]
@markusicu I corrected directory and push it.
please re-review my PR.

**Review by markusicu — APPROVED** [review]
lgtm

**Comment by eltociear** [comment]
@markusicu Thank you!

**Pull request merged**
