### PR TITLE
ICU-22723 BRS_76_RC: Update version number to 76.1-SNAPSHOT

### PR DESCRIPTION
**Pull request by rp9-next**
Ready to merge once approved

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22723
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [ ] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by markusicu — APPROVED** [review]

**Comment by rp9-next** [comment]
@mihnita,  could you please review if icu4j changes are ok?
I don't want to make maven unhappy (I recall I missed a few things last time which was then fixed by @yumaoka )

**Comment by mihnita** [comment]
LGTM and approved.

Two nitpicks:

---

`./tools/cldr/cldr-to-icu/pom.xml` contains `<version>76.0.1-SNAPSHOT</version>`

It does not matter much. It does not affect anything, really.
We can decided to fix it to some value forever.
But just for completeness would be nice to keep it in sync, for now.

---

./icu4j/main/core/src/test/java/com/ibm/icu/dev/test/util/DebugUtilitiesData.java` contains
`public static final String ICU4C_VERSION="76.0.1";`

It is only used in one place, in a log statement in test.

We should probably remove it.
The log can probably take the version from official APIs, which is more reliable anyway than a hard-coded string.

**Review by mihnita — APPROVED** [review]
Thank you,
Mihai

**Review by markusicu — APPROVED** [review]
@mihnita ok now?

**Pull request merged**
