### PR TITLE
ICU-22149 Be more graceful with missing lang bundle data

### PR DESCRIPTION
**Pull request by sffc**
I have this fully covered now in ICU4C. I wrote the code for ICU4J but I haven't tested it there.

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22149
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Hi @sffc sorry for not getting to this... could you please rebase and resolve the conflict?

**Comment by markusicu** [comment]
PS: I suspect that git might not automagically adjust for the Java code having been moved around for mavenization...

**Comment by markusicu** [comment]
After this Thursday we will have to bump this to ICU 75.

**Comment by sffc** [comment]
> Hi @sffc sorry for not getting to this... could you please rebase and resolve the conflict?

Is this your only feedback? After I finish this is the PR mergeable?

**Comment by markusicu** [comment]
> Is this your only feedback? After I finish this is the PR mergeable?

I haven't really looked at it yet because of the conflict.

**Comment by sffc** [comment]
> > Is this your only feedback? After I finish this is the PR mergeable?
> 
> I haven't really looked at it yet because of the conflict.

The diff in GitHub still works.

But I went ahead and fixed it in https://github.com/unicode-org/icu/pull/2635

**Pull request closed without merging**
