### PR TITLE
ICU-22220 CLDR release-43-alpha0 (with SurveyTool data) to ICU main

### PR DESCRIPTION
**Pull request by pedberg-icu**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22220
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

Integrate CLDR release-43-alpha0 to ICU. This is the first CLDR 43 that includes Survey Tool data from this limited release, which focused on PersonName data, updated displayNames for region TR, and the new exemplar city Ciudad Juarez. This integration also adds a new measurement unit `speed-beaufort`, which currently only has data in 2-3 locales. And finally this uses a new procedure for the ICU4J maven tests (generating a large number of files in `icu4j/maven-build/maven-icu4j-datafiles/`).

### CODE REVIEW

**Comment by markusicu** [comment]
changes lgtm; there is a CI failure for Maven + Java 8 -- @echeran @mihnita ?

**Comment by pedberg-icu** [comment]
> changes lgtm; there is a CI failure for Maven + Java 8 -- @echeran @mihnita ?

@markusicu @elango It almost seems as is the ICU4J tests that I updated for the new expected results (as a result of the integration) are only getting used for the normal ant check tests and the maven JDK11 tests, but the JDK8 tests are using the old version of the tests.

**Comment by pedberg-icu** [comment]
Re-running the GHA CI / icu4c-docs-build tasks caused it to pass (previously it failed due to inability to access an azure site)

**Review by markusicu — APPROVED** [review]
lgtm tnx!

**Pull request merged**
