### PR TITLE
ICU-21613 Fix undefined behaviour in ComplexUnitsConverter::applyRounder

### PR DESCRIPTION
**Pull request by andreas-schwab**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21613
- [x] Required: The PR title must be prefixed with a JIRA Issue number.
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number.
- [ ] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Review by sffc — COMMENTED** [review]
Thanks for the PR!  Some administrative things:

- Verify if the Java code needs to be changed in addition to the C++ code; @hugovdm and @younies can verify this
- Can you add test cases for this?

**Comment by andreas-schwab** [comment]
The test case already exists.

unitUsage {
FAIL: NaN meter-and-centimeter: Unsafe Path; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"
FAIL: NaN meter-and-centimeter: Safe Path; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"
FAIL: NaN meter-and-centimeter: Skeleton Path: 'unit/meter usage/person-height': nan; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"
FAIL: NaN meter-and-centimeter: Concise Skeleton Path: 'unit/meter usage/person-height': nan; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"

} ERRORS (4) in unitUsage (630ms)

**Review by hugovdm — COMMENTED** [review]
- The C++ code change looks good to me.
- The unit tests: I've not yet taken another look at them, so I don't yet grasp when they fail, and thus that they test the fix.
- The Java implementation is using BigDecimal, which does not support NaN and +/- Inf at all. Thus out of scope for this PR.

**Comment by sffc** [comment]
@hugovdm Thanks for the review!

@andreas-schwab As soon as you take steps to make @CLAassistant happy, we can merge this PR.

**Comment by hugovdm** [comment]
> The test case already exists.
> 
> unitUsage {
> FAIL: NaN meter-and-centimeter: Unsafe Path; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"
> FAIL: NaN meter-and-centimeter: Safe Path; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"
> FAIL: NaN meter-and-centimeter: Skeleton Path: 'unit/meter usage/person-height': nan; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"
> FAIL: NaN meter-and-centimeter: Concise Skeleton Path: 'unit/meter usage/person-height': nan; got "9\u00A0223\u00A0372\u00A0036\u00A0854\u00A0775\u00A0807 m, NaN cm"; expected "0 m, NaN cm"
> 
> } ERRORS (4) in unitUsage (630ms) 

I don't understand the unit test situation: no tests are currently failing on the main branch, and this PR isn't adding new tests - under what conditions do you get to see these errors?

**Comment by sffc** [comment]
Based on the Jira ticket, @andreas-schwab sees the errors on openSUSE riscv64, which our CI currently does not cover.

**Comment by hugovdm** [comment]
> Based on the Jira ticket, @andreas-schwab sees the errors on openSUSE riscv64, which our CI currently does not cover.

Aha! Thanks. Also for the ubsan mention, as I wondered what our long-term plan will be for these kinds of errors.

So: @andreas-schwab this PR looks great to me! As Shane mentioned, just the Contributor License Agreement needing to be signed.

**Comment by younies** [comment]
@andreas-schwab , could you sign the CLA (@CLAassistant ), so you can merge this PR?

**Comment by hugovdm** [comment]
I'm guessing it may be necessary for one of us to make this change ourselves, instead of andreas-schwab, so that it isn't blocked on Andreas signing the CLA.

**Comment by thesamesam** [comment]
We've had to apply this downstream in Gentoo to avoid test failures on e.g. HPPA.

Ping @andreas-schwab.

**Comment by hugovdm** [comment]
I'm proposing an alternative implementation and PR: #1946 - it returns earlier in the function, not even applying the rounder: if we have NaN or Inf, rounding is meaningless.

**Comment by hugovdm** [comment]
#1946 has been merged into main, I'm closing this PR. Thanks for the report and the suggested fix, Andreas!

**Pull request closed without merging**
