### PR TITLE
ICU-22746 Import tests from ICU4J and make more tests data-driven

### PR DESCRIPTION
**Pull request by catamorphism**
This change brings in all the tests from ICU4J (some are marked as "ignored" with a JIRA ticket number, which is a capability I added to the JSON test harness added in #2980 .)

It also includes some code changes: to fix number selection and to fix some of the options for number formatting, which were exposed as not-working by the ICU4J tests. I chose to include these code changes in this PR so that all of the ICU4J tests could be added in one PR.

I put all of the ICU4J tests in a separate subdirectory: testdata/message2/icu4j/ . These files will need to be kept consistent with ICU4J manually (from previous discussions, I understand that there's no way to share test data between ICU4J and ICU4C). 

##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-22746
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by catamorphism** [comment]
cc @echeran @mihnita

**Comment by mihnita** [comment]
LGTM, thank you.

I think it would be good to share the files somehow, but that is not to be solved here.
Before the next release we probably need to change the .json files according to the new schema anyway.

Mihai

**Review by mihnita — APPROVED** [review]
Thank you!
M

**Comment by mihnita** [comment]
@markusicu Reviewed, but I can't squash.

I get:
> NOTICE: Your previous squash attempt failed with code 404.
> If you get this error repeatedly, you may not have permission to push to this repository.

**Comment by mihnita** [comment]
Optional, @catamorphism : you can squash the 6 commits on your side (making sure the final commit is named "ICU-22746 Import tests from ICU4J and make more tests data-driven") and force-push

**Comment by catamorphism** [comment]
Squashed, thanks!

**Comment by catamorphism** [comment]
I've rebased and force-pushed, which Mihai suggested in order to fix the MSYS2 GCC build failure.

**Pull request merged**
