### PR TITLE
ICU-21699 Add some more particles

### PR DESCRIPTION
**Pull request by allensu05**
##### Checklist

- [x] Required: Issue filed: https://unicode-org.atlassian.net/browse/ICU-21699
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [x] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [ ] API docs and/or User Guide docs changed or added, if applicable

### CODE REVIEW

**Comment by markusicu** [comment]
Please add some unit test lines with a few of these.

**Comment by hiroyuki-komatsu** [comment]
Hi Allen, how about these cases?
```
幕の内弁当がよく買われるらしいです。
その名の通りに伝われと望まれています。
```

**Review by markusicu — APPROVED** [review]
lgtm
@pedberg-icu @FrankYFTang ok?

**Comment by markusicu** [comment]
@allensu05 could you please rebase and regenerate the .jar files?

**Comment by allensu05** [comment]
> @allensu05 could you please rebase and regenerate the .jar files?

Thanks, Markus.
Rebase and build pass.

**Review by pedberg-icu — APPROVED** [review]

**Comment by markusicu** [comment]
Thanks! Merged!
@gvictor @AEApple FYI

**Pull request merged**
