### PR TITLE
ICU-21467 tzdata 2021a updates

### PR DESCRIPTION
**Pull request by yumaoka**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21467
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by markusicu** [comment]
The AppVeyor Cygwin build fails:
```
g++ -D_REENTRANT  -DU_HAVE_ELF_H=1 -DU_HAVE_STRTOD_L=1 -DU_HAVE_XLOCALE_H=0  -DWINVER=0x0601 -D_WIN32_WINNT=0x0601 -I. -I../common   -DU_ATTRIBUTE_DEPRECATED= -DU_I18N_IMPLEMENTATION -O3  -W -Wall -pedantic -Wpointer-arith -Wwrite-strings -Wno-long-long -std=c++11    -c -DPIC  -o tridpars.o tridpars.cpp
make[1]: *** [../config/mh-cygwin64:76: tridpars.o] Segmentation fault
make[1]: Leaving directory '/cygdrive/c/projects/icu/icu4c/source/i18n'
make: *** [Makefile:153: all-recursive] Error 2
Command exited with code 2
```
@jefgen looks like the compiler crashes?? Ignore? Restart?

**Review by markusicu — COMMENTED** [review]
File changes look plausible.

It would be good to update the User Guide TZ chapter about dropping the old versions. Follow-up PR?

See my comment about the AppVeyor failure.

**Comment by jefgen** [comment]
> The AppVeyor Cygwin build fails:
> looks like the compiler crashes?? Ignore? Restart?

Sigh, it looks like another flaky failure. (FWIW, I've seen crashes like this before and they generally pass on rebuild).
I'll queue a rebuild of the PR, which should likely pass on re-run...

**Comment by jefgen** [comment]
Note: The AppVeyor build passed on re-run: https://ci.appveyor.com/project/unicode-org/icu/builds/37460862

**Review by markusicu — APPROVED** [review]
lgtm tnx

no need to wait for Travis

**Pull request merged**
