### PR TITLE
ICU-20348 Fixing DecimalFormat set affix currency behavior.

### PR DESCRIPTION
**Pull request by sffc**
If this looks good, I will make the same change in ICU4J.

##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-20348
- [x] Updated PR title and link in previous line to include Issue number
- [x] Issue accepted
- [x] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by sffc** [comment]
A little bit of background: PropertiesAffixPatternProvider is a class I came up with later in my rework that does a better job of correctly resolving user-specified versus default values for the affixes.  On the other hand, PatternStringUtils::propertiesToPatternString is a method I wrote before making PropertiesAffixPatternProvider.  This PR migrates that method to use the new class.

In addition, I double-checked the logic for currency rounding in [ICU 58](https://github.com/unicode-org/icu/blob/maint/maint-58/icu4c/source/i18n/decimfmtimpl.cpp#L1061).  It always looks at the pattern for the currency sign, even if the user had overridden the affixes.  I fixed PropertiesAffixPatternProvider to have this behavior.

**Comment by sffc** [comment]
I figured out the test failure.  The file locales/fr_CH.txt has the following:

    currencyFormat{"#,##0.00 ¤;-#,##0.00 ¤"}

The negative subpattern is redundant.  The new toPattern logic strips away the negative subpattern if it is redundant.  So, although no information is lost across toPattern/applyPattern, the DecimalFormats are not equal.  Looking into a fix.

**Comment by pedberg-icu** [comment]
> I figured out the test failure. The file locales/fr_CH.txt has the following:
> ```
> currencyFormat{"#,##0.00 ¤;-#,##0.00 ¤"}
> ```

I think we should treat this as an undetected error in CLDR data, we should fix this now in ICU's copy of CLDR data. I have filed a CLDR ticket to fix this and detect such redundancies in the future: https://unicode.org/cldr/trac/ticket/11779

**Comment by sffc** [comment]
Sounds good.  I experimented with various code changes to fix the test failure and I couldn't find a clean one that didn't have side-effects.  New commit is pushed.

Now I'm porting to ICU4J.

**Comment by sffc** [comment]
ICU4J is implemented, and I performed a squash-commit.

**Pull request merged**
