### PR TITLE
ICU-20445 Pass ByteSink to ulocimp_addLikelySubtags().

### PR DESCRIPTION
**Pull request by roubert**
ALLOW_MANY_COMMITS=true

### CODE REVIEW

**Comment by roubert** [comment]
These are the changes that I cut out from PR #457 as they then weren't important enough to deal with so close to the release code freeze.

Could you please take a look at the Windows build failures and see if you can help me figure out why this doesn't work and what I ought to do about it?

**Comment by jefgen** [comment]
Hello @roubert.
I created a PR inside your fork of the ICU repo here: https://github.com/roubert/icu/pull/1

You could merge that PR into your branch, squash-merge, and then update this PR.
(Or perhaps just make the same change, since it is only one line.)

Note: It looks like this also effects the OSX builds too, so the PR above will fix them as well.

**Comment by roubert** [comment]
> Need to export CharStringByteSink class for Windows and OSX.

Ah, I see, makes sense, thank you!

**Comment by roubert** [comment]
OK, now all checks have passed. PTAL

**Pull request merged**
