### PR TITLE
ICU-21191 Improve configurability of testtagsguards.sh

### PR DESCRIPTION
**Pull request by sffc**
##### Checklist

- [x] Issue filed: https://unicode-org.atlassian.net/browse/ICU-21191
- [x] Updated PR title and link in previous line to include Issue number
- [ ] Issue accepted
- [ ] Tests included
- [ ] Documentation is changed or added

### CODE REVIEW

**Comment by markusicu** [comment]
@sffc I just realized on another PR that this does not work, but the error does not show up as a non-zero exit code from testtagsguards.sh. Does this syntax require a special shell?

https://travis-ci.org/github/unicode-org/icu/jobs/706333645
```
9.22s$ ( cd .. && source/test/hdrtst/testtagsguards.sh )
source/test/hdrtst/testtagsguards.sh: line 9: DEF:=-DU_NO_DEFAULT_INCLUDE_UTF_HEADERS=1: command not found
source/test/hdrtst/testtagsguards.sh: line 10: INCL:=-Isource/common -Isource/i18n -Isource/io: No such file or directory
source/test/hdrtst/testtagsguards.sh: line 11: TMPDIR:=/tmp/tmp.U9mOVUYnSJ: No such file or directory
source/test/hdrtst/testtagsguards.sh: line 12: DIFF:=diff -u --minimal: command not found
source/test/hdrtst/testtagsguards.sh: line 13: CXX:=clang++: command not found
*** testtagsguards.sh TMPDIR=
source/common/unicode/appendable.h
source/test/hdrtst/testtagsguards.sh: line 20: /ht-appendable.h.cpp: Permission denied
clang-7: error: no such file or directory: '/ht-appendable.h.cpp'
clang-7: error: no input files
...
    @obsolete
clang-7: error: no such file or directory: '/ht-ustream.h.cpp'
clang-7: error: no input files
grep: /ht-ustream.h-obsolete.i: No such file or directory
source/test/hdrtst/testtagsguards.sh: line 85: /ht-ustream.h-normal-obsolete.txt: Permission denied
grep: /ht-ustream.h-normal-obsolete.txt: No such file or directory
pass
The command "( cd .. && source/test/hdrtst/testtagsguards.sh )" exited with 0.
```

**Comment by sffc** [comment]
This PR does nothing that changes the behavior of the return value of this script.  It only makes certain environment variables more configurable.

**Comment by sffc** [comment]
The `:=` syntax is probably specific to Bash.  Maybe `#!/usr/bin/env bash` at the top would address it?

**Comment by markusicu** [comment]
> The `:=` syntax is probably specific to Bash. Maybe `#!/usr/bin/env bash` at the top would address it?

Plausible. Please do try to fix this so that the test is effective.

**Comment by gnrunge** [comment]
#!/usr/bin/env bash does not fix the problem. Same behaviour, see https://travis-ci.com/github/gnrunge/icu/jobs/387268661
How did you test the script? Even on command line (Linux) it fails for me.

**Comment by sffc** [comment]
https://github.com/unicode-org/icu/pull/1344

Not sure how I was running it before. 🤔

**Pull request merged**
