### PR TITLE
ICU-22875 Fixed invisible angle brackets

### PR DESCRIPTION
**Pull request by Calorion**
Made angle brackets and enclosed text visible.

##### Checklist

- [x] Required: Issue filed: [ICU-22875](https://unicode-org.atlassian.net/browse/ICU-22875)
- [x] Required: The PR title must be prefixed with a JIRA Issue number. 
- [x] Required: The PR description must include the link to the Jira Issue, for example by completing the URL in the first checklist item
- [x] Required: Each commit message must be prefixed with a JIRA Issue number. 
- [ ] Issue accepted (done by Technical Committee after discussion)
- [x] Tests included, if applicable
- [x] API docs and/or User Guide docs changed or added, if applicable

[ICU-22875]: https://unicode-org.atlassian.net/browse/ICU-22875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Calorion** [comment]
Is there a holdup on this? Some step not completed properly?

**Review by markusicu — APPROVED** [review]

**Comment by markusicu** [comment]
Oh, there is one thing missing: Please amend the commit by prepending the commit message with the ticket and a space: `ICU-22875 `

**Comment by Calorion** [comment]
I tried; apparently the only way to do that is from the command line.

**Comment by markusicu** [comment]
> I tried; apparently the only way to do that is from the command line.

That appears to be true: https://github.com/orgs/community/discussions/8891

This discussion has some instructions: https://stackoverflow.com/a/67007037
The most important parts are `git commit --amend` and `git push -f`

**Comment by Calorion** [comment]
That's nice. I'm just an end user who noticed a typo. I'm not going to install and learn to use git in order to fix your error.

**Comment by markusicu** [comment]
replaced by https://github.com/unicode-org/icu/pull/3147

**Pull request closed without merging**
